-- ============================================================================
-- MinFlix - Limpieza total de objetos del proyecto
-- Ejecutar desde database/ con SQLcl/SQL*Plus y el owner real de MinFlix
-- o con un usuario administrativo (por ejemplo SYSTEM en FREEPDB1).
--
-- ADVERTENCIA:
-- - Este script es destructivo: elimina tablas, datos, vistas, MVs, triggers,
--   funciones, procedimientos, usuarios funcionales, roles y perfil de MinFlix.
-- - No elimina el usuario conectado ni objetos generales de Oracle/SYSTEM.
-- - La lista es explicita para evitar borrar objetos ajenos al proyecto.
-- ============================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE;
SET SERVEROUTPUT ON;
SET DEFINE OFF;

PROMPT ========================================================================
PROMPT MinFlix - Inicio limpieza total
PROMPT ========================================================================

DECLARE
  PROCEDURE DROP_IF_EXISTS(P_SQL IN VARCHAR2, P_LABEL IN VARCHAR2) IS
  BEGIN
    DBMS_OUTPUT.PUT_LINE('DROP -> ' || P_LABEL);
    EXECUTE IMMEDIATE P_SQL;
    DBMS_OUTPUT.PUT_LINE('OK   -> ' || P_LABEL);
  EXCEPTION
    WHEN OTHERS THEN
      IF SQLCODE IN (
        -942,    -- tabla o vista no existe
        -12003,  -- materialized view no existe
        -4043,   -- objeto no existe
        -4080,   -- trigger no existe
        -1418,   -- indice no existe
        -2289,   -- secuencia no existe
        -1918,   -- usuario no existe
        -1919,   -- rol no existe
        -2380    -- perfil no existe
      ) THEN
        DBMS_OUTPUT.PUT_LINE('SKIP -> ' || P_LABEL || ' no existe');
      ELSE
        DBMS_OUTPUT.PUT_LINE('WARN -> ' || P_LABEL || ': ' || SQLERRM);
      END IF;
  END;
BEGIN
  DBMS_OUTPUT.PUT_LINE('1) Triggers MinFlix');
  DROP_IF_EXISTS('DROP TRIGGER TRG_UPDATE_CONTENT_METRICS', 'TRIGGER TRG_UPDATE_CONTENT_METRICS');
  DROP_IF_EXISTS('DROP TRIGGER TRG_PREVENIR_ELIMINACION_PLAN', 'TRIGGER TRG_PREVENIR_ELIMINACION_PLAN');
  DROP_IF_EXISTS('DROP TRIGGER TRG_AUDITORIA_USUARIOS', 'TRIGGER TRG_AUDITORIA_USUARIOS');
  DROP_IF_EXISTS('DROP TRIGGER TRG_EMPLEADOS_REGLAS_BIU', 'TRIGGER TRG_EMPLEADOS_REGLAS_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_EMPLEADOS_JERARQUIA_BIU', 'TRIGGER TRG_EMPLEADOS_JERARQUIA_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_CONTENIDOS_PUBLICADOR_BIU', 'TRIGGER TRG_CONTENIDOS_PUBLICADOR_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_PAGOS_FACTURACION_BIU', 'TRIGGER TRG_PAGOS_FACTURACION_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_PAGOS_ACTUALIZA_FACTURA_AI', 'TRIGGER TRG_PAGOS_ACTUALIZA_FACTURA_AI');
  DROP_IF_EXISTS('DROP TRIGGER TRG_REFERIDOS_REGLAS_BIU', 'TRIGGER TRG_REFERIDOS_REGLAS_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_FACTURACIONES_CALCULO_BIU', 'TRIGGER TRG_FACTURACIONES_CALCULO_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_REPORTES_AUDITORIA_BIU', 'TRIGGER TRG_REPORTES_AUDITORIA_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_REPORTES_REGLAS_BIU', 'TRIGGER TRG_REPORTES_REGLAS_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_CONTENIDOS_RELACIONADOS_BI', 'TRIGGER TRG_CONTENIDOS_RELACIONADOS_BI');
  DROP_IF_EXISTS('DROP TRIGGER TRG_TEMPORADAS_TIPO_CONTENIDO_BIU', 'TRIGGER TRG_TEMPORADAS_TIPO_CONTENIDO_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_CALIFICACIONES_VALIDACION_BIU', 'TRIGGER TRG_CALIFICACIONES_VALIDACION_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_CALIFICACIONES_REGLAS_BIU', 'TRIGGER TRG_CALIFICACIONES_REGLAS_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_FAVORITOS_REGLAS_BI', 'TRIGGER TRG_FAVORITOS_REGLAS_BI');
  DROP_IF_EXISTS('DROP TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU', 'TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU');
  DROP_IF_EXISTS('DROP TRIGGER TRG_PERFILES_LIMITE_PLAN_BI', 'TRIGGER TRG_PERFILES_LIMITE_PLAN_BI');
  DROP_IF_EXISTS('DROP TRIGGER TRG_ACTUALIZAR_FECHA_USUARIO', 'TRIGGER TRG_ACTUALIZAR_FECHA_USUARIO');
  DROP_IF_EXISTS('DROP TRIGGER TRG_LIMITE_PERFILES', 'TRIGGER TRG_LIMITE_PERFILES');

  DBMS_OUTPUT.PUT_LINE('2) Vistas y vistas materializadas MinFlix');
  DROP_IF_EXISTS('DROP VIEW VW_CONTENT_PERFORMANCE', 'VIEW VW_CONTENT_PERFORMANCE');
  DROP_IF_EXISTS('DROP VIEW VW_USER_ACTIVITY', 'VIEW VW_USER_ACTIVITY');
  DROP_IF_EXISTS('DROP VIEW VW_REVENUE_BY_PLAN', 'VIEW VW_REVENUE_BY_PLAN');
  DROP_IF_EXISTS('DROP VIEW VW_MOST_WATCHED', 'VIEW VW_MOST_WATCHED');
  DROP_IF_EXISTS('DROP VIEW VW_FACTURACION_COMPLETA', 'VIEW VW_FACTURACION_COMPLETA');
  DROP_IF_EXISTS('DROP VIEW VW_DESEMPENO_CATEGORIAS', 'VIEW VW_DESEMPENO_CATEGORIAS');
  DROP_IF_EXISTS('DROP VIEW VW_RETENCION_USUARIOS', 'VIEW VW_RETENCION_USUARIOS');
  DROP_IF_EXISTS('DROP VIEW VW_INGRESOS_MENSUALES', 'VIEW VW_INGRESOS_MENSUALES');
  DROP_IF_EXISTS('DROP VIEW VW_CONTENIDOS_POPULARES', 'VIEW VW_CONTENIDOS_POPULARES');
  DROP_IF_EXISTS('DROP VIEW VW_CATALOGO_ADMIN_API', 'VIEW VW_CATALOGO_ADMIN_API');
  DROP_IF_EXISTS('DROP VIEW VW_PERFILES_ADMIN_API', 'VIEW VW_PERFILES_ADMIN_API');
  DROP_IF_EXISTS('DROP VIEW VW_USUARIOS_ADMIN_API', 'VIEW VW_USUARIOS_ADMIN_API');
  DROP_IF_EXISTS('DROP VIEW VW_RESUMEN_FINANCIERO_USUARIO', 'VIEW VW_RESUMEN_FINANCIERO_USUARIO');
  DROP_IF_EXISTS('DROP VIEW VW_PAGOS_USUARIO_API', 'VIEW VW_PAGOS_USUARIO_API');
  DROP_IF_EXISTS('DROP VIEW VW_FACTURAS_USUARIO_API', 'VIEW VW_FACTURAS_USUARIO_API');
  DROP_IF_EXISTS('DROP VIEW VW_ANALITICA_RENDIMIENTO', 'VIEW VW_ANALITICA_RENDIMIENTO');
  DROP_IF_EXISTS('DROP VIEW VW_ANALITICA_FINANZAS', 'VIEW VW_ANALITICA_FINANZAS');
  DROP_IF_EXISTS('DROP VIEW VW_ANALITICA_CONSUMO', 'VIEW VW_ANALITICA_CONSUMO');
  DROP_IF_EXISTS('DROP VIEW VW_FIN_REFERIDOS_DETALLE', 'VIEW VW_FIN_REFERIDOS_DETALLE');
  DROP_IF_EXISTS('DROP VIEW VW_FIN_PAGOS_DETALLE', 'VIEW VW_FIN_PAGOS_DETALLE');
  DROP_IF_EXISTS('DROP VIEW VW_FIN_FACTURAS_DETALLE', 'VIEW VW_FIN_FACTURAS_DETALLE');
  DROP_IF_EXISTS('DROP VIEW VW_FIN_RESUMEN_USUARIO', 'VIEW VW_FIN_RESUMEN_USUARIO');
  DROP_IF_EXISTS('DROP VIEW VW_REPORTES_PENDIENTES_SOPORTE', 'VIEW VW_REPORTES_PENDIENTES_SOPORTE');
  DROP_IF_EXISTS('DROP VIEW VW_CONTINUAR_VIENDO', 'VIEW VW_CONTINUAR_VIENDO');
  DROP_IF_EXISTS('DROP VIEW VW_CONTENIDO_VISIBLE_POR_PERFIL', 'VIEW VW_CONTENIDO_VISIBLE_POR_PERFIL');

  DROP_IF_EXISTS('DROP MATERIALIZED VIEW MV_CONTENIDO_POPULARIDAD', 'MATERIALIZED VIEW MV_CONTENIDO_POPULARIDAD');
  DROP_IF_EXISTS('DROP MATERIALIZED VIEW MV_ANALITICA_INGRESOS_MENSUALES', 'MATERIALIZED VIEW MV_ANALITICA_INGRESOS_MENSUALES');
  DROP_IF_EXISTS('DROP MATERIALIZED VIEW MV_ANALITICA_REPRODUCCION_DIARIA', 'MATERIALIZED VIEW MV_ANALITICA_REPRODUCCION_DIARIA');
  DROP_IF_EXISTS('DROP MATERIALIZED VIEW MV_METRICAS_FINANCIERAS', 'MATERIALIZED VIEW MV_METRICAS_FINANCIERAS');
  DROP_IF_EXISTS('DROP MATERIALIZED VIEW MV_CALIFICACIONES_PROMEDIO', 'MATERIALIZED VIEW MV_CALIFICACIONES_PROMEDIO');

  DBMS_OUTPUT.PUT_LINE('3) Procedimientos y funciones MinFlix');
  DROP_IF_EXISTS('DROP PROCEDURE SP_RECALCULAR_METRICAS_CONTENIDO', 'PROCEDURE SP_RECALCULAR_METRICAS_CONTENIDO');
  DROP_IF_EXISTS('DROP PROCEDURE SP_REGISTRAR_PAGO_FACTURA', 'PROCEDURE SP_REGISTRAR_PAGO_FACTURA');
  DROP_IF_EXISTS('DROP PROCEDURE SP_CAMBIAR_PLAN', 'PROCEDURE SP_CAMBIAR_PLAN');
  DROP_IF_EXISTS('DROP PROCEDURE SP_REGISTRAR_USUARIO', 'PROCEDURE SP_REGISTRAR_USUARIO');
  DROP_IF_EXISTS('DROP PROCEDURE SP_APLICAR_MORA_CUENTAS', 'PROCEDURE SP_APLICAR_MORA_CUENTAS');

  DROP_IF_EXISTS('DROP FUNCTION FN_USUARIO_ACTIVO', 'FUNCTION FN_USUARIO_ACTIVO');
  DROP_IF_EXISTS('DROP FUNCTION FN_PROMEDIO_CALIFICACION_CONTENIDO', 'FUNCTION FN_PROMEDIO_CALIFICACION_CONTENIDO');
  DROP_IF_EXISTS('DROP FUNCTION FN_TOTAL_PAGADO_USUARIO', 'FUNCTION FN_TOTAL_PAGADO_USUARIO');
  DROP_IF_EXISTS('DROP FUNCTION FN_ES_MAYOR_EDAD', 'FUNCTION FN_ES_MAYOR_EDAD');
  DROP_IF_EXISTS('DROP FUNCTION FN_CALCULAR_DESCUENTO_REFERIDO', 'FUNCTION FN_CALCULAR_DESCUENTO_REFERIDO');
  DROP_IF_EXISTS('DROP FUNCTION FN_CONTENIDO_RECOMENDADO', 'FUNCTION FN_CONTENIDO_RECOMENDADO');
  DROP_IF_EXISTS('DROP FUNCTION FN_CALCULAR_MONTO', 'FUNCTION FN_CALCULAR_MONTO');
  DROP_IF_EXISTS('DROP FUNCTION FN_CLASIFICACION_PERMITIDA_PARA_PERFIL', 'FUNCTION FN_CLASIFICACION_PERMITIDA_PARA_PERFIL');

  DBMS_OUTPUT.PUT_LINE('4) Tablas MinFlix');
  DROP_IF_EXISTS('DROP TABLE TMP_POPULARIDAD_CATALOGO CASCADE CONSTRAINTS PURGE', 'TABLE TMP_POPULARIDAD_CATALOGO');
  DROP_IF_EXISTS('DROP TABLE REPRODUCCIONES_BKP CASCADE CONSTRAINTS PURGE', 'TABLE REPRODUCCIONES_BKP');
  DROP_IF_EXISTS('DROP TABLE REPORTES CASCADE CONSTRAINTS PURGE', 'TABLE REPORTES');
  DROP_IF_EXISTS('DROP TABLE PAGOS CASCADE CONSTRAINTS PURGE', 'TABLE PAGOS');
  DROP_IF_EXISTS('DROP TABLE FACTURACIONES CASCADE CONSTRAINTS PURGE', 'TABLE FACTURACIONES');
  DROP_IF_EXISTS('DROP TABLE REFERIDOS CASCADE CONSTRAINTS PURGE', 'TABLE REFERIDOS');
  DROP_IF_EXISTS('DROP TABLE EMPLEADOS CASCADE CONSTRAINTS PURGE', 'TABLE EMPLEADOS');
  DROP_IF_EXISTS('DROP TABLE DEPARTAMENTOS CASCADE CONSTRAINTS PURGE', 'TABLE DEPARTAMENTOS');
  DROP_IF_EXISTS('DROP TABLE CALIFICACIONES CASCADE CONSTRAINTS PURGE', 'TABLE CALIFICACIONES');
   DROP_IF_EXISTS('DROP TABLE FAVORITOS CASCADE CONSTRAINTS PURGE', 'TABLE FAVORITOS');
   DROP_IF_EXISTS('DROP TABLE ROLES_USUARIOS CASCADE CONSTRAINTS PURGE', 'TABLE ROLES_USUARIOS');
  DROP_IF_EXISTS('DROP TABLE REPRODUCCIONES CASCADE CONSTRAINTS PURGE', 'TABLE REPRODUCCIONES');
  DROP_IF_EXISTS('DROP TABLE CONTENIDOS_RELACIONADOS CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDOS_RELACIONADOS');
  DROP_IF_EXISTS('DROP TABLE CONTENIDO_RELACIONADO CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDO_RELACIONADO');
  DROP_IF_EXISTS('DROP TABLE EPISODIOS CASCADE CONSTRAINTS PURGE', 'TABLE EPISODIOS');
  DROP_IF_EXISTS('DROP TABLE TEMPORADAS CASCADE CONSTRAINTS PURGE', 'TABLE TEMPORADAS');
  DROP_IF_EXISTS('DROP TABLE CONTENIDOS_GENEROS CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDOS_GENEROS');
  DROP_IF_EXISTS('DROP TABLE CONTENIDO_GENEROS CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDO_GENEROS');
  DROP_IF_EXISTS('DROP TABLE GENEROS CASCADE CONSTRAINTS PURGE', 'TABLE GENEROS');
  DROP_IF_EXISTS('DROP TABLE CONTENIDOS CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDOS');
  DROP_IF_EXISTS('DROP TABLE CONTENIDO CASCADE CONSTRAINTS PURGE', 'TABLE CONTENIDO');
  DROP_IF_EXISTS('DROP TABLE CATEGORIAS CASCADE CONSTRAINTS PURGE', 'TABLE CATEGORIAS');
  DROP_IF_EXISTS('DROP TABLE PERFILES CASCADE CONSTRAINTS PURGE', 'TABLE PERFILES');
  DROP_IF_EXISTS('DROP TABLE USUARIOS CASCADE CONSTRAINTS PURGE', 'TABLE USUARIOS');
  DROP_IF_EXISTS('DROP TABLE PLANES CASCADE CONSTRAINTS PURGE', 'TABLE PLANES');

  DBMS_OUTPUT.PUT_LINE('5) Usuarios, roles y perfil funcional MinFlix');
  DROP_IF_EXISTS('DROP USER MINFLIX_ADMIN CASCADE', 'USER MINFLIX_ADMIN');
  DROP_IF_EXISTS('DROP USER MINFLIX_ANALISTA CASCADE', 'USER MINFLIX_ANALISTA');
  DROP_IF_EXISTS('DROP USER MINFLIX_SOPORTE CASCADE', 'USER MINFLIX_SOPORTE');
  DROP_IF_EXISTS('DROP USER MINFLIX_CONTENIDO CASCADE', 'USER MINFLIX_CONTENIDO');
  DROP_IF_EXISTS('DROP ROLE ROL_CONTENIDO', 'ROLE ROL_CONTENIDO');
  DROP_IF_EXISTS('DROP ROLE ROL_SOPORTE', 'ROLE ROL_SOPORTE');
  DROP_IF_EXISTS('DROP ROLE ROL_ANALISTA', 'ROLE ROL_ANALISTA');
  DROP_IF_EXISTS('DROP ROLE ROL_ADMIN', 'ROLE ROL_ADMIN');
  DROP_IF_EXISTS('DROP PROFILE PRF_MINFLIX_OPERACION', 'PROFILE PRF_MINFLIX_OPERACION');
END;
/

PROMPT ========================================================================
PROMPT MinFlix - Verificacion posterior a limpieza
PROMPT ========================================================================

SELECT OBJECT_TYPE, OBJECT_NAME, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'PLANES', 'USUARIOS', 'PERFILES', 'CATEGORIAS', 'CONTENIDOS',
   'GENEROS', 'CONTENIDOS_GENEROS', 'TEMPORADAS', 'EPISODIOS',
   'CONTENIDOS_RELACIONADOS', 'REPRODUCCIONES', 'FAVORITOS',
   'CALIFICACIONES', 'REPORTES', 'REFERIDOS', 'FACTURACIONES',
   'ROLES_USUARIOS',
   'PAGOS', 'DEPARTAMENTOS', 'EMPLEADOS', 'REPRODUCCIONES_BKP',
   'TMP_POPULARIDAD_CATALOGO',
   'VW_CONTENIDO_VISIBLE_POR_PERFIL', 'VW_CONTINUAR_VIENDO',
   'VW_REPORTES_PENDIENTES_SOPORTE', 'VW_FIN_RESUMEN_USUARIO',
   'VW_FIN_FACTURAS_DETALLE', 'VW_FIN_PAGOS_DETALLE',
   'VW_FIN_REFERIDOS_DETALLE', 'VW_ANALITICA_CONSUMO',
   'VW_ANALITICA_FINANZAS', 'VW_ANALITICA_RENDIMIENTO',
   'MV_CALIFICACIONES_PROMEDIO', 'MV_METRICAS_FINANCIERAS',
   'SP_APLICAR_MORA_CUENTAS', 'SP_REGISTRAR_USUARIO', 'SP_CAMBIAR_PLAN',
   'FN_CLASIFICACION_PERMITIDA_PARA_PERFIL', 'FN_CALCULAR_MONTO',
   'FN_CONTENIDO_RECOMENDADO'
 )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;

SELECT 'Tablas MinFlix restantes: ' || COUNT(*) AS RESULTADO
  FROM USER_TABLES
 WHERE TABLE_NAME IN (
   'PLANES', 'USUARIOS', 'PERFILES', 'CATEGORIAS', 'CONTENIDOS',
   'GENEROS', 'CONTENIDOS_GENEROS', 'TEMPORADAS', 'EPISODIOS',
   'CONTENIDOS_RELACIONADOS', 'REPRODUCCIONES', 'FAVORITOS',
   'CALIFICACIONES', 'REPORTES', 'REFERIDOS', 'FACTURACIONES',
   'ROLES_USUARIOS',
   'PAGOS', 'DEPARTAMENTOS', 'EMPLEADOS', 'REPRODUCCIONES_BKP',
   'TMP_POPULARIDAD_CATALOGO'
 );

PROMPT ========================================================================
PROMPT MinFlix - Limpieza total finalizada
PROMPT ========================================================================
