-- ============================================================================
-- MinFlix - Limpieza total del esquema MINFLIX_APP
-- Ejecutar como MINFLIX_APP en XEPDB1
-- ADVERTENCIA: Elimina todas las tablas, vistas, triggers y funciones
-- ============================================================================

-- Triggers
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_LIMITE_PERFILES'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_ACTUALIZAR_FECHA_USUARIO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_PERFILES_LIMITE_PLAN_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TRIGGER TRG_FAVORITOS_REGLAS_BI'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Vistas
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONTINUAR_VIENDO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP VIEW VW_CONTENIDO_VISIBLE_POR_PERFIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Funciones
BEGIN EXECUTE IMMEDIATE 'DROP FUNCTION FN_CLASIFICACION_PERMITIDA_PARA_PERFIL'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Tablas (en orden inverso de dependencias)
BEGIN EXECUTE IMMEDIATE 'DROP TABLE FAVORITOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE REPRODUCCIONES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO_RELACIONADO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO_GENEROS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EPISODIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE TEMPORADAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTENIDO CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CONTENIDOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE GENEROS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CATEGORIAS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERFILES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE USUARIOS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PLANES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Verificacion
SELECT 'Esquema limpio. Tablas restantes: ' || COUNT(*) AS RESULTADO
FROM USER_TABLES;
