-- ============================================================================
-- MinFlix - Bootstrap Oracle Iteracion 1 (Auth + Usuarios + Perfiles)
-- Ejecute este script por secciones.
-- Seccion A: como SYSTEM (crea usuario de aplicacion)
-- Seccion B: como MINFLIX_APP (crea tablas y datos base)
-- ============================================================================

-- =============================================
-- Seccion A - Ejecutar como SYSTEM
-- =============================================
-- Ajuste la contrasena del usuario de aplicacion antes de ejecutar.
-- CREATE USER MINFLIX_APP IDENTIFIED BY "Cambiar_Contrasena_Segura";
-- GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW, CREATE PROCEDURE, CREATE TRIGGER TO MINFLIX_APP;
-- ALTER USER MINFLIX_APP QUOTA UNLIMITED ON USERS;

-- =============================================
-- Seccion B - Ejecutar como MINFLIX_APP
-- =============================================

-- --------------------------------------------------------------------------
-- Tabla PLANES
-- Define el catalogo de suscripciones y su capacidad de perfiles.
-- Columnas clave:
--   ID_PLAN: PK autonumerica.
--   NOMBRE: nombre unico del plan.
--   PRECIO_MENSUAL: valor del cobro por ciclo.
--   LIMITE_PERFILES: cantidad maxima de perfiles permitidos.
-- Restricciones:
--   UK_PLANES_NOMBRE evita duplicados.
--   CK_PLANES_LIMITE_PERFILES limita el rango permitido (1..5).
-- --------------------------------------------------------------------------
CREATE TABLE PLANES (
  -- PK: identificador del plan.
  ID_PLAN NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nombre del plan (BASICO, ESTANDAR, PREMIUM).
  NOMBRE VARCHAR2(40) NOT NULL,
  -- Precio mensual en moneda local.
  PRECIO_MENSUAL NUMBER(10,2) NOT NULL,
  -- Maximo de perfiles permitidos por plan.
  LIMITE_PERFILES NUMBER(2,0) NOT NULL,
  -- Constraint unica por nombre.
  CONSTRAINT UK_PLANES_NOMBRE UNIQUE (NOMBRE),
  -- Constraint de rango permitido (1..5 perfiles).
  CONSTRAINT CK_PLANES_LIMITE_PERFILES CHECK (LIMITE_PERFILES BETWEEN 1 AND 5)
);

-- --------------------------------------------------------------------------
-- Tabla USUARIOS
-- Almacena cuentas principales (titular de la suscripcion).
-- Columnas clave:
--   EMAIL: identificador unico de login.
--   PASSWORD_HASH: hash seguro (bcrypt) gestionado por la API.
--   ROL: controla permisos en la aplicacion.
--   ESTADO_CUENTA: controla acceso a reproduccion y pagos.
--   ID_PLAN: referencia al plan seleccionado.
-- Validaciones:
--   TELEFONO (solo digitos 7-15), CIUDAD con minimo 2 caracteres.
--   ROL y ESTADO_CUENTA restringidos por listas permitidas.
-- --------------------------------------------------------------------------
CREATE TABLE USUARIOS (
  -- PK: identificador del usuario.
  ID_USUARIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nombre completo del titular de la cuenta.
  NOMBRE VARCHAR2(120) NOT NULL,
  -- Email unico de autenticacion.
  EMAIL VARCHAR2(180) NOT NULL,
  -- Telefono de contacto (solo digitos).
  TELEFONO VARCHAR2(30) NOT NULL,
  -- Fecha de nacimiento para validaciones y segmentacion.
  FECHA_NACIMIENTO DATE NOT NULL,
  -- Ciudad de residencia para analitica.
  CIUDAD_RESIDENCIA VARCHAR2(120) NOT NULL,
  -- Hash de contrasena (bcrypt en backend).
  PASSWORD_HASH VARCHAR2(255) NOT NULL,
  -- Rol funcional dentro de la plataforma.
  ROL VARCHAR2(30) DEFAULT 'usuario' NOT NULL,
  -- Estado de la cuenta (controla acceso y reproduccion).
  ESTADO_CUENTA VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
  -- Plan de suscripcion asociado.
  ID_PLAN NUMBER NULL,
  -- Auditoria de creacion/actualizacion.
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Constraint de unicidad por email.
  CONSTRAINT UK_USUARIOS_EMAIL UNIQUE (EMAIL),
  -- Validacion de telefono (7 a 15 digitos).
  CONSTRAINT CK_USUARIOS_TELEFONO CHECK (REGEXP_LIKE(TELEFONO, '^[0-9]{7,15}$')),
  -- Validacion de longitud minima para ciudad.
  CONSTRAINT CK_USUARIOS_CIUDAD CHECK (LENGTH(TRIM(CIUDAD_RESIDENCIA)) >= 2),
  -- Validacion de roles permitidos.
  CONSTRAINT CK_USUARIOS_ROL CHECK (ROL IN ('admin', 'soporte', 'contenido', 'analista', 'usuario')),
  -- Validacion de estados permitidos.
  CONSTRAINT CK_USUARIOS_ESTADO CHECK (ESTADO_CUENTA IN ('ACTIVO', 'SUSPENDIDO', 'INACTIVO')),
  -- FK al catalogo de planes.
  CONSTRAINT FK_USUARIOS_PLAN FOREIGN KEY (ID_PLAN) REFERENCES PLANES(ID_PLAN)
);

-- --------------------------------------------------------------------------
-- Tabla PERFILES
-- Representa perfiles de consumo asociados a una cuenta (usuario).
-- Columnas clave:
--   ID_USUARIO: FK a USUARIOS (ownership del perfil).
--   TIPO_PERFIL: adulto/infantil para control de clasificacion.
-- --------------------------------------------------------------------------
CREATE TABLE PERFILES (
  -- PK: identificador del perfil.
  ID_PERFIL NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al usuario propietario.
  ID_USUARIO NUMBER NOT NULL,
  -- Nombre visible del perfil.
  NOMBRE VARCHAR2(80) NOT NULL,
  -- URL o ruta del avatar (opcional).
  AVATAR VARCHAR2(255) NULL,
  -- Tipo de perfil para control parental.
  TIPO_PERFIL VARCHAR2(20) NOT NULL,
  -- FK a USUARIOS.
  CONSTRAINT FK_PERFILES_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO),
  -- Validacion de tipos permitidos.
  CONSTRAINT CK_PERFILES_TIPO CHECK (TIPO_PERFIL IN ('adulto', 'infantil'))
);

-- Indice de apoyo para consultas de perfiles por cuenta.
CREATE INDEX IDX_PERFILES_USUARIO ON PERFILES (ID_USUARIO);

-- Seed base de planes (valores del enunciado).
-- BASICO: 1 pantalla, 2 perfiles.
INSERT INTO PLANES (NOMBRE, PRECIO_MENSUAL, LIMITE_PERFILES) VALUES ('BASICO', 14900, 2);
-- ESTANDAR: 2 pantallas, 3 perfiles.
INSERT INTO PLANES (NOMBRE, PRECIO_MENSUAL, LIMITE_PERFILES) VALUES ('ESTANDAR', 24900, 3);
-- PREMIUM: 4 pantallas, 5 perfiles.
INSERT INTO PLANES (NOMBRE, PRECIO_MENSUAL, LIMITE_PERFILES) VALUES ('PREMIUM', 34900, 5);

COMMIT;

-- Nota:
-- El usuario admin inicial se crea desde el backend con AUTH_SEED_ADMIN_ENABLED=true,
-- usando hash bcrypt para PASSWORD_HASH.
-- No se crea indice adicional para USUARIOS.EMAIL porque la constraint
-- UK_USUARIOS_EMAIL ya genera un indice unico implicito en Oracle.
