-- ============================================================================
-- MinFlix - Iteracion 2 (Catalogo Base)
-- Ejecutar como MINFLIX_APP despues de 01_bootstrap_oracle_iteracion1.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla CATEGORIAS
-- Clasifica contenidos por grandes grupos (accion, drama, etc.).
-- NOMBRE es unico y se refuerza con indice case-insensitive.
-- --------------------------------------------------------------------------
CREATE TABLE CATEGORIAS (
  -- PK: identificador de la categoria.
  ID_CATEGORIA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nombre de categoria mostrado en UI.
  NOMBRE VARCHAR2(80) NOT NULL,
  -- Descripcion opcional de la categoria.
  DESCRIPCION VARCHAR2(260) NULL,
  -- Constraint de unicidad por nombre (case-sensitive).
  CONSTRAINT UK_CATEGORIAS_NOMBRE UNIQUE (NOMBRE)
);

-- Indice unico adicional para evitar duplicados por diferencias de mayusculas.
CREATE UNIQUE INDEX UK_CATEGORIAS_NOMBRE_CI ON CATEGORIAS (UPPER(NOMBRE));

-- --------------------------------------------------------------------------
-- Tabla CONTENIDOS
-- Almacena peliculas, series, documentales, musica y podcasts.
-- Campos clave:
--   TIPO_CONTENIDO y CLASIFICACION_EDAD validan valores permitidos.
--   ES_EXCLUSIVO indica contenido original (0/1).
--   ID_CATEGORIA vincula la clasificacion editorial.
--   ID_EMPLEADO_PUBLICADOR registra quien publico el contenido (rol admin/contenido).
-- --------------------------------------------------------------------------
CREATE TABLE CONTENIDOS (
  -- PK: identificador del contenido.
  ID_CONTENIDO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Titulo principal del contenido.
  TITULO VARCHAR2(180) NOT NULL,
  -- Tipo de contenido (pelicula, serie, documental, musica, podcast).
  TIPO_CONTENIDO VARCHAR2(20) NOT NULL,
  -- Ano de lanzamiento (opcional).
  ANIO_LANZAMIENTO NUMBER(4,0) NULL,
  -- Duracion en minutos (opcional; episodios se modelan en script 07).
  DURACION_MINUTOS NUMBER(5,0) NULL,
  -- Sinopsis corta para detalle de catalogo.
  SINOPSIS VARCHAR2(1500) NULL,
  -- Clasificacion de edad para control parental.
  CLASIFICACION_EDAD VARCHAR2(10) NOT NULL,
  -- Fecha de adicion al catalogo.
  FECHA_ADICION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Indicador de exclusividad (1 = original MinFlix).
  ES_EXCLUSIVO NUMBER(1,0) DEFAULT 0 NOT NULL,
  -- FK a la categoria principal.
  ID_CATEGORIA NUMBER NOT NULL,
  -- Usuario publicador (rol admin/contenido).
  ID_EMPLEADO_PUBLICADOR NUMBER NULL,
  -- Validaciones de dominio (tipo, clasificacion, rangos).
  CONSTRAINT CK_CONTENIDOS_TIPO CHECK (
    TIPO_CONTENIDO IN ('pelicula', 'serie', 'documental', 'musica', 'podcast')
  ),
  CONSTRAINT CK_CONTENIDOS_CLASIFICACION CHECK (
    CLASIFICACION_EDAD IN ('TP', '+7', '+13', '+16', '+18')
  ),
  CONSTRAINT CK_CONTENIDOS_ANIO CHECK (
    ANIO_LANZAMIENTO IS NULL OR ANIO_LANZAMIENTO BETWEEN 1900 AND 2100
  ),
  CONSTRAINT CK_CONTENIDOS_DURACION CHECK (
    DURACION_MINUTOS IS NULL OR DURACION_MINUTOS BETWEEN 1 AND 10000
  ),
  CONSTRAINT CK_CONTENIDOS_EXCLUSIVO CHECK (ES_EXCLUSIVO IN (0, 1)),
  -- FK a categoria.
  CONSTRAINT FK_CONTENIDOS_CATEGORIA FOREIGN KEY (ID_CATEGORIA)
    REFERENCES CATEGORIAS(ID_CATEGORIA),
  -- FK a usuario publicador (tabla USUARIOS).
  CONSTRAINT FK_CONTENIDOS_PUBLICADOR FOREIGN KEY (ID_EMPLEADO_PUBLICADOR)
    REFERENCES USUARIOS(ID_USUARIO)
);

-- Indices de apoyo para filtros frecuentes en catalogo.
CREATE INDEX IDX_CONTENIDOS_TIPO ON CONTENIDOS (TIPO_CONTENIDO);
CREATE INDEX IDX_CONTENIDOS_CLASIFICACION ON CONTENIDOS (CLASIFICACION_EDAD);
CREATE INDEX IDX_CONTENIDOS_CATEGORIA ON CONTENIDOS (ID_CATEGORIA);

-- Seed base de categorias para navegacion inicial.
-- Categoria: Accion.
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION)
VALUES ('Accion', 'Historias de ritmo alto, riesgo y conflicto continuo.');

-- Categoria: Drama.
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION)
VALUES ('Drama', 'Narrativas emocionales centradas en personajes y decisiones.');

-- Categoria: Documental.
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION)
VALUES ('Documental', 'Contenido factual orientado a exploracion y aprendizaje.');

-- Categoria: Infantil.
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION)
VALUES ('Infantil', 'Contenido apto para audiencias de corta edad.');

-- Categoria: Podcast.
INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION)
VALUES ('Podcast', 'Producciones de audio por episodios o temporadas.');

-- Seed base de contenidos (muestra de cada tipo).
-- El publicador se resuelve con el primer usuario admin o contenido disponible.
-- Contenido tipo pelicula.
INSERT INTO CONTENIDOS (
  TITULO,
  TIPO_CONTENIDO,
  ANIO_LANZAMIENTO,
  DURACION_MINUTOS,
  SINOPSIS,
  CLASIFICACION_EDAD,
  ES_EXCLUSIVO,
  ID_CATEGORIA,
  ID_EMPLEADO_PUBLICADOR
) VALUES (
  'La Ciudad de las Sombras',
  'pelicula',
  2024,
  118,
  'Una detective enfrenta una red criminal en una metropoli futurista.',
  '+13',
  1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE = 'Accion'),
  (
    SELECT MIN(ID_USUARIO)
    FROM USUARIOS
    WHERE ROL IN ('admin', 'contenido')
  )
);

-- Contenido tipo serie.
INSERT INTO CONTENIDOS (
  TITULO,
  TIPO_CONTENIDO,
  ANIO_LANZAMIENTO,
  DURACION_MINUTOS,
  SINOPSIS,
  CLASIFICACION_EDAD,
  ES_EXCLUSIVO,
  ID_CATEGORIA,
  ID_EMPLEADO_PUBLICADOR
) VALUES (
  'Norte Incierto',
  'serie',
  2023,
  45,
  'Una familia reconstruye su vida en una ciudad fronteriza llena de secretos.',
  '+16',
  0,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE = 'Drama'),
  (
    SELECT MIN(ID_USUARIO)
    FROM USUARIOS
    WHERE ROL IN ('admin', 'contenido')
  )
);

-- Contenido tipo documental.
INSERT INTO CONTENIDOS (
  TITULO,
  TIPO_CONTENIDO,
  ANIO_LANZAMIENTO,
  DURACION_MINUTOS,
  SINOPSIS,
  CLASIFICACION_EDAD,
  ES_EXCLUSIVO,
  ID_CATEGORIA,
  ID_EMPLEADO_PUBLICADOR
) VALUES (
  'Origenes del Pacifico',
  'documental',
  2022,
  92,
  'Viaje por ecosistemas marinos y cultura costera del litoral colombiano.',
  'TP',
  1,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE = 'Documental'),
  (
    SELECT MIN(ID_USUARIO)
    FROM USUARIOS
    WHERE ROL IN ('admin', 'contenido')
  )
);

-- Contenido tipo pelicula infantil.
INSERT INTO CONTENIDOS (
  TITULO,
  TIPO_CONTENIDO,
  ANIO_LANZAMIENTO,
  DURACION_MINUTOS,
  SINOPSIS,
  CLASIFICACION_EDAD,
  ES_EXCLUSIVO,
  ID_CATEGORIA,
  ID_EMPLEADO_PUBLICADOR
) VALUES (
  'Aventuras en Neblina',
  'pelicula',
  2021,
  88,
  'Grupo de amigos descubre un mapa antiguo y protege su pueblo.',
  '+7',
  0,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE = 'Infantil'),
  (
    SELECT MIN(ID_USUARIO)
    FROM USUARIOS
    WHERE ROL IN ('admin', 'contenido')
  )
);

-- Contenido tipo podcast.
INSERT INTO CONTENIDOS (
  TITULO,
  TIPO_CONTENIDO,
  ANIO_LANZAMIENTO,
  DURACION_MINUTOS,
  SINOPSIS,
  CLASIFICACION_EDAD,
  ES_EXCLUSIVO,
  ID_CATEGORIA,
  ID_EMPLEADO_PUBLICADOR
) VALUES (
  'Codigo en Conversacion',
  'podcast',
  2025,
  60,
  'Conversaciones semanales sobre tecnologia, producto y arquitectura.',
  'TP',
  0,
  (SELECT ID_CATEGORIA FROM CATEGORIAS WHERE NOMBRE = 'Podcast'),
  (
    SELECT MIN(ID_USUARIO)
    FROM USUARIOS
    WHERE ROL IN ('admin', 'contenido')
  )
);

COMMIT;
