-- ============================================================================
-- MinFlix - Iteracion 2 (Reproducciones y Continuar Viendo)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql, 02_catalogo_base_iteracion2.sql,
--           03_reglas_perfiles_iteracion1.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla REPRODUCCIONES
-- Registra sesiones de consumo por perfil y contenido.
-- Columnas clave:
--   PROGRESO_SEGUNDOS / DURACION_TOTAL_SEGUNDOS: calculan avance.
--   PORCENTAJE_AVANCE: derivado, se recalcula en trigger.
--   ULTIMO_DISPOSITIVO: telefono, tv, computador, etc.
--   ESTADO_REPRODUCCION: EN_PROGRESO, PAUSADO, FINALIZADO.
--   FECHA_INICIO / FECHA_ULTIMO_EVENTO / FECHA_FIN: timeline de consumo.
-- --------------------------------------------------------------------------
CREATE TABLE REPRODUCCIONES (
  -- PK: identificador de la reproduccion.
  ID_REPRODUCCION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al perfil que reproduce.
  ID_PERFIL NUMBER NOT NULL,
  -- FK al contenido reproducido.
  ID_CONTENIDO NUMBER NOT NULL,
  -- Progreso actual en segundos.
  PROGRESO_SEGUNDOS NUMBER(10,0) DEFAULT 0 NOT NULL,
  -- Duracion total del contenido (segundos).
  DURACION_TOTAL_SEGUNDOS NUMBER(10,0) NULL,
  -- Porcentaje calculado por trigger.
  PORCENTAJE_AVANCE NUMBER(5,2) DEFAULT 0 NOT NULL,
  -- Ultimo dispositivo reportado.
  ULTIMO_DISPOSITIVO VARCHAR2(80) NULL,
  -- Estado actual de la reproduccion.
  ESTADO_REPRODUCCION VARCHAR2(20) DEFAULT 'EN_PROGRESO' NOT NULL,
  -- Inicio de la sesion.
  FECHA_INICIO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Ultimo evento recibido (play/pause/stop).
  FECHA_ULTIMO_EVENTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Fecha de fin cuando finaliza.
  FECHA_FIN TIMESTAMP NULL,
  -- Checks de valores y rangos.
  CONSTRAINT CK_REPRODUCCIONES_PROGRESO CHECK (PROGRESO_SEGUNDOS >= 0),
  CONSTRAINT CK_REPRODUCCIONES_DURACION CHECK (
    DURACION_TOTAL_SEGUNDOS IS NULL OR DURACION_TOTAL_SEGUNDOS > 0
  ),
  CONSTRAINT CK_REPRODUCCIONES_PORCENTAJE CHECK (
    PORCENTAJE_AVANCE BETWEEN 0 AND 100
  ),
  CONSTRAINT CK_REPRODUCCIONES_ESTADO CHECK (
    ESTADO_REPRODUCCION IN ('EN_PROGRESO', 'PAUSADO', 'FINALIZADO')
  ),
  CONSTRAINT FK_REPRODUCCIONES_PERFIL FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_REPRODUCCIONES_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

-- Indices de apoyo para historiales y continuidad de reproduccion.
-- Perfil + evento: ultima reproduccion por perfil.
CREATE INDEX IDX_REPRODUCCIONES_PERFIL_EVENTO
  ON REPRODUCCIONES (ID_PERFIL, FECHA_ULTIMO_EVENTO DESC);

-- Contenido + evento: ranking y tendencia por contenido.
CREATE INDEX IDX_REPRODUCCIONES_CONTENIDO
  ON REPRODUCCIONES (ID_CONTENIDO, FECHA_ULTIMO_EVENTO DESC);

-- Estado de reproduccion: filtros por EN_PROGRESO/PAUSADO/FINALIZADO.
CREATE INDEX IDX_REPRODUCCIONES_ESTADO
  ON REPRODUCCIONES (ESTADO_REPRODUCCION);

-- --------------------------------------------------------------------------
-- Trigger de reglas de negocio en reproduccion.
-- Valida:
--   - estado activo de la cuenta,
--   - restriccion de clasificacion por perfil infantil,
--   - progreso <= duracion,
--   - calculo automatico de porcentaje,
--   - timestamp del ultimo evento y fecha_fin al finalizar.
-- Errores:
--   -20021..-20024
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU
BEFORE INSERT OR UPDATE ON REPRODUCCIONES
FOR EACH ROW
DECLARE
  -- Estado de cuenta del usuario titular (ACTIVO, SUSPENDIDO, INACTIVO)
  V_ESTADO_CUENTA USUARIOS.ESTADO_CUENTA%TYPE;
  -- Tipo de perfil que reproduce (adulto o infantil)
  V_TIPO_PERFIL PERFILES.TIPO_PERFIL%TYPE;
  -- Clasificacion de edad del contenido (TP, +7, +13, +16, +18)
  V_CLASIFICACION CONTENIDOS.CLASIFICACION_EDAD%TYPE;
BEGIN
  -- Paso 1: cargar datos del perfil, usuario y contenido para validaciones.
  -- JOIN a USUARIOS para obtener estado de cuenta; JOIN a CONTENIDOS para clasificacion.
  SELECT U.ESTADO_CUENTA, P.TIPO_PERFIL, C.CLASIFICACION_EDAD
    INTO V_ESTADO_CUENTA, V_TIPO_PERFIL, V_CLASIFICACION
    FROM PERFILES P
    INNER JOIN USUARIOS U ON U.ID_USUARIO = P.ID_USUARIO
    INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = :NEW.ID_CONTENIDO
   WHERE P.ID_PERFIL = :NEW.ID_PERFIL;

  -- Regla 1: la cuenta del usuario debe estar activa para poder reproducir contenido.
  -- Si la cuenta esta suspendida o inactiva, se rechaza la reproduccion.
  IF V_ESTADO_CUENTA <> 'ACTIVO' THEN
    RAISE_APPLICATION_ERROR(
      -20021,
      'La cuenta debe estar activa para registrar reproducciones'
    );
  END IF;

  -- Regla 2: perfil infantil no puede reproducir contenido clasificado +16 o +18.
  -- Se delega a la funcion FN_CLASIFICACION_PERMITIDA_PARA_PERFIL para centralizar la logica.
  IF FN_CLASIFICACION_PERMITIDA_PARA_PERFIL(V_TIPO_PERFIL, V_CLASIFICACION) = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20022,
      'El perfil seleccionado no puede reproducir este contenido por clasificacion'
    );
  END IF;

  -- Regla 3: el progreso en segundos no puede superar la duracion total del contenido.
  -- Solo se valida cuando la duracion total esta definida (no NULL).
  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL
     AND :NEW.PROGRESO_SEGUNDOS > :NEW.DURACION_TOTAL_SEGUNDOS THEN
    RAISE_APPLICATION_ERROR(
      -20023,
      'El progreso no puede superar la duracion total del contenido'
    );
  END IF;

  -- Paso 2: calcular el porcentaje de avance automaticamente.
  -- Formula: (progreso / duracion_total) * 100, redondeado a 2 decimales.
  -- LEAST(100, ...) garantiza que nunca exceda 100%.
  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL AND :NEW.DURACION_TOTAL_SEGUNDOS > 0 THEN
    :NEW.PORCENTAJE_AVANCE := ROUND(
      LEAST(100, (:NEW.PROGRESO_SEGUNDOS / :NEW.DURACION_TOTAL_SEGUNDOS) * 100),
      2
    );
  ELSE
    -- Si no hay duracion total conocida, el avance se define como 0%
    :NEW.PORCENTAJE_AVANCE := 0;
  END IF;

  -- Paso 3: actualizar timestamp del ultimo evento recibido (play/pause/stop).
  :NEW.FECHA_ULTIMO_EVENTO := CURRENT_TIMESTAMP;

  -- Paso 4: si la reproduccion se marca como FINALIZADO, registrar fecha_fin.
  -- Solo se asigna si no estaba previamente definida (evita sobrescribir).
  IF :NEW.ESTADO_REPRODUCCION = 'FINALIZADO' AND :NEW.FECHA_FIN IS NULL THEN
    :NEW.FECHA_FIN := CURRENT_TIMESTAMP;
  END IF;
EXCEPTION
  -- Si el perfil o contenido no existen en la base de datos
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20024,
      'No existe el perfil o contenido asociado para registrar reproduccion'
    );
END;
/

-- --------------------------------------------------------------------------
-- Vista VW_CONTINUAR_VIENDO
-- Devuelve el ultimo evento por perfil y contenido no finalizado (<95%).
-- Usa ROW_NUMBER para quedarnos con el evento mas reciente.
-- --------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_CONTINUAR_VIENDO AS
SELECT *
FROM (
  SELECT
    R.ID_REPRODUCCION,
    R.ID_PERFIL,
    R.ID_CONTENIDO,
    C.TITULO,
    C.CLASIFICACION_EDAD,
    C.TIPO_CONTENIDO,
    R.PROGRESO_SEGUNDOS,
    R.DURACION_TOTAL_SEGUNDOS,
    R.PORCENTAJE_AVANCE,
    R.ULTIMO_DISPOSITIVO,
    R.ESTADO_REPRODUCCION,
    R.FECHA_ULTIMO_EVENTO,
    ROW_NUMBER() OVER (
      PARTITION BY R.ID_PERFIL, R.ID_CONTENIDO
      ORDER BY R.FECHA_ULTIMO_EVENTO DESC
    ) AS RN
  FROM REPRODUCCIONES R
  INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
  WHERE R.ESTADO_REPRODUCCION IN ('EN_PROGRESO', 'PAUSADO')
    AND R.PORCENTAJE_AVANCE < 95
)
WHERE RN = 1;

COMMIT;
