-- ============================================================================
-- MinFlix - Iteracion 3 (Comunidad: Favoritos por Perfil)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql, 02_catalogo_base_iteracion2.sql,
--           03_reglas_perfiles_iteracion1.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla FAVORITOS
-- Guarda la lista personal de contenidos favoritos por perfil.
-- La combinacion (ID_PERFIL, ID_CONTENIDO) es unica para evitar duplicados.
-- --------------------------------------------------------------------------
CREATE TABLE FAVORITOS (
  -- PK: identificador del favorito.
  ID_FAVORITO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al perfil.
  ID_PERFIL NUMBER NOT NULL,
  -- FK al contenido.
  ID_CONTENIDO NUMBER NOT NULL,
  -- Fecha de adicion a favoritos.
  FECHA_ADICION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Unicidad por perfil + contenido.
  CONSTRAINT UK_FAVORITOS_PERFIL_CONTENIDO UNIQUE (ID_PERFIL, ID_CONTENIDO),
  -- FK a PERFILES.
  CONSTRAINT FK_FAVORITOS_PERFIL FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  -- FK a CONTENIDOS.
  CONSTRAINT FK_FAVORITOS_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

-- Indice de apoyo para listar favoritos recientes por perfil.
CREATE INDEX IDX_FAVORITOS_PERFIL_FECHA
  ON FAVORITOS (ID_PERFIL, FECHA_ADICION DESC);

-- --------------------------------------------------------------------------
-- Trigger TRG_FAVORITOS_REGLAS_BI
-- Valida que perfiles infantiles no agreguen contenido no permitido.
-- Errores:
--   -20031: contenido no permitido por clasificacion.
--   -20032: perfil o contenido inexistente.
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FAVORITOS_REGLAS_BI
BEFORE INSERT ON FAVORITOS
FOR EACH ROW
DECLARE
  -- Tipo de perfil que intenta agregar a favoritos (adulto o infantil)
  V_TIPO_PERFIL PERFILES.TIPO_PERFIL%TYPE;
  -- Clasificacion de edad del contenido a agregar (TP, +7, +13, +16, +18)
  V_CLASIFICACION CONTENIDOS.CLASIFICACION_EDAD%TYPE;
BEGIN
  -- Paso 1: consultar tipo de perfil y clasificacion del contenido.
  -- JOIN a CONTENIDOS para traer la clasificacion del contenido solicitado.
  SELECT P.TIPO_PERFIL, C.CLASIFICACION_EDAD
    INTO V_TIPO_PERFIL, V_CLASIFICACION
    FROM PERFILES P
    INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = :NEW.ID_CONTENIDO
   WHERE P.ID_PERFIL = :NEW.ID_PERFIL;

  -- Regla de negocio: perfil infantil no puede agregar a favoritos contenido +16 o +18.
  -- Se delega a la funcion FN_CLASIFICACION_PERMITIDA_PARA_PERFIL para centralizar logica.
  IF FN_CLASIFICACION_PERMITIDA_PARA_PERFIL(V_TIPO_PERFIL, V_CLASIFICACION) = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20031,
      'El perfil seleccionado no puede agregar este contenido a favoritos'
    );
  END IF;
EXCEPTION
  -- Si el perfil o contenido no existen en la base de datos
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20032,
      'No existe el perfil o contenido asociado para registrar favorito'
    );
END;
/

COMMIT;
