-- ============================================================================
-- MinFlix - Iteracion 3 (Comunidad: Calificaciones por Perfil)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql, 02_catalogo_base_iteracion2.sql,
--           03_reglas_perfiles_iteracion1.sql, 04_reproducciones_iteracion2.sql,
--           05_comunidad_favoritos_iteracion3.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla CALIFICACIONES
-- Registra puntaje (1-5) y resena opcional por perfil y contenido.
-- Un perfil solo puede calificar una vez un contenido (constraint unica).
-- --------------------------------------------------------------------------
CREATE TABLE CALIFICACIONES (
  -- PK: identificador de la calificacion.
  ID_CALIFICACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al perfil que califica.
  ID_PERFIL NUMBER NOT NULL,
  -- FK al contenido calificado.
  ID_CONTENIDO NUMBER NOT NULL,
  -- Puntaje en escala 1..5.
  PUNTAJE NUMBER(1,0) NOT NULL,
  -- Resena opcional del usuario.
  RESENA VARCHAR2(1000) NULL,
  -- Fecha de registro o actualizacion.
  FECHA_CALIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Unicidad por perfil + contenido.
  CONSTRAINT UK_CALIFICACIONES_PERFIL_CONTENIDO UNIQUE (ID_PERFIL, ID_CONTENIDO),
  -- Validacion de rango de puntaje.
  CONSTRAINT CK_CALIFICACIONES_PUNTAJE CHECK (PUNTAJE BETWEEN 1 AND 5),
  -- FK a PERFILES.
  CONSTRAINT FK_CALIFICACIONES_PERFIL FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  -- FK a CONTENIDOS.
  CONSTRAINT FK_CALIFICACIONES_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

-- Indices de apoyo para listar calificaciones por perfil y calcular rankings.
CREATE INDEX IDX_CALIFICACIONES_PERFIL_FECHA
  ON CALIFICACIONES (ID_PERFIL, FECHA_CALIFICACION DESC);

CREATE INDEX IDX_CALIFICACIONES_CONTENIDO_PUNTAJE
  ON CALIFICACIONES (ID_CONTENIDO, PUNTAJE DESC);

-- --------------------------------------------------------------------------
-- Trigger TRG_CALIFICACIONES_REGLAS_BIU
-- Regla 50%: se exige avance >= 50% antes de permitir calificar.
-- Ademas verifica existencia de perfil y contenido.
-- Errores:
--   -20041: no cumple porcentaje minimo.
--   -20042: perfil o contenido inexistente.
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CALIFICACIONES_REGLAS_BIU
BEFORE INSERT OR UPDATE ON CALIFICACIONES
FOR EACH ROW
DECLARE
  V_PERFIL_EXISTE NUMBER;
  V_CONTENIDO_EXISTE NUMBER;
  V_MAX_AVANCE NUMBER(5,2);
BEGIN
  -- Verificar que el perfil exista.
  SELECT COUNT(*)
    INTO V_PERFIL_EXISTE
    FROM PERFILES
   WHERE ID_PERFIL = :NEW.ID_PERFIL;

  -- Verificar que el contenido exista.
  SELECT COUNT(*)
    INTO V_CONTENIDO_EXISTE
    FROM CONTENIDOS
   WHERE ID_CONTENIDO = :NEW.ID_CONTENIDO;

  IF V_PERFIL_EXISTE = 0 OR V_CONTENIDO_EXISTE = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20042,
      'No existe perfil o contenido asociado para registrar calificacion'
    );
  END IF;

  -- Consultar el maximo avance logrado por el perfil en ese contenido.
  SELECT NVL(MAX(R.PORCENTAJE_AVANCE), 0)
    INTO V_MAX_AVANCE
    FROM REPRODUCCIONES R
   WHERE R.ID_PERFIL = :NEW.ID_PERFIL
     AND R.ID_CONTENIDO = :NEW.ID_CONTENIDO;

  -- Regla de negocio: exigir minimo 50% de reproduccion.
  IF V_MAX_AVANCE < 50 THEN
    RAISE_APPLICATION_ERROR(
      -20041,
      'Debes superar el 50% de reproduccion para calificar este contenido'
    );
  END IF;

  -- Normalizar fecha de calificacion en cada insercion/actualizacion.
  :NEW.FECHA_CALIFICACION := CURRENT_TIMESTAMP;
END;
/

COMMIT;
