-- ============================================================================
-- MinFlix - Iteracion 3 (Comunidad: Calificaciones y Reportes)
-- Ejecutar como MINFLIX_APP en XEPDB1
-- Requiere: 01 al 05 ejecutados previamente
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Tabla CALIFICACIONES
-- Un perfil puede calificar un contenido solo si vio mas del 50%
-- ----------------------------------------------------------------------------
CREATE TABLE CALIFICACIONES (
  ID_CALIFICACION   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_PERFIL         NUMBER        NOT NULL,
  ID_CONTENIDO      NUMBER        NOT NULL,
  PUNTUACION        NUMBER(2,0)   NOT NULL,
  RESENA            VARCHAR2(1000) NULL,
  FECHA_CALIFICACION TIMESTAMP    DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT UK_CALIFICACIONES_PERFIL_CONTENIDO UNIQUE (ID_PERFIL, ID_CONTENIDO),
  CONSTRAINT CK_CALIFICACIONES_PUNTUACION CHECK (PUNTUACION BETWEEN 1 AND 5),
  CONSTRAINT FK_CALIFICACIONES_PERFIL FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_CALIFICACIONES_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

CREATE INDEX IDX_CALIFICACIONES_CONTENIDO ON CALIFICACIONES (ID_CONTENIDO);
CREATE INDEX IDX_CALIFICACIONES_PERFIL    ON CALIFICACIONES (ID_PERFIL);

-- ----------------------------------------------------------------------------
-- Trigger: valida que el perfil haya consumido al menos 50% antes de calificar
-- ----------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CALIFICACIONES_RETENSION_BI
BEFORE INSERT ON CALIFICACIONES
FOR EACH ROW
DECLARE
  V_MAX_PORCENTAJE NUMBER;
BEGIN
  SELECT MAX(PORCENTAJE_AVANCE)
    INTO V_MAX_PORCENTAJE
    FROM REPRODUCCIONES
   WHERE ID_PERFIL    = :NEW.ID_PERFIL
     AND ID_CONTENIDO = :NEW.ID_CONTENIDO;

  IF V_MAX_PORCENTAJE IS NULL OR V_MAX_PORCENTAJE < 50 THEN
    RAISE_APPLICATION_ERROR(
      -20041,
      'Debes haber visto al menos el 50% del contenido para poder calificarlo'
    );
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20042,
      'No se encontro historial de reproduccion para este perfil y contenido'
    );
END;
/

-- ----------------------------------------------------------------------------
-- Tabla REPORTES
-- Usuarios reportan contenido inapropiado, soporte lo gestiona
-- ----------------------------------------------------------------------------
CREATE TABLE REPORTES (
  ID_REPORTE    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_PERFIL     NUMBER        NOT NULL,
  ID_CONTENIDO  NUMBER        NOT NULL,
  MOTIVO        VARCHAR2(100) NOT NULL,
  DESCRIPCION   VARCHAR2(1000) NULL,
  ESTADO        VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
  FECHA_REPORTE TIMESTAMP     DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FECHA_RESOLUCION TIMESTAMP  NULL,
  CONSTRAINT CK_REPORTES_ESTADO CHECK (
    ESTADO IN ('PENDIENTE', 'EN_REVISION', 'RESUELTO', 'DESCARTADO')
  ),
  CONSTRAINT CK_REPORTES_MOTIVO CHECK (
    MOTIVO IN ('CONTENIDO_INAPROPIADO', 'DERECHOS_AUTOR', 'INFORMACION_FALSA', 'OTRO')
  ),
  CONSTRAINT FK_REPORTES_PERFIL FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_REPORTES_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

CREATE INDEX IDX_REPORTES_ESTADO    ON REPORTES (ESTADO);
CREATE INDEX IDX_REPORTES_CONTENIDO ON REPORTES (ID_CONTENIDO);

-- ----------------------------------------------------------------------------
-- Verificacion final
-- ----------------------------------------------------------------------------
SELECT 'CALIFICACIONES' AS TABLA, COUNT(*) AS TOTAL FROM CALIFICACIONES UNION ALL
SELECT 'REPORTES',                COUNT(*)           FROM REPORTES;
