-- ============================================================================
-- MinFlix - Iteracion 4 (Catalogo Extendido)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql y 02_catalogo_base_iteracion2.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla GENEROS
-- Clasificacion M:N para contenidos (accion, drama, etc.).
-- El indice case-insensitive evita duplicados por mayusculas.
-- --------------------------------------------------------------------------
CREATE TABLE GENEROS (
  -- PK: identificador del genero.
  ID_GENERO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nombre visible del genero.
  NOMBRE VARCHAR2(80) NOT NULL,
  -- Descripcion opcional.
  DESCRIPCION VARCHAR2(260) NULL,
  -- Unicidad por nombre.
  CONSTRAINT UK_GENEROS_NOMBRE UNIQUE (NOMBRE)
);

-- Indice unico adicional para controlar mayusculas/minusculas.
CREATE UNIQUE INDEX UK_GENEROS_NOMBRE_CI ON GENEROS (UPPER(NOMBRE));

-- --------------------------------------------------------------------------
-- Tabla CONTENIDOS_GENEROS
-- Relacion M:N entre contenidos y generos.
-- La PK compuesta evita relaciones duplicadas.
-- --------------------------------------------------------------------------
CREATE TABLE CONTENIDOS_GENEROS (
  -- FK al contenido.
  ID_CONTENIDO NUMBER NOT NULL,
  -- FK al genero.
  ID_GENERO NUMBER NOT NULL,
  -- Fecha de asignacion de la relacion.
  FECHA_ASIGNACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- PK compuesta para evitar duplicados.
  CONSTRAINT PK_CONTENIDOS_GENEROS PRIMARY KEY (ID_CONTENIDO, ID_GENERO),
  -- FK a CONTENIDOS.
  CONSTRAINT FK_CONTENIDOS_GENEROS_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO),
  -- FK a GENEROS.
  CONSTRAINT FK_CONTENIDOS_GENEROS_GENERO FOREIGN KEY (ID_GENERO)
    REFERENCES GENEROS(ID_GENERO)
);

-- Indice para consultas de genero y orden por fecha de asignacion.
CREATE INDEX IDX_CONTENIDOS_GENEROS_GENERO
  ON CONTENIDOS_GENEROS (ID_GENERO, FECHA_ASIGNACION DESC);

-- --------------------------------------------------------------------------
-- Tabla TEMPORADAS
-- Solo aplica para contenidos tipo serie/podcast (validado por trigger).
-- El numero de temporada es unico por contenido.
-- --------------------------------------------------------------------------
CREATE TABLE TEMPORADAS (
  -- PK: identificador de temporada.
  ID_TEMPORADA NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al contenido (serie/podcast).
  ID_CONTENIDO NUMBER NOT NULL,
  -- Numero de temporada dentro del contenido.
  NUMERO_TEMPORADA NUMBER(3,0) NOT NULL,
  -- Titulo opcional de temporada.
  TITULO VARCHAR2(180) NULL,
  -- Descripcion opcional.
  DESCRIPCION VARCHAR2(1500) NULL,
  -- Fecha de estreno (opcional).
  FECHA_ESTRENO DATE NULL,
  -- Unicidad por contenido + numero.
  CONSTRAINT UK_TEMPORADAS_CONTENIDO_NUMERO UNIQUE (
    ID_CONTENIDO,
    NUMERO_TEMPORADA
  ),
  -- Validacion de numeracion.
  CONSTRAINT CK_TEMPORADAS_NUMERO CHECK (NUMERO_TEMPORADA >= 1),
  -- FK a CONTENIDOS.
  CONSTRAINT FK_TEMPORADAS_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

-- Trigger: evita temporadas en contenidos que no sean series/podcasts.
-- Errores:
--   -20051: tipo de contenido no valido para temporadas.
--   -20052: contenido inexistente.
CREATE OR REPLACE TRIGGER TRG_TEMPORADAS_TIPO_CONTENIDO_BIU
BEFORE INSERT OR UPDATE ON TEMPORADAS
FOR EACH ROW
DECLARE
  -- Tipo del contenido padre para validar si acepta temporadas
  V_TIPO_CONTENIDO CONTENIDOS.TIPO_CONTENIDO%TYPE;
BEGIN
  -- Paso 1: obtener el tipo del contenido al que se asocia la temporada.
  SELECT C.TIPO_CONTENIDO
    INTO V_TIPO_CONTENIDO
    FROM CONTENIDOS C
   WHERE C.ID_CONTENIDO = :NEW.ID_CONTENIDO;

  -- Regla: solo contenidos tipo 'serie' o 'podcast' pueden tener temporadas.
  -- Peliculas, documentales y musica no admiten temporadas.
  IF V_TIPO_CONTENIDO NOT IN ('serie', 'podcast') THEN
    RAISE_APPLICATION_ERROR(
      -20051,
      'Solo contenidos tipo serie o podcast pueden tener temporadas'
    );
  END IF;
EXCEPTION
  -- Si el contenido padre no existe en la tabla CONTENIDOS
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20052,
      'No existe el contenido asociado para registrar temporada'
    );
END;
/

-- --------------------------------------------------------------------------
-- Tabla EPISODIOS
-- Episodios ligados a una temporada. El numero es unico por temporada.
-- --------------------------------------------------------------------------
CREATE TABLE EPISODIOS (
  -- PK: identificador del episodio.
  ID_EPISODIO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK a la temporada.
  ID_TEMPORADA NUMBER NOT NULL,
  -- Numero de episodio dentro de la temporada.
  NUMERO_EPISODIO NUMBER(4,0) NOT NULL,
  -- Titulo del episodio.
  TITULO VARCHAR2(180) NOT NULL,
  -- Duracion en minutos.
  DURACION_MINUTOS NUMBER(5,0) NULL,
  -- Sinopsis opcional.
  SINOPSIS VARCHAR2(1500) NULL,
  -- Fecha de estreno (opcional).
  FECHA_ESTRENO DATE NULL,
  -- Fecha de adicion al catalogo.
  FECHA_ADICION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Unicidad por temporada + numero.
  CONSTRAINT UK_EPISODIOS_TEMPORADA_NUMERO UNIQUE (
    ID_TEMPORADA,
    NUMERO_EPISODIO
  ),
  -- Validacion de numeracion.
  CONSTRAINT CK_EPISODIOS_NUMERO CHECK (NUMERO_EPISODIO >= 1),
  -- Validacion de duracion.
  CONSTRAINT CK_EPISODIOS_DURACION CHECK (
    DURACION_MINUTOS IS NULL OR DURACION_MINUTOS BETWEEN 1 AND 10000
  ),
  -- FK a TEMPORADAS.
  CONSTRAINT FK_EPISODIOS_TEMPORADA FOREIGN KEY (ID_TEMPORADA)
    REFERENCES TEMPORADAS(ID_TEMPORADA)
);

-- --------------------------------------------------------------------------
-- Tabla CONTENIDOS_RELACIONADOS
-- Vincula contenidos entre si con tipo de relacion (secuela, precuela, etc.).
-- Evita relaciones reflexivas y duplicadas por tipo.
-- --------------------------------------------------------------------------
CREATE TABLE CONTENIDOS_RELACIONADOS (
  -- PK: identificador de la relacion.
  ID_RELACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al contenido origen.
  ID_CONTENIDO_ORIGEN NUMBER NOT NULL,
  -- FK al contenido relacionado (destino).
  ID_CONTENIDO_RELACIONADO NUMBER NOT NULL,
  -- Tipo de relacion editorial (secuela, precuela, etc.).
  TIPO_RELACION VARCHAR2(30) NOT NULL,
  -- Descripcion opcional de la relacion.
  DESCRIPCION VARCHAR2(260) NULL,
  -- Fecha de creacion del vinculo.
  FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Unicidad por origen + destino + tipo.
  CONSTRAINT UK_CONT_REL_ORIGEN_DESTINO_TIPO UNIQUE (
    ID_CONTENIDO_ORIGEN,
    ID_CONTENIDO_RELACIONADO,
    TIPO_RELACION
  ),
  -- Bloquea relacion reflexiva (un contenido consigo mismo).
  CONSTRAINT CK_CONT_REL_NO_REFLEXIVA CHECK (
    ID_CONTENIDO_ORIGEN <> ID_CONTENIDO_RELACIONADO
  ),
  -- Validacion de tipos permitidos.
  CONSTRAINT CK_CONT_REL_TIPO CHECK (
    TIPO_RELACION IN (
      'SECUELA',
      'PRECUELA',
      'REMAKE',
      'SPIN_OFF',
      'VERSION_EXTENDIDA',
      'RELACIONADO'
    )
  ),
  -- FK al contenido origen.
  CONSTRAINT FK_CONT_REL_CONTENIDO_ORIGEN FOREIGN KEY (ID_CONTENIDO_ORIGEN)
    REFERENCES CONTENIDOS(ID_CONTENIDO),
  -- FK al contenido relacionado.
  CONSTRAINT FK_CONT_REL_CONTENIDO_DESTINO FOREIGN KEY (ID_CONTENIDO_RELACIONADO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
);

-- Indice para buscar relaciones desde el contenido destino y tipo.
CREATE INDEX IDX_CONT_REL_DESTINO_TIPO
  ON CONTENIDOS_RELACIONADOS (ID_CONTENIDO_RELACIONADO, TIPO_RELACION);

-- Trigger: bloquea relaciones inversas duplicadas del mismo tipo.
-- Ejemplo: si A -> B (SECUELA) ya existe, evita B -> A (SECUELA).
CREATE OR REPLACE TRIGGER TRG_CONTENIDOS_RELACIONADOS_BI
BEFORE INSERT ON CONTENIDOS_RELACIONADOS
FOR EACH ROW
DECLARE
  -- Contador para verificar si existe relacion inversa del mismo tipo
  V_RELACION_INVERSA NUMBER;
BEGIN
  -- Paso 1: verificar si ya existe una relacion inversa del mismo tipo.
  -- Ejemplo: si A -> B (SECUELA) ya existe, evita que se cree B -> A (SECUELA).
  SELECT COUNT(*)
    INTO V_RELACION_INVERSA
    FROM CONTENIDOS_RELACIONADOS CR
   WHERE CR.ID_CONTENIDO_ORIGEN = :NEW.ID_CONTENIDO_RELACIONADO
     AND CR.ID_CONTENIDO_RELACIONADO = :NEW.ID_CONTENIDO_ORIGEN
     AND CR.TIPO_RELACION = :NEW.TIPO_RELACION;

  -- Regla: bloquear relaciones inversas duplicadas del mismo tipo.
  IF V_RELACION_INVERSA > 0 THEN
    RAISE_APPLICATION_ERROR(
      -20053,
      'Ya existe una relacion inversa del mismo tipo entre estos contenidos'
    );
  END IF;
END;
/

COMMIT;
