-- ============================================================================
-- MinFlix - Iteracion 4 (Comunidad: Reportes y Moderacion)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql, 02_catalogo_base_iteracion2.sql,
--           03_reglas_perfiles_iteracion1.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla REPORTES
-- Gestiona reportes de contenido con ciclo de vida y asignacion de moderador.
-- Campos clave:
--   ESTADO_REPORTE: ABIERTO -> EN_REVISION -> RESUELTO/DESCARTADO.
--   ID_USUARIO_MODERADOR: usuario soporte/admin que resuelve.
--   FECHA_ACTUALIZACION/FECHA_RESOLUCION: trazabilidad del ciclo.
-- --------------------------------------------------------------------------
CREATE TABLE REPORTES (
  -- PK: identificador del reporte.
  ID_REPORTE NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al perfil que reporta.
  ID_PERFIL_REPORTADOR NUMBER NOT NULL,
  -- FK al contenido reportado.
  ID_CONTENIDO NUMBER NOT NULL,
  -- Motivo corto (taxonomia de reporte).
  MOTIVO VARCHAR2(120) NOT NULL,
  -- Detalle opcional del reporte.
  DETALLE VARCHAR2(1000) NULL,
  -- Estado del reporte en su ciclo de vida.
  ESTADO_REPORTE VARCHAR2(20) DEFAULT 'ABIERTO' NOT NULL,
  -- FK al usuario moderador (soporte/admin).
  ID_USUARIO_MODERADOR NUMBER NULL,
  -- Resultado o resolucion del caso.
  RESOLUCION VARCHAR2(1000) NULL,
  -- Fecha de creacion del reporte.
  FECHA_REPORTE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Fecha de ultima actualizacion (trigger).
  FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Fecha de cierre (si aplica).
  FECHA_RESOLUCION TIMESTAMP NULL,
  -- Validacion de estados permitidos.
  CONSTRAINT CK_REPORTES_ESTADO CHECK (
    ESTADO_REPORTE IN ('ABIERTO', 'EN_REVISION', 'RESUELTO', 'DESCARTADO')
  ),
  -- FK a PERFILES.
  CONSTRAINT FK_REPORTES_PERFIL FOREIGN KEY (ID_PERFIL_REPORTADOR)
    REFERENCES PERFILES(ID_PERFIL),
  -- FK a CONTENIDOS.
  CONSTRAINT FK_REPORTES_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO),
  -- FK a USUARIOS (moderador).
  CONSTRAINT FK_REPORTES_MODERADOR FOREIGN KEY (ID_USUARIO_MODERADOR)
    REFERENCES USUARIOS(ID_USUARIO)
);

-- Indices para bandejas de moderacion y consultas por perfil/contenido.
CREATE INDEX IDX_REPORTES_ESTADO_FECHA
  ON REPORTES (ESTADO_REPORTE, FECHA_ACTUALIZACION DESC);

CREATE INDEX IDX_REPORTES_CONTENIDO_FECHA
  ON REPORTES (ID_CONTENIDO, FECHA_REPORTE DESC);

CREATE INDEX IDX_REPORTES_PERFIL_FECHA
  ON REPORTES (ID_PERFIL_REPORTADOR, FECHA_REPORTE DESC);

-- --------------------------------------------------------------------------
-- Trigger TRG_REPORTES_REGLAS_BIU
-- Validaciones:
--   - existencia de perfil reportador y contenido,
--   - rol de moderador (solo soporte/admin),
--   - no reabrir reportes cerrados,
--   - fechas de actualizacion y resolucion coherentes.
-- Errores: -20061..-20066
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_REPORTES_REGLAS_BIU
BEFORE INSERT OR UPDATE ON REPORTES
FOR EACH ROW
DECLARE
  V_EXISTE NUMBER;
  V_ROL_MODERADOR USUARIOS.ROL%TYPE;
BEGIN
  -- Validar existencia del perfil reportador.
  SELECT COUNT(*)
    INTO V_EXISTE
    FROM PERFILES
   WHERE ID_PERFIL = :NEW.ID_PERFIL_REPORTADOR;

  IF V_EXISTE = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20061,
      'No existe el perfil reportador asociado al reporte'
    );
  END IF;

  -- Validar existencia del contenido reportado.
  SELECT COUNT(*)
    INTO V_EXISTE
    FROM CONTENIDOS
   WHERE ID_CONTENIDO = :NEW.ID_CONTENIDO;

  IF V_EXISTE = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20062,
      'No existe el contenido asociado al reporte'
    );
  END IF;

  -- Si hay moderador asignado, validar su rol.
  IF :NEW.ID_USUARIO_MODERADOR IS NOT NULL THEN
    SELECT U.ROL
      INTO V_ROL_MODERADOR
      FROM USUARIOS U
     WHERE U.ID_USUARIO = :NEW.ID_USUARIO_MODERADOR;

    IF LOWER(V_ROL_MODERADOR) NOT IN ('soporte', 'admin') THEN
      RAISE_APPLICATION_ERROR(
        -20063,
        'Solo usuarios con rol soporte o admin pueden moderar reportes'
      );
    END IF;
  END IF;

  -- Regla: reportes cerrados no se pueden reabrir.
  IF UPDATING THEN
    IF :OLD.ESTADO_REPORTE IN ('RESUELTO', 'DESCARTADO')
       AND :NEW.ESTADO_REPORTE <> :OLD.ESTADO_REPORTE THEN
      RAISE_APPLICATION_ERROR(
        -20064,
        'No se permite reabrir reportes cerrados'
      );
    END IF;
  END IF;

  -- Actualizar timestamp de cambios.
  :NEW.FECHA_ACTUALIZACION := CURRENT_TIMESTAMP;

  -- Reglas al cerrar: moderador obligatorio y fecha de resolucion.
  IF :NEW.ESTADO_REPORTE IN ('RESUELTO', 'DESCARTADO') THEN
    IF :NEW.ID_USUARIO_MODERADOR IS NULL THEN
      RAISE_APPLICATION_ERROR(
        -20065,
        'Para cerrar un reporte se requiere moderador asignado'
      );
    END IF;

    IF :NEW.FECHA_RESOLUCION IS NULL THEN
      :NEW.FECHA_RESOLUCION := CURRENT_TIMESTAMP;
    END IF;
  ELSIF :NEW.ESTADO_REPORTE = 'ABIERTO' THEN
    :NEW.FECHA_RESOLUCION := NULL;
    :NEW.RESOLUCION := NULL;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20066,
      'No existe el usuario moderador asociado al reporte'
    );
END;
/

-- --------------------------------------------------------------------------
-- Vista VW_REPORTES_PENDIENTES_SOPORTE
-- Lista reportes activos para bandeja de soporte (abiertos o en revision).
-- --------------------------------------------------------------------------
CREATE OR REPLACE VIEW VW_REPORTES_PENDIENTES_SOPORTE AS
SELECT
  R.ID_REPORTE,
  R.ID_PERFIL_REPORTADOR,
  P.NOMBRE AS NOMBRE_PERFIL_REPORTADOR,
  R.ID_CONTENIDO,
  C.TITULO,
  R.MOTIVO,
  R.DETALLE,
  R.ESTADO_REPORTE,
  R.ID_USUARIO_MODERADOR,
  R.FECHA_REPORTE,
  R.FECHA_ACTUALIZACION
FROM REPORTES R
INNER JOIN PERFILES P ON P.ID_PERFIL = R.ID_PERFIL_REPORTADOR
INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
WHERE R.ESTADO_REPORTE IN ('ABIERTO', 'EN_REVISION');

COMMIT;
