-- ============================================================================
-- MinFlix - Epica 6: Analitica e Inteligencia Empresarial (NT1)
-- Ejecutar como MINFLIX_APP en XEPDB1
-- Requiere: scripts 01 al 08 ejecutados previamente
-- ============================================================================

-- ----------------------------------------------------------------------------
-- Seccion 1: Consultas Parametrizadas (3 minimo requerido)
-- ----------------------------------------------------------------------------

-- Parametrizada 1: Top 10 contenidos mas reproducidos en un periodo
-- Uso: definir P_FECHA_INICIO y P_FECHA_FIN antes de ejecutar
DEFINE P_FECHA_INICIO = '2024-01-01'
DEFINE P_FECHA_FIN    = '2026-12-31'

SELECT * FROM (
  SELECT
    C.TITULO,
    C.TIPO_CONTENIDO,
    CAT.NOMBRE AS CATEGORIA,
    COUNT(R.ID_REPRODUCCION) AS TOTAL_REPRODUCCIONES,
    ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS PROMEDIO_AVANCE
  FROM REPRODUCCIONES R
  INNER JOIN CONTENIDOS C   ON C.ID_CONTENIDO   = R.ID_CONTENIDO
  INNER JOIN CATEGORIAS CAT ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
  WHERE R.FECHA_INICIO BETWEEN TO_DATE('&&P_FECHA_INICIO', 'YYYY-MM-DD')
                            AND TO_DATE('&&P_FECHA_FIN',    'YYYY-MM-DD')
  GROUP BY C.TITULO, C.TIPO_CONTENIDO, CAT.NOMBRE
  ORDER BY TOTAL_REPRODUCCIONES DESC
)
WHERE ROWNUM <= 10;

-- Parametrizada 2: Ingresos totales por plan en un rango de fechas
DEFINE P_FECHA_INICIO = '2024-01-01'
DEFINE P_FECHA_FIN    = '2026-12-31'

SELECT
  PL.NOMBRE AS PLAN,
  COUNT(PA.ID_PAGO)          AS TOTAL_PAGOS,
  SUM(PA.MONTO_FINAL)        AS INGRESOS_TOTALES,
  ROUND(AVG(PA.MONTO_FINAL), 2) AS PROMEDIO_PAGO
FROM PAGOS PA
INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
WHERE PA.ESTADO_PAGO = 'EXITOSO'
  AND PA.FECHA_PAGO BETWEEN TO_DATE('&&P_FECHA_INICIO', 'YYYY-MM-DD')
                        AND TO_DATE('&&P_FECHA_FIN',    'YYYY-MM-DD')
GROUP BY PL.NOMBRE
ORDER BY INGRESOS_TOTALES DESC;

-- Parametrizada 3: Calificaciones promedio por categoria de contenido
DEFINE P_CLASIFICACION = '+13'

SELECT
  CAT.NOMBRE                    AS CATEGORIA,
  C.TITULO,
  COUNT(CAL.ID_CALIFICACION)    AS TOTAL_CALIFICACIONES,
  ROUND(AVG(CAL.PUNTUACION), 2) AS PROMEDIO_ESTRELLAS,
  MIN(CAL.PUNTUACION)           AS MIN_ESTRELLAS,
  MAX(CAL.PUNTUACION)           AS MAX_ESTRELLAS
FROM CALIFICACIONES CAL
INNER JOIN CONTENIDOS C   ON C.ID_CONTENIDO   = CAL.ID_CONTENIDO
INNER JOIN CATEGORIAS CAT ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
WHERE C.CLASIFICACION_EDAD = '&&P_CLASIFICACION'
GROUP BY CAT.NOMBRE, C.TITULO
ORDER BY PROMEDIO_ESTRELLAS DESC;

-- ----------------------------------------------------------------------------
-- Seccion 2: Tablas Cruzadas PIVOT y UNPIVOT (2 de cada una)
-- ----------------------------------------------------------------------------

-- PIVOT 1: Reproducciones por dispositivo cruzadas con tipo de contenido
SELECT *
FROM (
  SELECT C.TIPO_CONTENIDO, R.ULTIMO_DISPOSITIVO, R.ID_REPRODUCCION
    FROM REPRODUCCIONES R
    INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
   WHERE R.ULTIMO_DISPOSITIVO IS NOT NULL
)
PIVOT (
  COUNT(ID_REPRODUCCION)
  FOR ULTIMO_DISPOSITIVO IN (
    'celular'     AS CELULAR,
    'computador'  AS COMPUTADOR,
    'TV'          AS TV,
    'tablet'      AS TABLET
  )
)
ORDER BY TIPO_CONTENIDO;

-- PIVOT 2: Ingresos por plan cruzados con metodo de pago
SELECT *
FROM (
  SELECT PL.NOMBRE AS PLAN, PA.METODO_PAGO, PA.MONTO_FINAL
    FROM PAGOS PA
    INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
    INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
   WHERE PA.ESTADO_PAGO = 'EXITOSO'
)
PIVOT (
  SUM(MONTO_FINAL)
  FOR METODO_PAGO IN (
    'PSE'             AS PSE,
    'NEQUI'           AS NEQUI,
    'TARJETA_CREDITO' AS TARJETA_CREDITO,
    'TARJETA_DEBITO'  AS TARJETA_DEBITO,
    'DAVIPLATA'       AS DAVIPLATA
  )
)
ORDER BY PLAN;

-- UNPIVOT 1: Expandir columnas de dispositivo a filas para analisis detallado
SELECT TIPO_CONTENIDO, DISPOSITIVO, TOTAL_REPRODUCCIONES
FROM (
  SELECT *
  FROM (
    SELECT C.TIPO_CONTENIDO, R.ULTIMO_DISPOSITIVO, R.ID_REPRODUCCION
      FROM REPRODUCCIONES R
      INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
     WHERE R.ULTIMO_DISPOSITIVO IS NOT NULL
  )
  PIVOT (
    COUNT(ID_REPRODUCCION)
    FOR ULTIMO_DISPOSITIVO IN (
      'celular'    AS CELULAR,
      'computador' AS COMPUTADOR,
      'TV'         AS TV,
      'tablet'     AS TABLET
    )
  )
)
UNPIVOT (
  TOTAL_REPRODUCCIONES FOR DISPOSITIVO IN (CELULAR, COMPUTADOR, TV, TABLET)
)
ORDER BY TIPO_CONTENIDO, DISPOSITIVO;

-- UNPIVOT 2: Expandir ingresos por metodo de pago a filas
SELECT PLAN, METODO_PAGO, INGRESOS
FROM (
  SELECT *
  FROM (
    SELECT PL.NOMBRE AS PLAN, PA.METODO_PAGO, PA.MONTO_FINAL
      FROM PAGOS PA
      INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
      INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
     WHERE PA.ESTADO_PAGO = 'EXITOSO'
  )
  PIVOT (
    SUM(MONTO_FINAL)
    FOR METODO_PAGO IN (
      'PSE'             AS PSE,
      'NEQUI'           AS NEQUI,
      'TARJETA_CREDITO' AS TARJETA_CREDITO,
      'TARJETA_DEBITO'  AS TARJETA_DEBITO,
      'DAVIPLATA'       AS DAVIPLATA
    )
  )
)
UNPIVOT (
  INGRESOS FOR METODO_PAGO IN (PSE, NEQUI, TARJETA_CREDITO, TARJETA_DEBITO, DAVIPLATA)
)
ORDER BY PLAN, METODO_PAGO;

-- ----------------------------------------------------------------------------
-- Seccion 3: Agrupamientos ROLLUP, CUBE, GROUPING SETS (4 minimo requerido)
-- ----------------------------------------------------------------------------

-- Agrupamiento 1: ROLLUP - Ingresos por plan y mes con subtotales
SELECT
  PL.NOMBRE                              AS PLAN,
  TO_CHAR(PA.FECHA_PERIODO, 'YYYY-MM')   AS MES,
  COUNT(PA.ID_PAGO)                      AS TOTAL_PAGOS,
  SUM(PA.MONTO_FINAL)                    AS INGRESOS,
  GROUPING(PL.NOMBRE)                    AS ES_SUBTOTAL_PLAN,
  GROUPING(TO_CHAR(PA.FECHA_PERIODO, 'YYYY-MM')) AS ES_TOTAL_GENERAL
FROM PAGOS PA
INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
WHERE PA.ESTADO_PAGO = 'EXITOSO'
GROUP BY ROLLUP(PL.NOMBRE, TO_CHAR(PA.FECHA_PERIODO, 'YYYY-MM'))
ORDER BY PL.NOMBRE NULLS LAST, MES NULLS LAST;

-- Agrupamiento 2: CUBE - Reproducciones por categoria y dispositivo
SELECT
  CAT.NOMBRE                AS CATEGORIA,
  R.ULTIMO_DISPOSITIVO      AS DISPOSITIVO,
  COUNT(R.ID_REPRODUCCION)  AS TOTAL_REPRODUCCIONES,
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS PROMEDIO_AVANCE,
  GROUPING(CAT.NOMBRE)           AS ES_TOTAL_CATEGORIA,
  GROUPING(R.ULTIMO_DISPOSITIVO) AS ES_TOTAL_DISPOSITIVO
FROM REPRODUCCIONES R
INNER JOIN CONTENIDOS C   ON C.ID_CONTENIDO   = R.ID_CONTENIDO
INNER JOIN CATEGORIAS CAT ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
WHERE R.ULTIMO_DISPOSITIVO IS NOT NULL
GROUP BY CUBE(CAT.NOMBRE, R.ULTIMO_DISPOSITIVO)
ORDER BY CAT.NOMBRE NULLS LAST, R.ULTIMO_DISPOSITIVO NULLS LAST;

-- Agrupamiento 3: GROUPING SETS - Pagos por plan y por metodo de pago
SELECT
  PL.NOMBRE        AS PLAN,
  PA.METODO_PAGO,
  PA.ESTADO_PAGO,
  COUNT(*)         AS TOTAL_PAGOS,
  SUM(PA.MONTO_FINAL) AS INGRESOS_TOTALES
FROM PAGOS PA
INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
GROUP BY GROUPING SETS (
  (PL.NOMBRE),
  (PA.METODO_PAGO),
  (PA.ESTADO_PAGO),
  ()
)
ORDER BY PL.NOMBRE NULLS LAST, PA.METODO_PAGO NULLS LAST;

-- Agrupamiento 4: ROLLUP con GROUPING() para identificar filas de subtotal
SELECT
  CASE GROUPING(C.TIPO_CONTENIDO) WHEN 1 THEN '** TODOS **' ELSE C.TIPO_CONTENIDO END AS TIPO,
  CASE GROUPING(R.ULTIMO_DISPOSITIVO) WHEN 1 THEN '** TODOS **' ELSE R.ULTIMO_DISPOSITIVO END AS DISPOSITIVO,
  COUNT(R.ID_REPRODUCCION)           AS REPRODUCCIONES,
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS AVANCE_PROMEDIO
FROM REPRODUCCIONES R
INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
WHERE R.ULTIMO_DISPOSITIVO IS NOT NULL
GROUP BY ROLLUP(C.TIPO_CONTENIDO, R.ULTIMO_DISPOSITIVO)
ORDER BY C.TIPO_CONTENIDO NULLS LAST, R.ULTIMO_DISPOSITIVO NULLS LAST;

-- ----------------------------------------------------------------------------
-- Seccion 4: Vistas Materializadas (2 minimo requerido)
-- ----------------------------------------------------------------------------

-- Vista Materializada 1: Rating promedio por contenido
BEGIN EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW MV_RATING_CONTENIDO'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE MATERIALIZED VIEW MV_RATING_CONTENIDO
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
  C.ID_CONTENIDO,
  C.TITULO,
  C.TIPO_CONTENIDO,
  CAT.NOMBRE                        AS CATEGORIA,
  COUNT(CAL.ID_CALIFICACION)        AS TOTAL_CALIFICACIONES,
  ROUND(AVG(CAL.PUNTUACION), 2)     AS RATING_PROMEDIO,
  COUNT(R.ID_REPRODUCCION)          AS TOTAL_REPRODUCCIONES,
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS AVANCE_PROMEDIO
FROM CONTENIDOS C
INNER JOIN CATEGORIAS CAT ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN CALIFICACIONES CAL ON CAL.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN REPRODUCCIONES R   ON R.ID_CONTENIDO   = C.ID_CONTENIDO
GROUP BY C.ID_CONTENIDO, C.TITULO, C.TIPO_CONTENIDO, CAT.NOMBRE;

-- Vista Materializada 2: Metricas financieras mensuales por plan
BEGIN EXECUTE IMMEDIATE 'DROP MATERIALIZED VIEW MV_METRICAS_FINANCIERAS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
CREATE MATERIALIZED VIEW MV_METRICAS_FINANCIERAS
BUILD IMMEDIATE
REFRESH COMPLETE ON DEMAND
AS
SELECT
  PL.NOMBRE                            AS PLAN,
  TO_CHAR(PA.FECHA_PERIODO, 'YYYY-MM') AS MES,
  COUNT(PA.ID_PAGO)                    AS TOTAL_PAGOS,
  SUM(CASE WHEN PA.ESTADO_PAGO = 'EXITOSO'    THEN 1 ELSE 0 END) AS PAGOS_EXITOSOS,
  SUM(CASE WHEN PA.ESTADO_PAGO = 'FALLIDO'    THEN 1 ELSE 0 END) AS PAGOS_FALLIDOS,
  SUM(CASE WHEN PA.ESTADO_PAGO = 'REEMBOLSADO' THEN 1 ELSE 0 END) AS PAGOS_REEMBOLSADOS,
  SUM(CASE WHEN PA.ESTADO_PAGO = 'EXITOSO'    THEN PA.MONTO_FINAL ELSE 0 END) AS INGRESOS_NETOS,
  SUM(CASE WHEN PA.ESTADO_PAGO = 'REEMBOLSADO' THEN PA.MONTO_FINAL ELSE 0 END) AS TOTAL_REEMBOLSOS,
  ROUND(AVG(CASE WHEN PA.ESTADO_PAGO = 'EXITOSO' THEN PA.MONTO_DESCUENTO END), 2) AS DESCUENTO_PROMEDIO
FROM PAGOS PA
INNER JOIN USUARIOS U  ON U.ID_USUARIO = PA.ID_USUARIO
INNER JOIN PLANES   PL ON PL.ID_PLAN   = U.ID_PLAN
GROUP BY PL.NOMBRE, TO_CHAR(PA.FECHA_PERIODO, 'YYYY-MM');

-- Consultar las vistas materializadas
SELECT * FROM MV_RATING_CONTENIDO    ORDER BY RATING_PROMEDIO DESC NULLS LAST;
SELECT * FROM MV_METRICAS_FINANCIERAS ORDER BY MES DESC, PLAN;

-- ----------------------------------------------------------------------------
-- Seccion 5: Fragmentacion - Particionamiento de REPRODUCCIONES por anio
-- ----------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE REPRODUCCIONES_PART CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE REPRODUCCIONES_PART (
  ID_REPRODUCCION          NUMBER GENERATED BY DEFAULT AS IDENTITY,
  ID_PERFIL                NUMBER        NOT NULL,
  ID_CONTENIDO             NUMBER        NOT NULL,
  PROGRESO_SEGUNDOS        NUMBER(10,0)  DEFAULT 0 NOT NULL,
  DURACION_TOTAL_SEGUNDOS  NUMBER(10,0)  NULL,
  PORCENTAJE_AVANCE        NUMBER(5,2)   DEFAULT 0 NOT NULL,
  ULTIMO_DISPOSITIVO       VARCHAR2(80)  NULL,
  ESTADO_REPRODUCCION      VARCHAR2(20)  DEFAULT 'EN_PROGRESO' NOT NULL,
  FECHA_INICIO             DATE          NOT NULL,
  FECHA_ULTIMO_EVENTO      DATE          NOT NULL
)
PARTITION BY RANGE (FECHA_INICIO) (
  PARTITION P_ANTES_2023 VALUES LESS THAN (DATE '2023-01-01'),
  PARTITION P_2023       VALUES LESS THAN (DATE '2024-01-01'),
  PARTITION P_2024       VALUES LESS THAN (DATE '2025-01-01'),
  PARTITION P_2025       VALUES LESS THAN (DATE '2026-01-01'),
  PARTITION P_2026_PLUS  VALUES LESS THAN (MAXVALUE)
);

-- Poblar la tabla particionada con los datos existentes
INSERT INTO REPRODUCCIONES_PART (
  ID_PERFIL, ID_CONTENIDO, PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS,
  PORCENTAJE_AVANCE, ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  FECHA_INICIO, FECHA_ULTIMO_EVENTO
)
SELECT
  ID_PERFIL, ID_CONTENIDO, PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS,
  PORCENTAJE_AVANCE, ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  TRUNC(FECHA_INICIO), TRUNC(FECHA_ULTIMO_EVENTO)
FROM REPRODUCCIONES;

COMMIT;

-- Verificar distribucion por particion
BEGIN
  DBMS_STATS.GATHER_TABLE_STATS(
    OWNNAME => 'MINFLIX_APP',
    TABNAME => 'REPRODUCCIONES_PART'
  );
END;
/

SELECT TABLE_NAME, PARTITION_NAME, NUM_ROWS
  FROM USER_TAB_PARTITIONS
 WHERE TABLE_NAME = 'REPRODUCCIONES_PART'
 ORDER BY PARTITION_NAME;

-- ----------------------------------------------------------------------------
-- Verificacion final de objetos de analitica
-- ----------------------------------------------------------------------------
SELECT OBJECT_NAME, OBJECT_TYPE, STATUS
  FROM USER_OBJECTS
 WHERE OBJECT_NAME IN (
   'MV_RATING_CONTENIDO',
   'MV_METRICAS_FINANCIERAS',
   'REPRODUCCIONES_PART'
 )
 ORDER BY OBJECT_TYPE, OBJECT_NAME;
