-- ============================================================================
-- MinFlix - Iteracion 5 (Finanzas + Referidos)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla REFERIDOS
-- Relaciona un usuario referente con un referido para beneficios.
-- Reglas:
--   - Un referido solo puede estar asociado a un referente (UK).
--   - No se permite auto-referido.
--   - Estado controla si el descuento aplica.
-- --------------------------------------------------------------------------
CREATE TABLE REFERIDOS (
  -- PK: identificador del referido.
  ID_REFERIDO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Usuario que refiere.
  ID_USUARIO_REFERENTE NUMBER NOT NULL,
  -- Usuario referido (unico en el sistema de referidos).
  ID_USUARIO_REFERIDO NUMBER NOT NULL,
  -- Fecha de relacion de referido.
  FECHA_REFERIDO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Estado del referido (pendiente/validado/anulado).
  ESTADO_REFERIDO VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  -- Descuento otorgado (porcentaje).
  DESCUENTO_PCT NUMBER(5,2) DEFAULT 0 NOT NULL,
  -- Un referido solo puede aparecer una vez.
  CONSTRAINT UK_REFERIDOS_USUARIO_REFERIDO UNIQUE (ID_USUARIO_REFERIDO),
  -- Validaciones de dominio.
  CONSTRAINT CK_REFERIDOS_ESTADO CHECK (
    ESTADO_REFERIDO IN ('PENDIENTE', 'VALIDADO', 'ANULADO')
  ),
  CONSTRAINT CK_REFERIDOS_DESCUENTO CHECK (DESCUENTO_PCT BETWEEN 0 AND 100),
  CONSTRAINT CK_REFERIDOS_DISTINTO CHECK (
    ID_USUARIO_REFERENTE <> ID_USUARIO_REFERIDO
  ),
  CONSTRAINT FK_REFERIDOS_REFERENTE FOREIGN KEY (ID_USUARIO_REFERENTE)
    REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_REFERIDOS_REFERIDO FOREIGN KEY (ID_USUARIO_REFERIDO)
    REFERENCES USUARIOS(ID_USUARIO)
);

-- Indice para consultas de referidos por referente y estado.
CREATE INDEX IDX_REFERIDOS_REFERENTE_ESTADO
  ON REFERIDOS (ID_USUARIO_REFERENTE, ESTADO_REFERIDO, FECHA_REFERIDO DESC);

-- --------------------------------------------------------------------------
-- Tabla FACTURACIONES
-- Registra el ciclo mensual de cobro por usuario.
-- Campos clave:
--   PERIODO_ANIO/PERIODO_MES: llave de periodo (UK por usuario).
--   MONTO_BASE y MONTO_FINAL: calculo de descuentos.
--   ESTADO_FACTURA: PENDIENTE/PAGADA/VENCIDA/ANULADA.
-- --------------------------------------------------------------------------
CREATE TABLE FACTURACIONES (
  -- PK: identificador de la factura.
  ID_FACTURACION NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Usuario facturado.
  ID_USUARIO NUMBER NOT NULL,
  -- Periodo de la factura (anio/mes).
  PERIODO_ANIO NUMBER(4,0) NOT NULL,
  PERIODO_MES NUMBER(2,0) NOT NULL,
  -- Fechas de corte y vencimiento.
  FECHA_CORTE DATE NOT NULL,
  FECHA_VENCIMIENTO DATE NOT NULL,
  -- Monto base y descuentos.
  MONTO_BASE NUMBER(10,2) NOT NULL,
  DESCUENTO_REFERIDOS_PCT NUMBER(5,2) DEFAULT 0 NOT NULL,
  DESCUENTO_FIDELIDAD_PCT NUMBER(5,2) DEFAULT 0 NOT NULL,
  -- Monto final calculado por trigger.
  MONTO_FINAL NUMBER(10,2) NOT NULL,
  -- Estado de la factura.
  ESTADO_FACTURA VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  -- Fecha de pago cuando aplica.
  FECHA_PAGO TIMESTAMP NULL,
  -- Unicidad por usuario/periodo.
  CONSTRAINT UK_FACTURACIONES_USUARIO_PERIODO UNIQUE (
    ID_USUARIO,
    PERIODO_ANIO,
    PERIODO_MES
  ),
  CONSTRAINT CK_FACTURACIONES_PERIODO_MES CHECK (
    PERIODO_MES BETWEEN 1 AND 12
  ),
  CONSTRAINT CK_FACTURACIONES_MONTO_BASE CHECK (MONTO_BASE >= 0),
  CONSTRAINT CK_FACTURACIONES_DESC_REF CHECK (
    DESCUENTO_REFERIDOS_PCT BETWEEN 0 AND 100
  ),
  CONSTRAINT CK_FACTURACIONES_DESC_FID CHECK (
    DESCUENTO_FIDELIDAD_PCT BETWEEN 0 AND 100
  ),
  CONSTRAINT CK_FACTURACIONES_MONTO_FINAL CHECK (MONTO_FINAL >= 0),
  CONSTRAINT CK_FACTURACIONES_ESTADO CHECK (
    ESTADO_FACTURA IN ('PENDIENTE', 'PAGADA', 'VENCIDA', 'ANULADA')
  ),
  CONSTRAINT FK_FACTURACIONES_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID_USUARIO)
);

-- Indice para listar facturas por usuario y estado.
CREATE INDEX IDX_FACTURACIONES_USUARIO_ESTADO
  ON FACTURACIONES (ID_USUARIO, ESTADO_FACTURA, FECHA_VENCIMIENTO DESC);

-- --------------------------------------------------------------------------
-- Tabla PAGOS
-- Transacciones asociadas a una factura (metodo y estado de pago).
-- --------------------------------------------------------------------------
CREATE TABLE PAGOS (
  -- PK: identificador del pago.
  ID_PAGO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK a la factura.
  ID_FACTURACION NUMBER NOT NULL,
  -- FK al usuario pagador.
  ID_USUARIO NUMBER NOT NULL,
  -- Fecha del pago.
  FECHA_PAGO TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Monto pagado.
  MONTO NUMBER(10,2) NOT NULL,
  -- Metodo de pago.
  METODO_PAGO VARCHAR2(30) NOT NULL,
  -- Estado transaccional.
  ESTADO_TRANSACCION VARCHAR2(20) DEFAULT 'PENDIENTE' NOT NULL,
  -- Referencia externa o simulada.
  REFERENCIA_PAGO VARCHAR2(120) NULL,
  -- Validaciones de dominio.
  CONSTRAINT CK_PAGOS_MONTO CHECK (MONTO >= 0),
  CONSTRAINT CK_PAGOS_METODO CHECK (
    METODO_PAGO IN (
      'TARJETA_CREDITO',
      'TARJETA_DEBITO',
      'PSE',
      'NEQUI',
      'DAVIPLATA'
    )
  ),
  CONSTRAINT CK_PAGOS_ESTADO CHECK (
    ESTADO_TRANSACCION IN ('EXITOSO', 'FALLIDO', 'PENDIENTE', 'REEMBOLSADO')
  ),
  CONSTRAINT FK_PAGOS_FACTURACION FOREIGN KEY (ID_FACTURACION)
    REFERENCES FACTURACIONES(ID_FACTURACION),
  CONSTRAINT FK_PAGOS_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID_USUARIO)
);

-- Indices para consultas por usuario y estado transaccional.
CREATE INDEX IDX_PAGOS_USUARIO_FECHA
  ON PAGOS (ID_USUARIO, FECHA_PAGO DESC);

CREATE INDEX IDX_PAGOS_ESTADO
  ON PAGOS (ESTADO_TRANSACCION, FECHA_PAGO DESC);

-- --------------------------------------------------------------------------
-- Trigger TRG_FACTURACIONES_CALCULO_BIU
-- Calcula MONTO_FINAL con descuentos y valida coherencia de fechas.
-- Errores:
--   -20081: fecha de vencimiento anterior a fecha de corte.
--   -20082: descuentos acumulados > 100%.
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_FACTURACIONES_CALCULO_BIU
BEFORE INSERT OR UPDATE ON FACTURACIONES
FOR EACH ROW
DECLARE
  -- Suma acumulada de descuentos (referidos + fidelidad) en porcentaje
  V_TOTAL_DESCUENTO NUMBER(6,2);
BEGIN
  -- Regla 1: la fecha de vencimiento debe ser igual o posterior a la fecha de corte.
  IF :NEW.FECHA_VENCIMIENTO < :NEW.FECHA_CORTE THEN
    RAISE_APPLICATION_ERROR(
      -20081,
      'La fecha de vencimiento no puede ser menor a la fecha de corte'
    );
  END IF;

  -- Paso 1: calcular descuento total sumando referidos y fidelidad.
  -- NVL maneja NULL como 0 para evitar errores de aritmetica con NULL.
  V_TOTAL_DESCUENTO := NVL(:NEW.DESCUENTO_REFERIDOS_PCT, 0)
    + NVL(:NEW.DESCUENTO_FIDELIDAD_PCT, 0);

  -- Regla 2: los descuentos acumulados no pueden superar el 100%.
  IF V_TOTAL_DESCUENTO > 100 THEN
    RAISE_APPLICATION_ERROR(
      -20082,
      'La suma de descuentos no puede superar el 100%'
    );
  END IF;

  -- Paso 2: calcular monto final aplicando descuentos al monto base.
  -- Formula: monto_base * (1 - descuento_total / 100).
  -- GREATEST(0, ...) garantiza que el monto final nunca sea negativo.
  :NEW.MONTO_FINAL := ROUND(
    GREATEST(
      0,
      NVL(:NEW.MONTO_BASE, 0) * (1 - (V_TOTAL_DESCUENTO / 100))
    ),
    2
  );

  -- Paso 3: si la factura se marca como PAGADA, registrar fecha de pago automaticamente.
  IF :NEW.ESTADO_FACTURA = 'PAGADA' AND :NEW.FECHA_PAGO IS NULL THEN
    :NEW.FECHA_PAGO := CURRENT_TIMESTAMP;
  END IF;
END;
/

-- --------------------------------------------------------------------------
-- Trigger TRG_PAGOS_ACTUALIZA_FACTURA_AI
-- Cuando un pago exitoso entra, actualiza la factura y reactiva la cuenta.
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_PAGOS_ACTUALIZA_FACTURA_AI
AFTER INSERT ON PAGOS
FOR EACH ROW
BEGIN
  -- Solo los pagos con estado EXITOSO impactan la factura y reactivan la cuenta.
  IF :NEW.ESTADO_TRANSACCION = 'EXITOSO' THEN
    -- Actualizar la factura asociada: marcar como PAGADA y registrar fecha de pago.
    -- NVL(FECHA_PAGO, :NEW.FECHA_PAGO) evita sobrescribir una fecha ya existente.
    UPDATE FACTURACIONES
       SET ESTADO_FACTURA = 'PAGADA',
           FECHA_PAGO = NVL(FECHA_PAGO, :NEW.FECHA_PAGO)
     WHERE ID_FACTURACION = :NEW.ID_FACTURACION;

    -- Reactivar la cuenta del usuario para permitir reproduccion nuevamente.
    UPDATE USUARIOS
       SET ESTADO_CUENTA = 'ACTIVO'
     WHERE ID_USUARIO = :NEW.ID_USUARIO;
  END IF;
END;
/

-- --------------------------------------------------------------------------
-- Procedimiento SP_APLICAR_MORA_CUENTAS
-- Marca facturas vencidas y desactiva cuentas con mora > 30 dias.
-- Pensado para ejecucion periodica (job nocturno).
-- --------------------------------------------------------------------------
CREATE OR REPLACE PROCEDURE SP_APLICAR_MORA_CUENTAS
IS
BEGIN
  -- Paso 1: marcar como VENCIDA las facturas PENDIENTES cuya fecha de vencimiento ya paso.
  -- TRUNC(SYSDATE) obtiene la fecha actual sin hora para comparar fechas puras.
  UPDATE FACTURACIONES F
     SET F.ESTADO_FACTURA = 'VENCIDA'
   WHERE F.ESTADO_FACTURA = 'PENDIENTE'
     AND F.FECHA_VENCIMIENTO < TRUNC(SYSDATE);

  -- Paso 2: desactivar cuentas de usuarios con facturas pendientes o vencidas
  -- cuya fecha de vencimiento tiene mas de 30 dias de retraso.
  UPDATE USUARIOS U
     SET U.ESTADO_CUENTA = 'INACTIVO'
   WHERE EXISTS (
     SELECT 1
       FROM FACTURACIONES F
      WHERE F.ID_USUARIO = U.ID_USUARIO
        AND F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
        AND F.FECHA_VENCIMIENTO <= TRUNC(SYSDATE) - 30
   );
END;
/

COMMIT;
