-- ============================================================================
-- MinFlix - Iteracion 5 (Organizacion de Equipo)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: 01_bootstrap_oracle_iteracion1.sql y 02_catalogo_base_iteracion2.sql
-- ============================================================================

-- --------------------------------------------------------------------------
-- Tabla DEPARTAMENTOS
-- Lista de areas internas de la compania.
-- El CHECK limita el conjunto permitido por el enunciado.
-- --------------------------------------------------------------------------
CREATE TABLE DEPARTAMENTOS (
  -- PK: identificador del departamento.
  ID_DEPARTAMENTO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Nombre del area interna.
  NOMBRE VARCHAR2(80) NOT NULL,
  -- Descripcion funcional.
  DESCRIPCION VARCHAR2(260) NULL,
  -- Unicidad por nombre.
  CONSTRAINT UK_DEPARTAMENTOS_NOMBRE UNIQUE (NOMBRE),
  -- Validacion de conjunto permitido.
  CONSTRAINT CK_DEPARTAMENTOS_NOMBRE CHECK (
    NOMBRE IN ('Tecnologia', 'Contenido', 'Marketing', 'Soporte', 'Finanzas')
  )
);

-- --------------------------------------------------------------------------
-- Tabla EMPLEADOS
-- Vincula usuarios de la plataforma con el organigrama interno.
-- Campos clave:
--   ID_USUARIO: relacion 1:1 con cuenta (UK).
--   ID_SUPERVISOR: jerarquia con autorreferencia.
--   ES_JEFE: identifica lideres de area.
-- --------------------------------------------------------------------------
CREATE TABLE EMPLEADOS (
  -- PK: identificador del empleado.
  ID_EMPLEADO NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al usuario asociado.
  ID_USUARIO NUMBER NOT NULL,
  -- FK al departamento.
  ID_DEPARTAMENTO NUMBER NOT NULL,
  -- FK al supervisor directo (autorreferencia).
  ID_SUPERVISOR NUMBER NULL,
  -- Cargo o rol interno.
  CARGO VARCHAR2(80) NOT NULL,
  -- Indicador de jefe de departamento.
  ES_JEFE NUMBER(1,0) DEFAULT 0 NOT NULL,
  -- Estado del empleado.
  ESTADO_EMPLEADO VARCHAR2(20) DEFAULT 'ACTIVO' NOT NULL,
  -- Fecha de ingreso (por defecto hoy).
  FECHA_INGRESO DATE DEFAULT TRUNC(SYSDATE) NOT NULL,
  -- Unicidad por usuario (1:1 con USUARIOS).
  CONSTRAINT UK_EMPLEADOS_USUARIO UNIQUE (ID_USUARIO),
  CONSTRAINT CK_EMPLEADOS_JEFE CHECK (ES_JEFE IN (0, 1)),
  CONSTRAINT CK_EMPLEADOS_ESTADO CHECK (
    ESTADO_EMPLEADO IN ('ACTIVO', 'INACTIVO')
  ),
  CONSTRAINT FK_EMPLEADOS_USUARIO FOREIGN KEY (ID_USUARIO)
    REFERENCES USUARIOS(ID_USUARIO),
  CONSTRAINT FK_EMPLEADOS_DEPARTAMENTO FOREIGN KEY (ID_DEPARTAMENTO)
    REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
  CONSTRAINT FK_EMPLEADOS_SUPERVISOR FOREIGN KEY (ID_SUPERVISOR)
    REFERENCES EMPLEADOS(ID_EMPLEADO)
);

-- Indices para consultas por departamento y jerarquia.
CREATE INDEX IDX_EMPLEADOS_DEPARTAMENTO
  ON EMPLEADOS (ID_DEPARTAMENTO, ES_JEFE, ESTADO_EMPLEADO);

CREATE INDEX IDX_EMPLEADOS_SUPERVISOR
  ON EMPLEADOS (ID_SUPERVISOR);

-- --------------------------------------------------------------------------
-- Trigger TRG_EMPLEADOS_JERARQUIA_BIU
-- Reglas:
--   - un empleado no se supervisa a si mismo,
--   - un jefe no debe tener supervisor directo,
--   - supervisor y subordinado deben estar en el mismo departamento.
-- Errores: -20091..-20094
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_EMPLEADOS_JERARQUIA_BIU
BEFORE INSERT OR UPDATE ON EMPLEADOS
FOR EACH ROW
DECLARE
  -- Departamento del supervisor asignado para validar que coincida
  V_DEPTO_SUPERVISOR EMPLEADOS.ID_DEPARTAMENTO%TYPE;
BEGIN
  -- Regla 1: evitar referencias reflexivas (un empleado no puede ser su propio jefe).
  IF :NEW.ID_SUPERVISOR IS NOT NULL AND :NEW.ID_SUPERVISOR = :NEW.ID_EMPLEADO THEN
    RAISE_APPLICATION_ERROR(
      -20091,
      'Un empleado no puede supervisarse a si mismo'
    );
  END IF;

  -- Regla 2: un jefe de departamento (ES_JEFE = 1) no debe tener supervisor directo.
  IF :NEW.ES_JEFE = 1 AND :NEW.ID_SUPERVISOR IS NOT NULL THEN
    RAISE_APPLICATION_ERROR(
      -20092,
      'Un jefe de departamento no debe registrar supervisor directo'
    );
  END IF;

  -- Regla 3: si hay supervisor asignado, validar que pertenezca al mismo departamento.
  IF :NEW.ID_SUPERVISOR IS NOT NULL THEN
    SELECT E.ID_DEPARTAMENTO
      INTO V_DEPTO_SUPERVISOR
      FROM EMPLEADOS E
     WHERE E.ID_EMPLEADO = :NEW.ID_SUPERVISOR;

    IF V_DEPTO_SUPERVISOR <> :NEW.ID_DEPARTAMENTO THEN
      RAISE_APPLICATION_ERROR(
        -20093,
        'Supervisor y subordinado deben pertenecer al mismo departamento'
      );
    END IF;
  END IF;
EXCEPTION
  -- Si el supervisor asignado no existe en la tabla EMPLEADOS
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20094,
      'No existe el supervisor asociado al empleado'
    );
END;
/

-- --------------------------------------------------------------------------
-- Trigger TRG_CONTENIDOS_PUBLICADOR_BIU
-- Valida que el publicador de contenido tenga rol admin o contenido.
-- --------------------------------------------------------------------------
CREATE OR REPLACE TRIGGER TRG_CONTENIDOS_PUBLICADOR_BIU
BEFORE INSERT OR UPDATE OF ID_EMPLEADO_PUBLICADOR ON CONTENIDOS
FOR EACH ROW
DECLARE
  -- Rol del usuario asignado como publicador del contenido
  V_ROL_PUBLICADOR USUARIOS.ROL%TYPE;
BEGIN
  -- Permitir contenidos sin publicador asignado (NULL es valido).
  IF :NEW.ID_EMPLEADO_PUBLICADOR IS NULL THEN
    RETURN;
  END IF;

  -- Paso 1: consultar el rol del usuario asignado como publicador.
  SELECT U.ROL
    INTO V_ROL_PUBLICADOR
    FROM USUARIOS U
   WHERE U.ID_USUARIO = :NEW.ID_EMPLEADO_PUBLICADOR;

  -- Regla: solo usuarios con rol 'admin' o 'contenido' pueden publicar contenidos.
  -- LOWER() para comparacion case-insensitive del rol.
  IF LOWER(V_ROL_PUBLICADOR) NOT IN ('admin', 'contenido') THEN
    RAISE_APPLICATION_ERROR(
      -20095,
      'El publicador debe tener rol admin o contenido'
    );
  END IF;
EXCEPTION
  -- Si el publicador asignado no existe en la tabla USUARIOS
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20096,
      'No existe el usuario publicador asociado al contenido'
    );
END;
/

-- Seed inicial de departamentos.
INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
VALUES ('Tecnologia', 'Desarrollo de plataforma, arquitectura y operacion tecnica.');

INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
VALUES ('Contenido', 'Gestion editorial y publicacion de catalogo multimedia.');

INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
VALUES ('Marketing', 'Promocion, crecimiento y campanas de adquisicion.');

INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
VALUES ('Soporte', 'Atencion de incidencias y moderacion de reportes.');

INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
VALUES ('Finanzas', 'Facturacion, recaudo, control de mora y beneficios.');

COMMIT;
