-- ============================================================================
-- MinFlix - Nucleo 5 (Seguridad de Acceso: PROFILE, Roles, Usuarios y GRANT)
-- Ejecutar como SYSTEM.
-- Requiere: scripts 01..10 ejecutados en el owner de objetos (SYSTEM en entorno actual).
-- ============================================================================

-- --------------------------------------------------------------------------
-- PROFILE de seguridad
-- --------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE PROFILE PRF_MINFLIX_OPERACION LIMIT
      SESSIONS_PER_USER 3
      IDLE_TIME 30
      FAILED_LOGIN_ATTEMPTS 5
      PASSWORD_LIFE_TIME 180
      PASSWORD_REUSE_TIME 365
      PASSWORD_REUSE_MAX 5
      CONNECT_TIME UNLIMITED
  ]';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2379 THEN
      RAISE;
    END IF;
END;
/

-- --------------------------------------------------------------------------
-- Roles requeridos por el enunciado
-- --------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE ROL_ADMIN';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1921 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE ROL_ANALISTA';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1921 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE ROL_SOPORTE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1921 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE ROLE ROL_CONTENIDO';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1921 THEN
      RAISE;
    END IF;
END;
/

-- --------------------------------------------------------------------------
-- GRANT por rol
-- --------------------------------------------------------------------------
-- ADMIN: acceso operativo amplio
GRANT SELECT, INSERT, UPDATE, DELETE ON USUARIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PERFILES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PLANES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CATEGORIAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_GENEROS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_RELACIONADOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPRODUCCIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FAVORITOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON CALIFICACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REPORTES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON REFERIDOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON FACTURACIONES TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON PAGOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON DEPARTAMENTOS TO ROL_ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE ON EMPLEADOS TO ROL_ADMIN;
GRANT SELECT ON VW_CONTENIDO_VISIBLE_POR_PERFIL TO ROL_ADMIN;
GRANT SELECT ON VW_CONTINUAR_VIENDO TO ROL_ADMIN;
GRANT SELECT ON VW_REPORTES_PENDIENTES_SOPORTE TO ROL_ADMIN;
GRANT EXECUTE ON FN_CLASIFICACION_PERMITIDA_PARA_PERFIL TO ROL_ADMIN;
GRANT EXECUTE ON SP_APLICAR_MORA_CUENTAS TO ROL_ADMIN;

-- ANALISTA: solo lectura sobre datos consolidados y operativos
GRANT SELECT ON PLANES TO ROL_ANALISTA;
GRANT SELECT ON USUARIOS TO ROL_ANALISTA;
GRANT SELECT ON PERFILES TO ROL_ANALISTA;
GRANT SELECT ON CATEGORIAS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDOS TO ROL_ANALISTA;
GRANT SELECT ON GENEROS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDOS_GENEROS TO ROL_ANALISTA;
GRANT SELECT ON TEMPORADAS TO ROL_ANALISTA;
GRANT SELECT ON EPISODIOS TO ROL_ANALISTA;
GRANT SELECT ON CONTENIDOS_RELACIONADOS TO ROL_ANALISTA;
GRANT SELECT ON REPRODUCCIONES TO ROL_ANALISTA;
GRANT SELECT ON FAVORITOS TO ROL_ANALISTA;
GRANT SELECT ON CALIFICACIONES TO ROL_ANALISTA;
GRANT SELECT ON REPORTES TO ROL_ANALISTA;
GRANT SELECT ON REFERIDOS TO ROL_ANALISTA;
GRANT SELECT ON FACTURACIONES TO ROL_ANALISTA;
GRANT SELECT ON PAGOS TO ROL_ANALISTA;
GRANT SELECT ON VW_CONTINUAR_VIENDO TO ROL_ANALISTA;
GRANT SELECT ON VW_REPORTES_PENDIENTES_SOPORTE TO ROL_ANALISTA;

-- SOPORTE: manejo de reportes, lectura de contexto, sin privilegios de publicacion
GRANT SELECT ON USUARIOS TO ROL_SOPORTE;
GRANT SELECT ON PERFILES TO ROL_SOPORTE;
GRANT SELECT ON CONTENIDOS TO ROL_SOPORTE;
GRANT SELECT ON CATEGORIAS TO ROL_SOPORTE;
GRANT SELECT ON REPORTES TO ROL_SOPORTE;
GRANT INSERT ON REPORTES TO ROL_SOPORTE;
GRANT UPDATE ON REPORTES TO ROL_SOPORTE;
GRANT SELECT ON VW_REPORTES_PENDIENTES_SOPORTE TO ROL_SOPORTE;

-- CONTENIDO: mantenimiento editorial de catalogo
GRANT SELECT ON CATEGORIAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE ON CONTENIDOS TO ROL_CONTENIDO;
GRANT SELECT ON GENEROS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_GENEROS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON TEMPORADAS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON EPISODIOS TO ROL_CONTENIDO;
GRANT SELECT, INSERT, UPDATE, DELETE ON CONTENIDOS_RELACIONADOS TO ROL_CONTENIDO;

-- --------------------------------------------------------------------------
-- Usuarios de base de datos para demostracion NT5
-- --------------------------------------------------------------------------
BEGIN
  EXECUTE IMMEDIATE 'CREATE USER MINFLIX_ADMIN IDENTIFIED BY "Admin123*"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER MINFLIX_ANALISTA IDENTIFIED BY "Analista123*"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER MINFLIX_SOPORTE IDENTIFIED BY "Soporte123*"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE USER MINFLIX_CONTENIDO IDENTIFIED BY "Contenido123*"';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -1920 THEN
      RAISE;
    END IF;
END;
/

ALTER USER MINFLIX_ADMIN PROFILE PRF_MINFLIX_OPERACION;
ALTER USER MINFLIX_ANALISTA PROFILE PRF_MINFLIX_OPERACION;
ALTER USER MINFLIX_SOPORTE PROFILE PRF_MINFLIX_OPERACION;
ALTER USER MINFLIX_CONTENIDO PROFILE PRF_MINFLIX_OPERACION;

GRANT CREATE SESSION TO MINFLIX_ADMIN;
GRANT CREATE SESSION TO MINFLIX_ANALISTA;
GRANT CREATE SESSION TO MINFLIX_SOPORTE;
GRANT CREATE SESSION TO MINFLIX_CONTENIDO;

GRANT ROL_ADMIN TO MINFLIX_ADMIN;
GRANT ROL_ANALISTA TO MINFLIX_ANALISTA;
GRANT ROL_SOPORTE TO MINFLIX_SOPORTE;
GRANT ROL_CONTENIDO TO MINFLIX_CONTENIDO;

-- --------------------------------------------------------------------------
-- Evidencia sugerida de restriccion de acceso (manual)
-- --------------------------------------------------------------------------
-- 1) CONNECT MINFLIX_ANALISTA/Analista123*;
-- 2) Intentar un INSERT sobre CONTENIDOS y verificar ORA-01031.
-- 3) CONNECT MINFLIX_SOPORTE/Soporte123*;
-- 4) Actualizar REPORTES en estados permitidos y validar exito.
-- 5) CONNECT MINFLIX_CONTENIDO/Contenido123*;
-- 6) Intentar UPDATE en PAGOS y verificar ORA-01031.

COMMIT;
