-- ============================================================================
-- MinFlix - Seed Extra Funcional (Iteracion 5)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: scripts 01..13 aplicados.
-- Objetivo:
--   1) Poblar datos funcionales de catalogo, comunidad, finanzas y equipo.
--   2) Mantener idempotencia para permitir re-ejecucion sin duplicados logicos.
-- ============================================================================

SET SERVEROUTPUT ON;

DECLARE
  C_EMAIL_ADMIN      CONSTANT VARCHAR2(180) := 'admin.seed@minflix.local';
  C_EMAIL_SOPORTE    CONSTANT VARCHAR2(180) := 'soporte.seed@minflix.local';
  C_EMAIL_CONTENIDO  CONSTANT VARCHAR2(180) := 'contenido.seed@minflix.local';
  C_EMAIL_ANALISTA   CONSTANT VARCHAR2(180) := 'analista.seed@minflix.local';
  C_EMAIL_USUARIO    CONSTANT VARCHAR2(180) := 'usuario.seed@minflix.local';

  C_PREFIJO_SEED     CONSTANT VARCHAR2(20) := 'SEED14';

  V_CNT_CONTENIDOS_SEED NUMBER;
  V_CNT_REPORTE_SEED    NUMBER;
  V_CNT_PAGO_SEED       NUMBER;

  FUNCTION GET_USUARIO_ID (
    P_EMAIL IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID USUARIOS.ID_USUARIO%TYPE;
  BEGIN
    SELECT U.ID_USUARIO
      INTO V_ID
      FROM USUARIOS U
     WHERE UPPER(U.EMAIL) = UPPER(P_EMAIL);

    RETURN V_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(
        -20140,
        'No existe usuario para email: ' || P_EMAIL || '. Ejecuta primero script 13.'
      );
  END;

  FUNCTION GET_PERFIL_ID (
    P_EMAIL IN VARCHAR2,
    P_NOMBRE_PERFIL IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID_USUARIO USUARIOS.ID_USUARIO%TYPE;
    V_ID_PERFIL  PERFILES.ID_PERFIL%TYPE;
  BEGIN
    V_ID_USUARIO := GET_USUARIO_ID(P_EMAIL);

    BEGIN
      SELECT P.ID_PERFIL
        INTO V_ID_PERFIL
        FROM PERFILES P
       WHERE P.ID_USUARIO = V_ID_USUARIO
         AND UPPER(P.NOMBRE) = UPPER(P_NOMBRE_PERFIL);
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        SELECT MIN(P.ID_PERFIL)
          INTO V_ID_PERFIL
          FROM PERFILES P
         WHERE P.ID_USUARIO = V_ID_USUARIO;

        IF V_ID_PERFIL IS NULL THEN
          RAISE_APPLICATION_ERROR(
            -20141,
            'El usuario ' || P_EMAIL || ' no tiene perfiles registrados'
          );
        END IF;
    END;

    RETURN V_ID_PERFIL;
  END;

  FUNCTION GET_CATEGORIA_ID (
    P_NOMBRE IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID CATEGORIAS.ID_CATEGORIA%TYPE;
  BEGIN
    SELECT C.ID_CATEGORIA
      INTO V_ID
      FROM CATEGORIAS C
     WHERE UPPER(C.NOMBRE) = UPPER(P_NOMBRE);

    RETURN V_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(
        -20142,
        'No existe categoria: ' || P_NOMBRE
      );
  END;

  FUNCTION GET_CONTENIDO_ID (
    P_TITULO IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID CONTENIDOS.ID_CONTENIDO%TYPE;
  BEGIN
    SELECT MIN(C.ID_CONTENIDO)
      INTO V_ID
      FROM CONTENIDOS C
     WHERE UPPER(C.TITULO) = UPPER(P_TITULO);

    IF V_ID IS NULL THEN
      RAISE_APPLICATION_ERROR(
        -20143,
        'No existe contenido: ' || P_TITULO
      );
    END IF;

    RETURN V_ID;
  END;

  FUNCTION GET_GENERO_ID (
    P_NOMBRE IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID GENEROS.ID_GENERO%TYPE;
  BEGIN
    SELECT G.ID_GENERO
      INTO V_ID
      FROM GENEROS G
     WHERE UPPER(G.NOMBRE) = UPPER(P_NOMBRE);

    RETURN V_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(
        -20144,
        'No existe genero: ' || P_NOMBRE
      );
  END;

  FUNCTION GET_DEPARTAMENTO_ID (
    P_NOMBRE IN VARCHAR2
  ) RETURN NUMBER
  IS
    V_ID DEPARTAMENTOS.ID_DEPARTAMENTO%TYPE;
  BEGIN
    SELECT D.ID_DEPARTAMENTO
      INTO V_ID
      FROM DEPARTAMENTOS D
     WHERE UPPER(D.NOMBRE) = UPPER(P_NOMBRE);

    RETURN V_ID;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
      RAISE_APPLICATION_ERROR(
        -20145,
        'No existe departamento: ' || P_NOMBRE
      );
  END;

  PROCEDURE UPSERT_PERFIL (
    P_EMAIL       IN VARCHAR2,
    P_NOMBRE      IN VARCHAR2,
    P_TIPO_PERFIL IN VARCHAR2
  )
  IS
    V_ID_USUARIO USUARIOS.ID_USUARIO%TYPE;
    V_EXISTE     NUMBER;
  BEGIN
    V_ID_USUARIO := GET_USUARIO_ID(P_EMAIL);

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM PERFILES P
     WHERE P.ID_USUARIO = V_ID_USUARIO
       AND UPPER(P.NOMBRE) = UPPER(P_NOMBRE);

    IF V_EXISTE = 0 THEN
      INSERT INTO PERFILES (
        ID_USUARIO,
        NOMBRE,
        TIPO_PERFIL
      ) VALUES (
        V_ID_USUARIO,
        P_NOMBRE,
        LOWER(P_TIPO_PERFIL)
      );
    END IF;
  END;

  PROCEDURE UPSERT_GENERO (
    P_NOMBRE      IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
  )
  IS
    V_ID GENEROS.ID_GENERO%TYPE;
  BEGIN
    BEGIN
      SELECT G.ID_GENERO
        INTO V_ID
        FROM GENEROS G
       WHERE UPPER(G.NOMBRE) = UPPER(P_NOMBRE);

      UPDATE GENEROS
         SET DESCRIPCION = P_DESCRIPCION
       WHERE ID_GENERO = V_ID;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO GENEROS (
          NOMBRE,
          DESCRIPCION
        ) VALUES (
          P_NOMBRE,
          P_DESCRIPCION
        );
    END;
  END;

  PROCEDURE UPSERT_CONTENIDO (
    P_TITULO          IN VARCHAR2,
    P_TIPO            IN VARCHAR2,
    P_ANIO            IN NUMBER,
    P_DURACION_MIN    IN NUMBER,
    P_SINOPSIS        IN VARCHAR2,
    P_CLASIFICACION   IN VARCHAR2,
    P_ES_EXCLUSIVO    IN NUMBER,
    P_CATEGORIA       IN VARCHAR2,
    P_PUBLICADOR_MAIL IN VARCHAR2
  )
  IS
    V_ID_CONTENIDO   CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_CATEGORIA   CATEGORIAS.ID_CATEGORIA%TYPE;
    V_ID_PUBLICADOR  USUARIOS.ID_USUARIO%TYPE;
  BEGIN
    V_ID_CATEGORIA := GET_CATEGORIA_ID(P_CATEGORIA);
    V_ID_PUBLICADOR := GET_USUARIO_ID(P_PUBLICADOR_MAIL);

    SELECT MIN(C.ID_CONTENIDO)
      INTO V_ID_CONTENIDO
      FROM CONTENIDOS C
     WHERE UPPER(C.TITULO) = UPPER(P_TITULO);

    IF V_ID_CONTENIDO IS NULL THEN
      INSERT INTO CONTENIDOS (
        TITULO,
        TIPO_CONTENIDO,
        ANIO_LANZAMIENTO,
        DURACION_MINUTOS,
        SINOPSIS,
        CLASIFICACION_EDAD,
        ES_EXCLUSIVO,
        ID_CATEGORIA,
        ID_EMPLEADO_PUBLICADOR
      ) VALUES (
        P_TITULO,
        LOWER(P_TIPO),
        P_ANIO,
        P_DURACION_MIN,
        P_SINOPSIS,
        UPPER(P_CLASIFICACION),
        P_ES_EXCLUSIVO,
        V_ID_CATEGORIA,
        V_ID_PUBLICADOR
      );
    ELSE
      UPDATE CONTENIDOS
         SET TIPO_CONTENIDO = LOWER(P_TIPO),
             ANIO_LANZAMIENTO = P_ANIO,
             DURACION_MINUTOS = P_DURACION_MIN,
             SINOPSIS = P_SINOPSIS,
             CLASIFICACION_EDAD = UPPER(P_CLASIFICACION),
             ES_EXCLUSIVO = P_ES_EXCLUSIVO,
             ID_CATEGORIA = V_ID_CATEGORIA,
             ID_EMPLEADO_PUBLICADOR = V_ID_PUBLICADOR
       WHERE ID_CONTENIDO = V_ID_CONTENIDO;
    END IF;
  END;

  PROCEDURE UPSERT_CONTENIDO_GENERO (
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_NOMBRE_GENERO    IN VARCHAR2
  )
  IS
    V_ID_CONTENIDO CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_GENERO    GENEROS.ID_GENERO%TYPE;
    V_EXISTE       NUMBER;
  BEGIN
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);
    V_ID_GENERO := GET_GENERO_ID(P_NOMBRE_GENERO);

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM CONTENIDOS_GENEROS CG
     WHERE CG.ID_CONTENIDO = V_ID_CONTENIDO
       AND CG.ID_GENERO = V_ID_GENERO;

    IF V_EXISTE = 0 THEN
      INSERT INTO CONTENIDOS_GENEROS (
        ID_CONTENIDO,
        ID_GENERO
      ) VALUES (
        V_ID_CONTENIDO,
        V_ID_GENERO
      );
    END IF;
  END;

  PROCEDURE UPSERT_TEMPORADA (
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_NUM_TEMPORADA    IN NUMBER,
    P_TITULO_TEMP      IN VARCHAR2,
    P_DESCRIPCION      IN VARCHAR2,
    P_FECHA_ESTRENO    IN DATE
  )
  IS
    V_ID_CONTENIDO CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_TEMPORADA TEMPORADAS.ID_TEMPORADA%TYPE;
  BEGIN
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    BEGIN
      SELECT T.ID_TEMPORADA
        INTO V_ID_TEMPORADA
        FROM TEMPORADAS T
       WHERE T.ID_CONTENIDO = V_ID_CONTENIDO
         AND T.NUMERO_TEMPORADA = P_NUM_TEMPORADA;

      UPDATE TEMPORADAS
         SET TITULO = P_TITULO_TEMP,
             DESCRIPCION = P_DESCRIPCION,
             FECHA_ESTRENO = P_FECHA_ESTRENO
       WHERE ID_TEMPORADA = V_ID_TEMPORADA;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO TEMPORADAS (
          ID_CONTENIDO,
          NUMERO_TEMPORADA,
          TITULO,
          DESCRIPCION,
          FECHA_ESTRENO
        ) VALUES (
          V_ID_CONTENIDO,
          P_NUM_TEMPORADA,
          P_TITULO_TEMP,
          P_DESCRIPCION,
          P_FECHA_ESTRENO
        );
    END;
  END;

  PROCEDURE UPSERT_EPISODIO (
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_NUM_TEMPORADA    IN NUMBER,
    P_NUM_EPISODIO     IN NUMBER,
    P_TITULO_EPISODIO  IN VARCHAR2,
    P_DURACION_MIN     IN NUMBER,
    P_SINOPSIS         IN VARCHAR2,
    P_FECHA_ESTRENO    IN DATE
  )
  IS
    V_ID_CONTENIDO CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_TEMPORADA TEMPORADAS.ID_TEMPORADA%TYPE;
    V_ID_EPISODIO  EPISODIOS.ID_EPISODIO%TYPE;
  BEGIN
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    SELECT T.ID_TEMPORADA
      INTO V_ID_TEMPORADA
      FROM TEMPORADAS T
     WHERE T.ID_CONTENIDO = V_ID_CONTENIDO
       AND T.NUMERO_TEMPORADA = P_NUM_TEMPORADA;

    BEGIN
      SELECT E.ID_EPISODIO
        INTO V_ID_EPISODIO
        FROM EPISODIOS E
       WHERE E.ID_TEMPORADA = V_ID_TEMPORADA
         AND E.NUMERO_EPISODIO = P_NUM_EPISODIO;

      UPDATE EPISODIOS
         SET TITULO = P_TITULO_EPISODIO,
             DURACION_MINUTOS = P_DURACION_MIN,
             SINOPSIS = P_SINOPSIS,
             FECHA_ESTRENO = P_FECHA_ESTRENO
       WHERE ID_EPISODIO = V_ID_EPISODIO;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO EPISODIOS (
          ID_TEMPORADA,
          NUMERO_EPISODIO,
          TITULO,
          DURACION_MINUTOS,
          SINOPSIS,
          FECHA_ESTRENO
        ) VALUES (
          V_ID_TEMPORADA,
          P_NUM_EPISODIO,
          P_TITULO_EPISODIO,
          P_DURACION_MIN,
          P_SINOPSIS,
          P_FECHA_ESTRENO
        );
    END;
  END;

  PROCEDURE UPSERT_RELACION_CONTENIDOS (
    P_TITULO_ORIGEN     IN VARCHAR2,
    P_TITULO_RELACION   IN VARCHAR2,
    P_TIPO_RELACION     IN VARCHAR2,
    P_DESCRIPCION       IN VARCHAR2
  )
  IS
    V_ID_ORIGEN     CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_RELACION   CONTENIDOS.ID_CONTENIDO%TYPE;
    V_EXISTE_DIRECTA NUMBER;
    V_EXISTE_INVERSA NUMBER;
  BEGIN
    V_ID_ORIGEN := GET_CONTENIDO_ID(P_TITULO_ORIGEN);
    V_ID_RELACION := GET_CONTENIDO_ID(P_TITULO_RELACION);

    SELECT COUNT(*)
      INTO V_EXISTE_DIRECTA
      FROM CONTENIDOS_RELACIONADOS CR
     WHERE CR.ID_CONTENIDO_ORIGEN = V_ID_ORIGEN
       AND CR.ID_CONTENIDO_RELACIONADO = V_ID_RELACION
       AND CR.TIPO_RELACION = UPPER(P_TIPO_RELACION);

    IF V_EXISTE_DIRECTA = 0 THEN
      SELECT COUNT(*)
        INTO V_EXISTE_INVERSA
        FROM CONTENIDOS_RELACIONADOS CR
       WHERE CR.ID_CONTENIDO_ORIGEN = V_ID_RELACION
         AND CR.ID_CONTENIDO_RELACIONADO = V_ID_ORIGEN
         AND CR.TIPO_RELACION = UPPER(P_TIPO_RELACION);

      IF V_EXISTE_INVERSA = 0 THEN
        INSERT INTO CONTENIDOS_RELACIONADOS (
          ID_CONTENIDO_ORIGEN,
          ID_CONTENIDO_RELACIONADO,
          TIPO_RELACION,
          DESCRIPCION
        ) VALUES (
          V_ID_ORIGEN,
          V_ID_RELACION,
          UPPER(P_TIPO_RELACION),
          P_DESCRIPCION
        );
      END IF;
    END IF;
  END;

  PROCEDURE UPSERT_DEPARTAMENTO (
    P_NOMBRE      IN VARCHAR2,
    P_DESCRIPCION IN VARCHAR2
  )
  IS
    V_EXISTE NUMBER;
  BEGIN
    SELECT COUNT(*)
      INTO V_EXISTE
      FROM DEPARTAMENTOS D
     WHERE UPPER(D.NOMBRE) = UPPER(P_NOMBRE);

    IF V_EXISTE = 0 THEN
      INSERT INTO DEPARTAMENTOS (NOMBRE, DESCRIPCION)
      VALUES (P_NOMBRE, P_DESCRIPCION);
    ELSE
      UPDATE DEPARTAMENTOS
         SET DESCRIPCION = P_DESCRIPCION
       WHERE UPPER(NOMBRE) = UPPER(P_NOMBRE);
    END IF;
  END;

  PROCEDURE UPSERT_EMPLEADO (
    P_EMAIL            IN VARCHAR2,
    P_DEPARTAMENTO     IN VARCHAR2,
    P_CARGO            IN VARCHAR2,
    P_ES_JEFE          IN NUMBER,
    P_SUPERVISOR_EMAIL IN VARCHAR2 DEFAULT NULL
  )
  IS
    V_ID_USUARIO      USUARIOS.ID_USUARIO%TYPE;
    V_ID_DEPTO        DEPARTAMENTOS.ID_DEPARTAMENTO%TYPE;
    V_ID_SUP_USUARIO  USUARIOS.ID_USUARIO%TYPE;
    V_ID_SUPERVISOR   EMPLEADOS.ID_EMPLEADO%TYPE;
    V_ID_EMPLEADO     EMPLEADOS.ID_EMPLEADO%TYPE;
  BEGIN
    V_ID_USUARIO := GET_USUARIO_ID(P_EMAIL);
    V_ID_DEPTO := GET_DEPARTAMENTO_ID(P_DEPARTAMENTO);

    IF P_SUPERVISOR_EMAIL IS NOT NULL THEN
      V_ID_SUP_USUARIO := GET_USUARIO_ID(P_SUPERVISOR_EMAIL);

      SELECT E.ID_EMPLEADO
        INTO V_ID_SUPERVISOR
        FROM EMPLEADOS E
       WHERE E.ID_USUARIO = V_ID_SUP_USUARIO;
    ELSE
      V_ID_SUPERVISOR := NULL;
    END IF;

    BEGIN
      SELECT E.ID_EMPLEADO
        INTO V_ID_EMPLEADO
        FROM EMPLEADOS E
       WHERE E.ID_USUARIO = V_ID_USUARIO;

      UPDATE EMPLEADOS
         SET ID_DEPARTAMENTO = V_ID_DEPTO,
             ID_SUPERVISOR = V_ID_SUPERVISOR,
             CARGO = P_CARGO,
             ES_JEFE = P_ES_JEFE,
             ESTADO_EMPLEADO = 'ACTIVO'
       WHERE ID_EMPLEADO = V_ID_EMPLEADO;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO EMPLEADOS (
          ID_USUARIO,
          ID_DEPARTAMENTO,
          ID_SUPERVISOR,
          CARGO,
          ES_JEFE,
          ESTADO_EMPLEADO
        ) VALUES (
          V_ID_USUARIO,
          V_ID_DEPTO,
          V_ID_SUPERVISOR,
          P_CARGO,
          P_ES_JEFE,
          'ACTIVO'
        );
    END;
  END;

  PROCEDURE UPSERT_REPRODUCCION (
    P_EMAIL            IN VARCHAR2,
    P_NOMBRE_PERFIL    IN VARCHAR2,
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_PROGRESO_SEG     IN NUMBER,
    P_DURACION_SEG     IN NUMBER,
    P_DISPOSITIVO      IN VARCHAR2,
    P_ESTADO           IN VARCHAR2
  )
  IS
    V_ID_PERFIL       PERFILES.ID_PERFIL%TYPE;
    V_ID_CONTENIDO    CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_REPRODUCCION REPRODUCCIONES.ID_REPRODUCCION%TYPE;
  BEGIN
    V_ID_PERFIL := GET_PERFIL_ID(P_EMAIL, P_NOMBRE_PERFIL);
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    SELECT MIN(R.ID_REPRODUCCION)
      INTO V_ID_REPRODUCCION
      FROM REPRODUCCIONES R
     WHERE R.ID_PERFIL = V_ID_PERFIL
       AND R.ID_CONTENIDO = V_ID_CONTENIDO
       AND UPPER(NVL(R.ULTIMO_DISPOSITIVO, 'NA')) = UPPER(NVL(P_DISPOSITIVO, 'NA'));

    IF V_ID_REPRODUCCION IS NULL THEN
      INSERT INTO REPRODUCCIONES (
        ID_PERFIL,
        ID_CONTENIDO,
        PROGRESO_SEGUNDOS,
        DURACION_TOTAL_SEGUNDOS,
        ULTIMO_DISPOSITIVO,
        ESTADO_REPRODUCCION
      ) VALUES (
        V_ID_PERFIL,
        V_ID_CONTENIDO,
        P_PROGRESO_SEG,
        P_DURACION_SEG,
        P_DISPOSITIVO,
        UPPER(P_ESTADO)
      );
    ELSE
      UPDATE REPRODUCCIONES
         SET PROGRESO_SEGUNDOS = P_PROGRESO_SEG,
             DURACION_TOTAL_SEGUNDOS = P_DURACION_SEG,
             ULTIMO_DISPOSITIVO = P_DISPOSITIVO,
             ESTADO_REPRODUCCION = UPPER(P_ESTADO)
       WHERE ID_REPRODUCCION = V_ID_REPRODUCCION;
    END IF;
  END;

  PROCEDURE UPSERT_FAVORITO (
    P_EMAIL            IN VARCHAR2,
    P_NOMBRE_PERFIL    IN VARCHAR2,
    P_TITULO_CONTENIDO IN VARCHAR2
  )
  IS
    V_ID_PERFIL    PERFILES.ID_PERFIL%TYPE;
    V_ID_CONTENIDO CONTENIDOS.ID_CONTENIDO%TYPE;
    V_EXISTE       NUMBER;
  BEGIN
    V_ID_PERFIL := GET_PERFIL_ID(P_EMAIL, P_NOMBRE_PERFIL);
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    SELECT COUNT(*)
      INTO V_EXISTE
      FROM FAVORITOS F
     WHERE F.ID_PERFIL = V_ID_PERFIL
       AND F.ID_CONTENIDO = V_ID_CONTENIDO;

    IF V_EXISTE = 0 THEN
      INSERT INTO FAVORITOS (
        ID_PERFIL,
        ID_CONTENIDO
      ) VALUES (
        V_ID_PERFIL,
        V_ID_CONTENIDO
      );
    END IF;
  END;

  PROCEDURE UPSERT_CALIFICACION (
    P_EMAIL            IN VARCHAR2,
    P_NOMBRE_PERFIL    IN VARCHAR2,
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_PUNTAJE          IN NUMBER,
    P_RESENA           IN VARCHAR2
  )
  IS
    V_ID_PERFIL       PERFILES.ID_PERFIL%TYPE;
    V_ID_CONTENIDO    CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_CALIFICACION CALIFICACIONES.ID_CALIFICACION%TYPE;
  BEGIN
    V_ID_PERFIL := GET_PERFIL_ID(P_EMAIL, P_NOMBRE_PERFIL);
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    BEGIN
      SELECT C.ID_CALIFICACION
        INTO V_ID_CALIFICACION
        FROM CALIFICACIONES C
       WHERE C.ID_PERFIL = V_ID_PERFIL
         AND C.ID_CONTENIDO = V_ID_CONTENIDO;

      UPDATE CALIFICACIONES
         SET PUNTAJE = P_PUNTAJE,
             RESENA = P_RESENA
       WHERE ID_CALIFICACION = V_ID_CALIFICACION;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO CALIFICACIONES (
          ID_PERFIL,
          ID_CONTENIDO,
          PUNTAJE,
          RESENA
        ) VALUES (
          V_ID_PERFIL,
          V_ID_CONTENIDO,
          P_PUNTAJE,
          P_RESENA
        );
    END;
  END;

  PROCEDURE UPSERT_REPORTE (
    P_EMAIL_REPORTADOR IN VARCHAR2,
    P_NOMBRE_PERFIL    IN VARCHAR2,
    P_TITULO_CONTENIDO IN VARCHAR2,
    P_MOTIVO           IN VARCHAR2,
    P_DETALLE          IN VARCHAR2,
    P_ESTADO           IN VARCHAR2,
    P_EMAIL_MODERADOR  IN VARCHAR2 DEFAULT NULL,
    P_RESOLUCION       IN VARCHAR2 DEFAULT NULL
  )
  IS
    V_ID_PERFIL       PERFILES.ID_PERFIL%TYPE;
    V_ID_CONTENIDO    CONTENIDOS.ID_CONTENIDO%TYPE;
    V_ID_MODERADOR    USUARIOS.ID_USUARIO%TYPE;
    V_ID_REPORTE      REPORTES.ID_REPORTE%TYPE;
  BEGIN
    V_ID_PERFIL := GET_PERFIL_ID(P_EMAIL_REPORTADOR, P_NOMBRE_PERFIL);
    V_ID_CONTENIDO := GET_CONTENIDO_ID(P_TITULO_CONTENIDO);

    IF P_EMAIL_MODERADOR IS NOT NULL THEN
      V_ID_MODERADOR := GET_USUARIO_ID(P_EMAIL_MODERADOR);
    ELSE
      V_ID_MODERADOR := NULL;
    END IF;

    BEGIN
      SELECT R.ID_REPORTE
        INTO V_ID_REPORTE
        FROM REPORTES R
       WHERE UPPER(NVL(R.DETALLE, 'NA')) = UPPER(NVL(P_DETALLE, 'NA'));

      UPDATE REPORTES
         SET ID_PERFIL_REPORTADOR = V_ID_PERFIL,
             ID_CONTENIDO = V_ID_CONTENIDO,
             MOTIVO = P_MOTIVO,
             DETALLE = P_DETALLE,
             ESTADO_REPORTE = UPPER(P_ESTADO),
             ID_USUARIO_MODERADOR = V_ID_MODERADOR,
             RESOLUCION = P_RESOLUCION
       WHERE ID_REPORTE = V_ID_REPORTE;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO REPORTES (
          ID_PERFIL_REPORTADOR,
          ID_CONTENIDO,
          MOTIVO,
          DETALLE,
          ESTADO_REPORTE,
          ID_USUARIO_MODERADOR,
          RESOLUCION
        ) VALUES (
          V_ID_PERFIL,
          V_ID_CONTENIDO,
          P_MOTIVO,
          P_DETALLE,
          UPPER(P_ESTADO),
          V_ID_MODERADOR,
          P_RESOLUCION
        );
    END;
  END;

  PROCEDURE UPSERT_REFERIDO (
    P_EMAIL_REFERENTE IN VARCHAR2,
    P_EMAIL_REFERIDO  IN VARCHAR2,
    P_ESTADO          IN VARCHAR2,
    P_DESCUENTO_PCT   IN NUMBER
  )
  IS
    V_ID_REFERENTE REFERIDOS.ID_USUARIO_REFERENTE%TYPE;
    V_ID_REFERIDO  REFERIDOS.ID_USUARIO_REFERIDO%TYPE;
    V_ID_REF_ROW   REFERIDOS.ID_REFERIDO%TYPE;
  BEGIN
    V_ID_REFERENTE := GET_USUARIO_ID(P_EMAIL_REFERENTE);
    V_ID_REFERIDO := GET_USUARIO_ID(P_EMAIL_REFERIDO);

    IF V_ID_REFERENTE = V_ID_REFERIDO THEN
      RAISE_APPLICATION_ERROR(-20146, 'Referente y referido no pueden ser el mismo usuario');
    END IF;

    BEGIN
      SELECT R.ID_REFERIDO
        INTO V_ID_REF_ROW
        FROM REFERIDOS R
       WHERE R.ID_USUARIO_REFERIDO = V_ID_REFERIDO;

      UPDATE REFERIDOS
         SET ID_USUARIO_REFERENTE = V_ID_REFERENTE,
             ESTADO_REFERIDO = UPPER(P_ESTADO),
             DESCUENTO_PCT = P_DESCUENTO_PCT,
             FECHA_REFERIDO = CURRENT_TIMESTAMP
       WHERE ID_REFERIDO = V_ID_REF_ROW;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO REFERIDOS (
          ID_USUARIO_REFERENTE,
          ID_USUARIO_REFERIDO,
          ESTADO_REFERIDO,
          DESCUENTO_PCT
        ) VALUES (
          V_ID_REFERENTE,
          V_ID_REFERIDO,
          UPPER(P_ESTADO),
          P_DESCUENTO_PCT
        );
    END;
  END;

  PROCEDURE UPSERT_FACTURA (
    P_EMAIL          IN VARCHAR2,
    P_ANIO           IN NUMBER,
    P_MES            IN NUMBER,
    P_FECHA_CORTE    IN DATE,
    P_FECHA_VENC     IN DATE,
    P_MONTO_BASE     IN NUMBER,
    P_DESC_REF       IN NUMBER,
    P_DESC_FID       IN NUMBER,
    P_ESTADO_FACTURA IN VARCHAR2
  )
  IS
    V_ID_USUARIO   USUARIOS.ID_USUARIO%TYPE;
    V_ID_FACTURA   FACTURACIONES.ID_FACTURACION%TYPE;
  BEGIN
    V_ID_USUARIO := GET_USUARIO_ID(P_EMAIL);

    BEGIN
      SELECT F.ID_FACTURACION
        INTO V_ID_FACTURA
        FROM FACTURACIONES F
       WHERE F.ID_USUARIO = V_ID_USUARIO
         AND F.PERIODO_ANIO = P_ANIO
         AND F.PERIODO_MES = P_MES;

      UPDATE FACTURACIONES
         SET FECHA_CORTE = P_FECHA_CORTE,
             FECHA_VENCIMIENTO = P_FECHA_VENC,
             MONTO_BASE = P_MONTO_BASE,
             DESCUENTO_REFERIDOS_PCT = P_DESC_REF,
             DESCUENTO_FIDELIDAD_PCT = P_DESC_FID,
             ESTADO_FACTURA = UPPER(P_ESTADO_FACTURA)
       WHERE ID_FACTURACION = V_ID_FACTURA;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO FACTURACIONES (
          ID_USUARIO,
          PERIODO_ANIO,
          PERIODO_MES,
          FECHA_CORTE,
          FECHA_VENCIMIENTO,
          MONTO_BASE,
          DESCUENTO_REFERIDOS_PCT,
          DESCUENTO_FIDELIDAD_PCT,
          MONTO_FINAL,
          ESTADO_FACTURA
        ) VALUES (
          V_ID_USUARIO,
          P_ANIO,
          P_MES,
          P_FECHA_CORTE,
          P_FECHA_VENC,
          P_MONTO_BASE,
          P_DESC_REF,
          P_DESC_FID,
          P_MONTO_BASE,
          UPPER(P_ESTADO_FACTURA)
        );
    END;
  END;

  PROCEDURE UPSERT_PAGO (
    P_REFERENCIA   IN VARCHAR2,
    P_EMAIL        IN VARCHAR2,
    P_ANIO         IN NUMBER,
    P_MES          IN NUMBER,
    P_MONTO        IN NUMBER,
    P_METODO       IN VARCHAR2,
    P_ESTADO       IN VARCHAR2
  )
  IS
    V_ID_USUARIO   USUARIOS.ID_USUARIO%TYPE;
    V_ID_FACTURA   FACTURACIONES.ID_FACTURACION%TYPE;
    V_ID_PAGO      PAGOS.ID_PAGO%TYPE;
  BEGIN
    V_ID_USUARIO := GET_USUARIO_ID(P_EMAIL);

    SELECT F.ID_FACTURACION
      INTO V_ID_FACTURA
      FROM FACTURACIONES F
     WHERE F.ID_USUARIO = V_ID_USUARIO
       AND F.PERIODO_ANIO = P_ANIO
       AND F.PERIODO_MES = P_MES;

    BEGIN
      SELECT P.ID_PAGO
        INTO V_ID_PAGO
        FROM PAGOS P
       WHERE UPPER(NVL(P.REFERENCIA_PAGO, 'NA')) = UPPER(NVL(P_REFERENCIA, 'NA'));

      UPDATE PAGOS
         SET ID_FACTURACION = V_ID_FACTURA,
             ID_USUARIO = V_ID_USUARIO,
             MONTO = P_MONTO,
             METODO_PAGO = UPPER(P_METODO),
             ESTADO_TRANSACCION = UPPER(P_ESTADO)
       WHERE ID_PAGO = V_ID_PAGO;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        INSERT INTO PAGOS (
          ID_FACTURACION,
          ID_USUARIO,
          MONTO,
          METODO_PAGO,
          ESTADO_TRANSACCION,
          REFERENCIA_PAGO
        ) VALUES (
          V_ID_FACTURA,
          V_ID_USUARIO,
          P_MONTO,
          UPPER(P_METODO),
          UPPER(P_ESTADO),
          P_REFERENCIA
        );
    END;

    IF UPPER(P_ESTADO) = 'EXITOSO' THEN
      UPDATE FACTURACIONES
         SET ESTADO_FACTURA = 'PAGADA',
             FECHA_PAGO = NVL(FECHA_PAGO, CURRENT_TIMESTAMP)
       WHERE ID_FACTURACION = V_ID_FACTURA;

      UPDATE USUARIOS
         SET ESTADO_CUENTA = 'ACTIVO'
       WHERE ID_USUARIO = V_ID_USUARIO;
    END IF;
  END;

BEGIN
  -- 1) Perfiles extra para pruebas de clasificacion infantil.
  UPSERT_PERFIL(C_EMAIL_USUARIO, 'Usuario Infantil', 'infantil');

  -- 2) Generos base para cobertura de catalogo extendido.
  UPSERT_GENERO('Accion', 'Genero con ritmo alto y conflictos constantes.');
  UPSERT_GENERO('Drama', 'Historias emocionales centradas en personajes.');
  UPSERT_GENERO('Suspenso', 'Narrativas de tension, misterio y riesgo.');
  UPSERT_GENERO('Tecnologia', 'Contenido sobre tecnologia y transformacion digital.');
  UPSERT_GENERO('Investigacion', 'Contenido basado en analisis y evidencia.');
  UPSERT_GENERO('Educativo', 'Contenido orientado a aprendizaje guiado.');
  UPSERT_GENERO('Infantil', 'Contenido apto para audiencias de corta edad.');
  UPSERT_GENERO('Ciencia Ficcion', 'Narrativas especulativas sobre ciencia y futuro.');

  -- 3) Contenidos nuevos para seed funcional.
  UPSERT_CONTENIDO(
    P_TITULO => 'SEED14 - Horizonte Andino',
    P_TIPO => 'documental',
    P_ANIO => 2025,
    P_DURACION_MIN => 96,
    P_SINOPSIS => 'Exploracion de ecosistemas de alta montana y comunidades locales.',
    P_CLASIFICACION => '+7',
    P_ES_EXCLUSIVO => 1,
    P_CATEGORIA => 'Documental',
    P_PUBLICADOR_MAIL => C_EMAIL_CONTENIDO
  );

  UPSERT_CONTENIDO(
    P_TITULO => 'SEED14 - Norte Incierto Cero',
    P_TIPO => 'serie',
    P_ANIO => 2025,
    P_DURACION_MIN => 48,
    P_SINOPSIS => 'Precuela que muestra los eventos previos a Norte Incierto.',
    P_CLASIFICACION => '+13',
    P_ES_EXCLUSIVO => 0,
    P_CATEGORIA => 'Drama',
    P_PUBLICADOR_MAIL => C_EMAIL_CONTENIDO
  );

  UPSERT_CONTENIDO(
    P_TITULO => 'SEED14 - Codigo en Conversacion IA',
    P_TIPO => 'podcast',
    P_ANIO => 2026,
    P_DURACION_MIN => 55,
    P_SINOPSIS => 'Conversaciones tecnicas sobre IA aplicada a productos digitales.',
    P_CLASIFICACION => 'TP',
    P_ES_EXCLUSIVO => 0,
    P_CATEGORIA => 'Podcast',
    P_PUBLICADOR_MAIL => C_EMAIL_CONTENIDO
  );

  -- 4) Relacion N:M de contenidos con generos.
  UPSERT_CONTENIDO_GENERO('SEED14 - Horizonte Andino', 'Investigacion');
  UPSERT_CONTENIDO_GENERO('SEED14 - Horizonte Andino', 'Educativo');
  UPSERT_CONTENIDO_GENERO('SEED14 - Norte Incierto Cero', 'Drama');
  UPSERT_CONTENIDO_GENERO('SEED14 - Norte Incierto Cero', 'Suspenso');
  UPSERT_CONTENIDO_GENERO('SEED14 - Codigo en Conversacion IA', 'Tecnologia');

  -- 5) Temporadas y episodios para serie/podcast.
  UPSERT_TEMPORADA(
    P_TITULO_CONTENIDO => 'SEED14 - Norte Incierto Cero',
    P_NUM_TEMPORADA => 1,
    P_TITULO_TEMP => 'Temporada 1 - Origenes',
    P_DESCRIPCION => 'Primer arco narrativo de la precuela.',
    P_FECHA_ESTRENO => DATE '2025-02-15'
  );

  UPSERT_EPISODIO(
    P_TITULO_CONTENIDO => 'SEED14 - Norte Incierto Cero',
    P_NUM_TEMPORADA => 1,
    P_NUM_EPISODIO => 1,
    P_TITULO_EPISODIO => 'Frontera de Humo',
    P_DURACION_MIN => 48,
    P_SINOPSIS => 'Inicio del conflicto en la frontera norte.',
    P_FECHA_ESTRENO => DATE '2025-02-15'
  );

  UPSERT_EPISODIO(
    P_TITULO_CONTENIDO => 'SEED14 - Norte Incierto Cero',
    P_NUM_TEMPORADA => 1,
    P_NUM_EPISODIO => 2,
    P_TITULO_EPISODIO => 'Linea de Silencio',
    P_DURACION_MIN => 47,
    P_SINOPSIS => 'Los protagonistas siguen una pista de alto riesgo.',
    P_FECHA_ESTRENO => DATE '2025-02-22'
  );

  UPSERT_TEMPORADA(
    P_TITULO_CONTENIDO => 'SEED14 - Codigo en Conversacion IA',
    P_NUM_TEMPORADA => 1,
    P_TITULO_TEMP => 'Temporada 1 - IA Aplicada',
    P_DESCRIPCION => 'Temporada inicial de conversaciones tecnicas.',
    P_FECHA_ESTRENO => DATE '2026-01-10'
  );

  UPSERT_EPISODIO(
    P_TITULO_CONTENIDO => 'SEED14 - Codigo en Conversacion IA',
    P_NUM_TEMPORADA => 1,
    P_NUM_EPISODIO => 1,
    P_TITULO_EPISODIO => 'Modelos Fundacionales',
    P_DURACION_MIN => 54,
    P_SINOPSIS => 'Conceptos base para integrar IA en productos.',
    P_FECHA_ESTRENO => DATE '2026-01-10'
  );

  UPSERT_EPISODIO(
    P_TITULO_CONTENIDO => 'SEED14 - Codigo en Conversacion IA',
    P_NUM_TEMPORADA => 1,
    P_NUM_EPISODIO => 2,
    P_TITULO_EPISODIO => 'MLOps para Equipos Pequenos',
    P_DURACION_MIN => 55,
    P_SINOPSIS => 'Patrones operativos para despliegue y monitoreo.',
    P_FECHA_ESTRENO => DATE '2026-01-17'
  );

  -- 6) Relacion de contenidos para navegacion editorial.
  UPSERT_RELACION_CONTENIDOS(
    P_TITULO_ORIGEN => 'Norte Incierto',
    P_TITULO_RELACION => 'SEED14 - Norte Incierto Cero',
    P_TIPO_RELACION => 'PRECUELA',
    P_DESCRIPCION => 'Historia previa de los eventos de la serie principal.'
  );

  -- 7) Estructura organizacional y empleados.
  UPSERT_DEPARTAMENTO('Tecnologia', 'Desarrollo de plataforma y operacion tecnica.');
  UPSERT_DEPARTAMENTO('Contenido', 'Curaduria y publicacion del catalogo multimedia.');
  UPSERT_DEPARTAMENTO('Soporte', 'Atencion al usuario y moderacion de reportes.');

  UPSERT_EMPLEADO(
    P_EMAIL => C_EMAIL_ADMIN,
    P_DEPARTAMENTO => 'Tecnologia',
    P_CARGO => 'Director de Tecnologia',
    P_ES_JEFE => 1,
    P_SUPERVISOR_EMAIL => NULL
  );

  UPSERT_EMPLEADO(
    P_EMAIL => C_EMAIL_ANALISTA,
    P_DEPARTAMENTO => 'Tecnologia',
    P_CARGO => 'Analista de Datos',
    P_ES_JEFE => 0,
    P_SUPERVISOR_EMAIL => C_EMAIL_ADMIN
  );

  UPSERT_EMPLEADO(
    P_EMAIL => C_EMAIL_CONTENIDO,
    P_DEPARTAMENTO => 'Contenido',
    P_CARGO => 'Editor Senior de Catalogo',
    P_ES_JEFE => 1,
    P_SUPERVISOR_EMAIL => NULL
  );

  UPSERT_EMPLEADO(
    P_EMAIL => C_EMAIL_SOPORTE,
    P_DEPARTAMENTO => 'Soporte',
    P_CARGO => 'Lider de Moderacion',
    P_ES_JEFE => 1,
    P_SUPERVISOR_EMAIL => NULL
  );

  -- 8) Reproducciones con avance > 50% para habilitar calificaciones.
  UPSERT_REPRODUCCION(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Demo',
    P_TITULO_CONTENIDO => 'La Ciudad de las Sombras',
    P_PROGRESO_SEG => 5200,
    P_DURACION_SEG => 7080,
    P_DISPOSITIVO => C_PREFIJO_SEED || '-TV',
    P_ESTADO => 'PAUSADO'
  );

  UPSERT_REPRODUCCION(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Infantil',
    P_TITULO_CONTENIDO => 'Aventuras en Neblina',
    P_PROGRESO_SEG => 3000,
    P_DURACION_SEG => 5280,
    P_DISPOSITIVO => C_PREFIJO_SEED || '-TABLET',
    P_ESTADO => 'EN_PROGRESO'
  );

  UPSERT_REPRODUCCION(
    P_EMAIL => C_EMAIL_ANALISTA,
    P_NOMBRE_PERFIL => 'Analista BI',
    P_TITULO_CONTENIDO => 'SEED14 - Horizonte Andino',
    P_PROGRESO_SEG => 3900,
    P_DURACION_SEG => 5760,
    P_DISPOSITIVO => C_PREFIJO_SEED || '-WEB',
    P_ESTADO => 'EN_PROGRESO'
  );

  -- 9) Favoritos por perfil.
  UPSERT_FAVORITO(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Demo',
    P_TITULO_CONTENIDO => 'SEED14 - Norte Incierto Cero'
  );

  UPSERT_FAVORITO(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Infantil',
    P_TITULO_CONTENIDO => 'Aventuras en Neblina'
  );

  UPSERT_FAVORITO(
    P_EMAIL => C_EMAIL_ANALISTA,
    P_NOMBRE_PERFIL => 'Analista BI',
    P_TITULO_CONTENIDO => 'SEED14 - Horizonte Andino'
  );

  -- 10) Calificaciones con regla de retencion cumplida.
  UPSERT_CALIFICACION(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Demo',
    P_TITULO_CONTENIDO => 'La Ciudad de las Sombras',
    P_PUNTAJE => 5,
    P_RESENA => C_PREFIJO_SEED || ' - Excelente ritmo narrativo y produccion.'
  );

  UPSERT_CALIFICACION(
    P_EMAIL => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Infantil',
    P_TITULO_CONTENIDO => 'Aventuras en Neblina',
    P_PUNTAJE => 4,
    P_RESENA => C_PREFIJO_SEED || ' - Aventura clara y apropiada para perfil infantil.'
  );

  UPSERT_CALIFICACION(
    P_EMAIL => C_EMAIL_ANALISTA,
    P_NOMBRE_PERFIL => 'Analista BI',
    P_TITULO_CONTENIDO => 'SEED14 - Horizonte Andino',
    P_PUNTAJE => 4,
    P_RESENA => C_PREFIJO_SEED || ' - Buen equilibrio entre datos y narrativa.'
  );

  -- 11) Reportes y moderacion.
  UPSERT_REPORTE(
    P_EMAIL_REPORTADOR => C_EMAIL_USUARIO,
    P_NOMBRE_PERFIL => 'Usuario Demo',
    P_TITULO_CONTENIDO => 'SEED14 - Norte Incierto Cero',
    P_MOTIVO => 'SINOPSIS_INCOMPLETA',
    P_DETALLE => '[' || C_PREFIJO_SEED || '] REPORTE_ABIERTO_001',
    P_ESTADO => 'ABIERTO',
    P_EMAIL_MODERADOR => NULL,
    P_RESOLUCION => NULL
  );

  UPSERT_REPORTE(
    P_EMAIL_REPORTADOR => C_EMAIL_ANALISTA,
    P_NOMBRE_PERFIL => 'Analista BI',
    P_TITULO_CONTENIDO => 'SEED14 - Horizonte Andino',
    P_MOTIVO => 'METADATOS',
    P_DETALLE => '[' || C_PREFIJO_SEED || '] REPORTE_RESUELTO_001',
    P_ESTADO => 'RESUELTO',
    P_EMAIL_MODERADOR => C_EMAIL_SOPORTE,
    P_RESOLUCION => 'Metadata editorial corregida y validada por soporte.'
  );

  -- 12) Referidos y facturacion.
  UPSERT_REFERIDO(
    P_EMAIL_REFERENTE => C_EMAIL_ADMIN,
    P_EMAIL_REFERIDO => C_EMAIL_USUARIO,
    P_ESTADO => 'VALIDADO',
    P_DESCUENTO_PCT => 10
  );

  UPSERT_FACTURA(
    P_EMAIL => C_EMAIL_USUARIO,
    P_ANIO => 2026,
    P_MES => 4,
    P_FECHA_CORTE => DATE '2026-04-01',
    P_FECHA_VENC => DATE '2026-04-30',
    P_MONTO_BASE => 14900,
    P_DESC_REF => 10,
    P_DESC_FID => 0,
    P_ESTADO_FACTURA => 'PENDIENTE'
  );

  UPSERT_PAGO(
    P_REFERENCIA => C_PREFIJO_SEED || '-PAGO-2026-04-USUARIO',
    P_EMAIL => C_EMAIL_USUARIO,
    P_ANIO => 2026,
    P_MES => 4,
    P_MONTO => 13410,
    P_METODO => 'PSE',
    P_ESTADO => 'EXITOSO'
  );

  UPSERT_FACTURA(
    P_EMAIL => C_EMAIL_ANALISTA,
    P_ANIO => 2026,
    P_MES => 4,
    P_FECHA_CORTE => DATE '2026-04-01',
    P_FECHA_VENC => DATE '2026-04-30',
    P_MONTO_BASE => 24900,
    P_DESC_REF => 0,
    P_DESC_FID => 0,
    P_ESTADO_FACTURA => 'PENDIENTE'
  );

  COMMIT;

  SELECT COUNT(*)
    INTO V_CNT_CONTENIDOS_SEED
    FROM CONTENIDOS C
   WHERE UPPER(C.TITULO) LIKE UPPER(C_PREFIJO_SEED || ' - %');

  SELECT COUNT(*)
    INTO V_CNT_REPORTE_SEED
    FROM REPORTES R
   WHERE UPPER(NVL(R.DETALLE, 'NA')) LIKE UPPER('%[' || C_PREFIJO_SEED || ']%');

  SELECT COUNT(*)
    INTO V_CNT_PAGO_SEED
    FROM PAGOS P
   WHERE UPPER(NVL(P.REFERENCIA_PAGO, 'NA')) LIKE UPPER(C_PREFIJO_SEED || '-PAGO%');

  DBMS_OUTPUT.PUT_LINE('Seed extra finalizado.');
  DBMS_OUTPUT.PUT_LINE('Contenidos seed ' || C_PREFIJO_SEED || ': ' || V_CNT_CONTENIDOS_SEED);
  DBMS_OUTPUT.PUT_LINE('Reportes seed ' || C_PREFIJO_SEED || ': ' || V_CNT_REPORTE_SEED);
  DBMS_OUTPUT.PUT_LINE('Pagos seed ' || C_PREFIJO_SEED || ': ' || V_CNT_PAGO_SEED);
END;
/

-- ============================================================================
-- Consultas de validacion sugeridas (ejecutar despues del bloque):
-- ============================================================================
-- 1) Contenidos creados por seed:
-- SELECT ID_CONTENIDO, TITULO, TIPO_CONTENIDO, CLASIFICACION_EDAD
--   FROM CONTENIDOS
--  WHERE UPPER(TITULO) LIKE 'SEED14 - %'
--  ORDER BY ID_CONTENIDO;
--
-- 2) Temporadas y episodios seed:
-- SELECT C.TITULO, T.NUMERO_TEMPORADA, E.NUMERO_EPISODIO, E.TITULO AS TITULO_EPISODIO
--   FROM CONTENIDOS C
--   JOIN TEMPORADAS T ON T.ID_CONTENIDO = C.ID_CONTENIDO
--   JOIN EPISODIOS E ON E.ID_TEMPORADA = T.ID_TEMPORADA
--  WHERE UPPER(C.TITULO) LIKE 'SEED14 - %'
--  ORDER BY C.TITULO, T.NUMERO_TEMPORADA, E.NUMERO_EPISODIO;
--
-- 3) Reproducciones con porcentaje recalculado por trigger:
-- SELECT R.ID_REPRODUCCION, P.NOMBRE AS PERFIL, C.TITULO,
--        R.PROGRESO_SEGUNDOS, R.DURACION_TOTAL_SEGUNDOS, R.PORCENTAJE_AVANCE, R.ESTADO_REPRODUCCION
--   FROM REPRODUCCIONES R
--   JOIN PERFILES P ON P.ID_PERFIL = R.ID_PERFIL
--   JOIN CONTENIDOS C ON C.ID_CONTENIDO = R.ID_CONTENIDO
--  WHERE UPPER(R.ULTIMO_DISPOSITIVO) LIKE 'SEED14-%'
--  ORDER BY R.ID_REPRODUCCION;
--
-- 4) Calificaciones y favoritos seed:
-- SELECT P.NOMBRE AS PERFIL, C.TITULO, CA.PUNTAJE, CA.RESENA
--   FROM CALIFICACIONES CA
--   JOIN PERFILES P ON P.ID_PERFIL = CA.ID_PERFIL
--   JOIN CONTENIDOS C ON C.ID_CONTENIDO = CA.ID_CONTENIDO
--  WHERE UPPER(CA.RESENA) LIKE 'SEED14%'
--  ORDER BY P.NOMBRE, C.TITULO;
--
-- SELECT P.NOMBRE AS PERFIL, C.TITULO, F.FECHA_ADICION
--   FROM FAVORITOS F
--   JOIN PERFILES P ON P.ID_PERFIL = F.ID_PERFIL
--   JOIN CONTENIDOS C ON C.ID_CONTENIDO = F.ID_CONTENIDO
--  WHERE C.TITULO LIKE 'SEED14 - %' OR P.NOMBRE = 'Usuario Infantil'
--  ORDER BY F.FECHA_ADICION DESC;
--
-- 5) Reportes seed y estado de moderacion:
-- SELECT R.ID_REPORTE, R.DETALLE, R.ESTADO_REPORTE, U.EMAIL AS MODERADOR, R.FECHA_RESOLUCION
--   FROM REPORTES R
--   LEFT JOIN USUARIOS U ON U.ID_USUARIO = R.ID_USUARIO_MODERADOR
--  WHERE UPPER(NVL(R.DETALLE, 'NA')) LIKE '%[SEED14]%'
--  ORDER BY R.ID_REPORTE;
--
-- 6) Referidos, facturas y pagos seed:
-- SELECT RE.ID_REFERIDO, UR.EMAIL AS REFERENTE, UE.EMAIL AS REFERIDO, RE.ESTADO_REFERIDO, RE.DESCUENTO_PCT
--   FROM REFERIDOS RE
--   JOIN USUARIOS UR ON UR.ID_USUARIO = RE.ID_USUARIO_REFERENTE
--   JOIN USUARIOS UE ON UE.ID_USUARIO = RE.ID_USUARIO_REFERIDO
--  WHERE UE.EMAIL IN ('usuario.seed@minflix.local')
--  ORDER BY RE.ID_REFERIDO;
--
-- SELECT F.ID_FACTURACION, U.EMAIL, F.PERIODO_ANIO, F.PERIODO_MES, F.MONTO_BASE,
--        F.DESCUENTO_REFERIDOS_PCT, F.DESCUENTO_FIDELIDAD_PCT, F.MONTO_FINAL, F.ESTADO_FACTURA
--   FROM FACTURACIONES F
--   JOIN USUARIOS U ON U.ID_USUARIO = F.ID_USUARIO
--  WHERE U.EMAIL IN ('usuario.seed@minflix.local', 'analista.seed@minflix.local')
--    AND F.PERIODO_ANIO = 2026
--    AND F.PERIODO_MES = 4
--  ORDER BY U.EMAIL;
--
-- SELECT P.ID_PAGO, U.EMAIL, P.MONTO, P.METODO_PAGO, P.ESTADO_TRANSACCION, P.REFERENCIA_PAGO
--   FROM PAGOS P
--   JOIN USUARIOS U ON U.ID_USUARIO = P.ID_USUARIO
--  WHERE UPPER(NVL(P.REFERENCIA_PAGO, 'NA')) LIKE 'SEED14-PAGO%'
--  ORDER BY P.ID_PAGO;
