-- ============================================================================
-- MinFlix - Iteracion 6 (Finanzas API Read Models)
-- Ejecutar como owner de tablas (SYSTEM en entorno actual).
-- Requiere: scripts 01..14 aplicados.
-- Objetivo:
--   1) Crear vistas de lectura para endpoints financieros.
--   2) Agregar indice por periodo para acelerar historial de facturas.
-- ============================================================================

DECLARE
  V_EXISTE NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO V_EXISTE
    FROM USER_INDEXES
   WHERE INDEX_NAME = 'IDX_FACTURACIONES_USR_PERIODO';

  IF V_EXISTE = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE INDEX IDX_FACTURACIONES_USR_PERIODO
          ON FACTURACIONES (
            ID_USUARIO,
            PERIODO_ANIO DESC,
            PERIODO_MES DESC,
            FECHA_CORTE DESC
          )';
  END IF;
END;
/

CREATE OR REPLACE VIEW VW_FIN_RESUMEN_USUARIO AS
SELECT
  U.ID_USUARIO,
  U.EMAIL,
  U.ESTADO_CUENTA,
  (
    SELECT COUNT(*)
      FROM FACTURACIONES F
     WHERE F.ID_USUARIO = U.ID_USUARIO
  ) AS TOTAL_FACTURAS,
  (
    SELECT COUNT(*)
      FROM FACTURACIONES F
     WHERE F.ID_USUARIO = U.ID_USUARIO
       AND F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
  ) AS FACTURAS_PENDIENTES_VENCIDAS,
  (
    SELECT NVL(SUM(P.MONTO), 0)
      FROM PAGOS P
     WHERE P.ID_USUARIO = U.ID_USUARIO
       AND P.ESTADO_TRANSACCION = 'EXITOSO'
  ) AS TOTAL_PAGADO_EXITOSO,
  (
    SELECT NVL(MAX(R.DESCUENTO_PCT), 0)
      FROM REFERIDOS R
     WHERE (R.ID_USUARIO_REFERENTE = U.ID_USUARIO
        OR R.ID_USUARIO_REFERIDO = U.ID_USUARIO)
       AND R.ESTADO_REFERIDO = 'VALIDADO'
  ) AS DESCUENTO_REFERIDOS_ACTIVO_PCT,
  (
    SELECT MAX(F.ID_FACTURACION)
      KEEP (DENSE_RANK LAST ORDER BY F.PERIODO_ANIO, F.PERIODO_MES, F.FECHA_CORTE)
      FROM FACTURACIONES F
     WHERE F.ID_USUARIO = U.ID_USUARIO
  ) AS ID_FACTURA_VIGENTE
FROM USUARIOS U;

CREATE OR REPLACE VIEW VW_FIN_FACTURAS_DETALLE AS
SELECT
  F.ID_FACTURACION,
  F.ID_USUARIO,
  U.EMAIL AS USUARIO_EMAIL,
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  F.FECHA_CORTE,
  F.FECHA_VENCIMIENTO,
  F.MONTO_BASE,
  F.DESCUENTO_REFERIDOS_PCT,
  F.DESCUENTO_FIDELIDAD_PCT,
  F.MONTO_FINAL,
  F.ESTADO_FACTURA,
  F.FECHA_PAGO
FROM FACTURACIONES F
JOIN USUARIOS U
  ON U.ID_USUARIO = F.ID_USUARIO;

CREATE OR REPLACE VIEW VW_FIN_PAGOS_DETALLE AS
SELECT
  P.ID_PAGO,
  P.ID_FACTURACION,
  P.ID_USUARIO,
  U.EMAIL AS USUARIO_EMAIL,
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  P.FECHA_PAGO,
  P.MONTO,
  P.METODO_PAGO,
  P.ESTADO_TRANSACCION,
  P.REFERENCIA_PAGO
FROM PAGOS P
JOIN USUARIOS U
  ON U.ID_USUARIO = P.ID_USUARIO
JOIN FACTURACIONES F
  ON F.ID_FACTURACION = P.ID_FACTURACION;

CREATE OR REPLACE VIEW VW_FIN_REFERIDOS_DETALLE AS
SELECT
  R.ID_REFERIDO,
  R.ID_USUARIO_REFERENTE,
  U_REF.EMAIL AS EMAIL_REFERENTE,
  R.ID_USUARIO_REFERIDO,
  U_REFD.EMAIL AS EMAIL_REFERIDO,
  R.FECHA_REFERIDO,
  R.ESTADO_REFERIDO,
  R.DESCUENTO_PCT
FROM REFERIDOS R
JOIN USUARIOS U_REF
  ON U_REF.ID_USUARIO = R.ID_USUARIO_REFERENTE
JOIN USUARIOS U_REFD
  ON U_REFD.ID_USUARIO = R.ID_USUARIO_REFERIDO;

COMMENT ON TABLE VW_FIN_RESUMEN_USUARIO IS
  'Resumen financiero por cuenta para consumo de API de estado de cuenta.';

COMMENT ON TABLE VW_FIN_FACTURAS_DETALLE IS
  'Vista de facturas con datos de cuenta para endpoint /finance/invoices.';

COMMENT ON TABLE VW_FIN_PAGOS_DETALLE IS
  'Vista de pagos con metadatos de periodo para endpoint /finance/payments.';

COMMENT ON TABLE VW_FIN_REFERIDOS_DETALLE IS
  'Vista de relaciones de referidos para endpoint /finance/referrals.';

COMMIT;
