-- ============================================================================
-- MinFlix - Nucleo 1 Analitica (NT1: Consultas Avanzadas, Iteracion 7)
-- Ejecutar como owner de tablas (MINFLIX_APP en XEPDB1).
-- Requiere: scripts 01..16 aplicados.
-- Objetivo:
--   Seccion A: Fragmentacion (particionamiento) de REPRODUCCIONES por FECHA_INICIO.
--   Seccion B: Vistas materializadas para calificaciones y metricas financieras.
--   Seccion C: Consultas parametrizadas (DEFINE/&&) para analitica interactiva.
--   Seccion D: Tablas cruzadas con PIVOT y UNPIVOT bidimensional.
--   Seccion E: Agrupamientos avanzados: ROLLUP, CUBE, GROUPING(), GROUPING SETS.
--   Seccion F: Vistas de lectura para los tres endpoints de analitica del backend.
-- ============================================================================

SET SERVEROUTPUT ON;
-- Nota: este script puede tardar por recreacion de tabla particionada y MVs.
-- Recomendado ejecutarlo en ventana de mantenimiento.

-- ============================================================================
-- SECCION A: Fragmentacion (Particionamiento por rango de FECHA_INICIO)
-- ============================================================================
-- Oracle no permite agregar particionamiento a una tabla existente.
-- Estrategia: guardar datos, recrear la tabla con particiones, reinsertar.
-- Se usan cinco particiones por ventanas de tiempo para optimizar consultas
-- analiticas que filtran por periodo (WHERE FECHA_INICIO BETWEEN ...).
-- ============================================================================
-- Importante: el backup REPRODUCCIONES_BKP permite rollback manual si falla.

-- Paso A.1: Guardar datos existentes en tabla temporal de respaldo
CREATE TABLE REPRODUCCIONES_BKP AS
  SELECT * FROM REPRODUCCIONES;

-- Paso A.2: Eliminar tabla original con sus constraints e indices
--   CASCADE CONSTRAINTS elimina las FKs propias (PERFILES, CONTENIDOS).
--   El trigger TRG_REPRODUCCIONES_REGLAS_BIU se elimina automaticamente.
--   La vista VW_CONTINUAR_VIENDO quedara invalida y se recompilara al recrear la tabla.
DROP TABLE REPRODUCCIONES CASCADE CONSTRAINTS;

-- Paso A.3: Recrear tabla con PARTITION BY RANGE sobre FECHA_INICIO.
-- Cada particion almacena fisicamente las reproducciones de un periodo de tiempo,
-- acelerando consultas analiticas que filtran por rango de fechas.
CREATE TABLE REPRODUCCIONES (
  -- PK autogenerada: identificador unico de cada sesion de reproduccion
  ID_REPRODUCCION         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- FK al perfil que realiza la reproduccion (obligatorio)
  ID_PERFIL               NUMBER NOT NULL,
  -- FK al contenido reproducido (obligatorio)
  ID_CONTENIDO            NUMBER NOT NULL,
  -- Segundos visionados hasta el momento (no puede ser negativo)
  PROGRESO_SEGUNDOS       NUMBER(10,0) DEFAULT 0 NOT NULL,
  -- Duracion total del contenido en segundos (NULL si no se conoce)
  DURACION_TOTAL_SEGUNDOS NUMBER(10,0) NULL,
  -- Porcentaje de visionado calculado automaticamente por trigger (0-100)
  PORCENTAJE_AVANCE       NUMBER(5,2) DEFAULT 0 NOT NULL,
  -- Dispositivo desde el que se reprodujo (tv, movil, computador, tablet)
  ULTIMO_DISPOSITIVO      VARCHAR2(80) NULL,
  -- Estado de la sesion: EN_PROGRESO, PAUSADO o FINALIZADO
  ESTADO_REPRODUCCION     VARCHAR2(20) DEFAULT 'EN_PROGRESO' NOT NULL,
  -- Fecha y hora de inicio de la reproduccion (clave de particionamiento)
  FECHA_INICIO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Fecha y hora del ultimo evento recibido (heartbeat/pausa/progreso)
  FECHA_ULTIMO_EVENTO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  -- Fecha y hora en que la reproduccion llego a FINALIZADO (NULL si aun no)
  FECHA_FIN               TIMESTAMP NULL,
  -- Constraint: el progreso no puede ser negativo
  CONSTRAINT CK_REPRO_PROGRESO  CHECK (PROGRESO_SEGUNDOS >= 0),
  -- Constraint: si hay duracion total, debe ser mayor que cero
  CONSTRAINT CK_REPRO_DURACION  CHECK (
    DURACION_TOTAL_SEGUNDOS IS NULL OR DURACION_TOTAL_SEGUNDOS > 0
  ),
  -- Constraint: el porcentaje de avance debe estar entre 0 y 100
  CONSTRAINT CK_REPRO_PORCENTAJE CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
  -- Constraint: solo valores validos de estado de reproduccion
  CONSTRAINT CK_REPRO_ESTADO    CHECK (
    ESTADO_REPRODUCCION IN ('EN_PROGRESO', 'PAUSADO', 'FINALIZADO')
  ),
  -- FK: el perfil debe existir en la tabla PERFILES
  CONSTRAINT FK_REPRO_PERFIL    FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  -- FK: el contenido debe existir en la tabla CONTENIDOS
  CONSTRAINT FK_REPRO_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
)
-- Particionamiento por rango sobre FECHA_INICIO para consultas analiticas rapidas.
-- Oracle redirige la consulta a la particion relevante sin escanear toda la tabla.
PARTITION BY RANGE (FECHA_INICIO) (
  -- Partition P_2024: reproducciones del ano 2024 (hasta 2025-01-01 exclusive)
  PARTITION P_2024    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
  -- Partition P_2025_Q1: primer trimestre de 2025 (hasta 2025-04-01 exclusive)
  PARTITION P_2025_Q1 VALUES LESS THAN (TIMESTAMP '2025-04-01 00:00:00'),
  -- Partition P_2025_Q2: segundo trimestre de 2025 (hasta 2025-07-01 exclusive)
  PARTITION P_2025_Q2 VALUES LESS THAN (TIMESTAMP '2025-07-01 00:00:00'),
  -- Partition P_2025_Q3: tercer trimestre de 2025 (hasta 2025-10-01 exclusive)
  PARTITION P_2025_Q3 VALUES LESS THAN (TIMESTAMP '2025-10-01 00:00:00'),
  -- Partition P_FUTURO: cuarto trimestre 2025 y todas las fechas posteriores
  PARTITION P_FUTURO  VALUES LESS THAN (MAXVALUE)
);

-- Paso A.4: Reinsertar datos del respaldo en la tabla particionada
-- Mantiene IDs originales para no romper referencias en historiales.
INSERT INTO REPRODUCCIONES (
  ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO,
  PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS, PORCENTAJE_AVANCE,
  ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  FECHA_INICIO, FECHA_ULTIMO_EVENTO, FECHA_FIN
)
SELECT
  ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO,
  PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS, PORCENTAJE_AVANCE,
  ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  FECHA_INICIO, FECHA_ULTIMO_EVENTO, FECHA_FIN
FROM REPRODUCCIONES_BKP;

COMMIT;

-- Paso A.5: Recrear indices de la tabla original (script 04)
CREATE INDEX IDX_REPRODUCCIONES_PERFIL_EVENTO
  ON REPRODUCCIONES (ID_PERFIL, FECHA_ULTIMO_EVENTO DESC)
  LOCAL; -- LOCAL: cada particion tiene su propio segmento de indice

CREATE INDEX IDX_REPRODUCCIONES_CONTENIDO
  ON REPRODUCCIONES (ID_CONTENIDO, FECHA_ULTIMO_EVENTO DESC)
  LOCAL;

CREATE INDEX IDX_REPRODUCCIONES_ESTADO
  ON REPRODUCCIONES (ESTADO_REPRODUCCION)
  LOCAL;

-- Paso A.6: Recrear trigger de validacion (identico al de script 04)
CREATE OR REPLACE TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU
BEFORE INSERT OR UPDATE ON REPRODUCCIONES
FOR EACH ROW
DECLARE
  V_ESTADO_CUENTA USUARIOS.ESTADO_CUENTA%TYPE;
  V_TIPO_PERFIL   PERFILES.TIPO_PERFIL%TYPE;
  V_CLASIFICACION CONTENIDOS.CLASIFICACION_EDAD%TYPE;
BEGIN
  SELECT U.ESTADO_CUENTA, P.TIPO_PERFIL, C.CLASIFICACION_EDAD
    INTO V_ESTADO_CUENTA, V_TIPO_PERFIL, V_CLASIFICACION
    FROM PERFILES P
    INNER JOIN USUARIOS U ON U.ID_USUARIO = P.ID_USUARIO
    INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = :NEW.ID_CONTENIDO
   WHERE P.ID_PERFIL = :NEW.ID_PERFIL;

  IF V_ESTADO_CUENTA <> 'ACTIVO' THEN
    RAISE_APPLICATION_ERROR(
      -20021,
      'La cuenta debe estar activa para registrar reproducciones'
    );
  END IF;

  IF FN_CLASIFICACION_PERMITIDA_PARA_PERFIL(V_TIPO_PERFIL, V_CLASIFICACION) = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20022,
      'El perfil seleccionado no puede reproducir este contenido por clasificacion'
    );
  END IF;

  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL
     AND :NEW.PROGRESO_SEGUNDOS > :NEW.DURACION_TOTAL_SEGUNDOS THEN
    RAISE_APPLICATION_ERROR(
      -20023,
      'El progreso no puede superar la duracion total del contenido'
    );
  END IF;

  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL
     AND :NEW.DURACION_TOTAL_SEGUNDOS > 0 THEN
    :NEW.PORCENTAJE_AVANCE := ROUND(
      LEAST(100, (:NEW.PROGRESO_SEGUNDOS / :NEW.DURACION_TOTAL_SEGUNDOS) * 100),
      2
    );
  ELSE
    :NEW.PORCENTAJE_AVANCE := 0;
  END IF;

  :NEW.FECHA_ULTIMO_EVENTO := CURRENT_TIMESTAMP;

  IF :NEW.ESTADO_REPRODUCCION = 'FINALIZADO' AND :NEW.FECHA_FIN IS NULL THEN
    :NEW.FECHA_FIN := CURRENT_TIMESTAMP;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20024,
      'No existe el perfil o contenido asociado para registrar reproduccion'
    );
END;
/

-- Paso A.7: Forzar recompilacion de la vista que depende de REPRODUCCIONES
ALTER VIEW VW_CONTINUAR_VIENDO COMPILE;

-- Paso A.8: Eliminar tabla de respaldo
DROP TABLE REPRODUCCIONES_BKP;

-- Verificacion de particiones creadas
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE
  FROM USER_TAB_PARTITIONS
 WHERE TABLE_NAME = 'REPRODUCCIONES'
 ORDER BY PARTITION_POSITION;

-- ============================================================================
-- SECCION B: Vistas Materializadas (2 requeridas por NT1)
-- ============================================================================
-- Las vistas materializadas almacenan fisicamente el resultado de una consulta.
-- Se usan para pre-calcular agregaciones costosas y acelerar consultas analiticas.
-- REFRESH ON DEMAND: se actualizan manualmente con DBMS_MVIEW.REFRESH.
-- ============================================================================
-- Nota: estas MVs pueden refrescarse al finalizar cargas o seeds.

-- MV 1: Promedio de calificaciones por contenido y genero.
-- Pre-calcula agregaciones costosas para evitar recalcular en cada consulta del dashboard.
-- LEFT JOIN con GENEROS porque un contenido puede no tener generos asignados.
-- BUILD IMMEDIATE: crea y puebla la MV inmediatamente.
-- REFRESH ON DEMAND: se actualiza manualmente con DBMS_MVIEW.REFRESH.
CREATE MATERIALIZED VIEW MV_CALIFICACIONES_PROMEDIO
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT
  C.ID_CONTENIDO,                      -- PK del contenido evaluado
  C.TITULO,                            -- Titulo legible del contenido
  C.TIPO_CONTENIDO,                    -- Tipo: pelicula, serie, documental, etc.
  G.NOMBRE                         AS GENERO,  -- Genero asociado (NULL si no tiene)
  ROUND(AVG(CAL.PUNTAJE), 2)       AS PROMEDIO_PUNTAJE,     -- Puntaje medio 1-5
  COUNT(CAL.ID_CALIFICACION)       AS TOTAL_CALIFICACIONES, -- Cantidad de reviews
  MIN(CAL.PUNTAJE)                 AS PUNTAJE_MINIMO,       -- Puntaje mas bajo recibido
  MAX(CAL.PUNTAJE)                 AS PUNTAJE_MAXIMO        -- Puntaje mas alto recibido
FROM CALIFICACIONES CAL
-- JOIN obligatorio: solo calificaciones de contenidos existentes
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = CAL.ID_CONTENIDO
-- LEFT JOIN: traer generos del contenido si existen (no excluye sin genero)
LEFT JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
GROUP BY
  C.ID_CONTENIDO,
  C.TITULO,
  C.TIPO_CONTENIDO,
  G.NOMBRE;

-- MV 2: Metricas financieras agregadas por plan y periodo.
-- Resume millones de facturas en pocas filas para el dashboard ejecutivo.
-- CASE WHEN separa ingresos cobrados vs por cobrar para analisis de cartera.
-- COUNT(DISTINCT) evita contar el mismo usuario dos veces si tiene multiples facturas.
CREATE MATERIALIZED VIEW MV_METRICAS_FINANCIERAS
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT
  PL.NOMBRE                        AS PLAN,            -- Nombre comercial del plan
  F.PERIODO_ANIO,                                       -- Anio de facturacion
  F.PERIODO_MES,                                        -- Mes de facturacion
  COUNT(F.ID_FACTURACION)          AS TOTAL_FACTURAS,   -- Cantidad de facturas emitidas
  SUM(F.MONTO_FINAL)               AS INGRESOS_TOTALES, -- Suma de todos los montos finales
  -- Suma solo de facturas pagadas (estado = 'PAGADA')
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                                AS INGRESOS_COBRADOS,
  -- Suma de facturas pendientes o vencidas (cartera por cobrar)
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                                AS INGRESOS_PENDIENTES,
  -- Usuarios unicos facturados en este plan/periodo
  COUNT(DISTINCT F.ID_USUARIO)     AS USUARIOS_FACTURADOS
FROM FACTURACIONES F
-- JOIN obligatorio: traer datos del usuario para resolver su plan
JOIN USUARIOS U
  ON U.ID_USUARIO = F.ID_USUARIO
-- JOIN obligatorio: traer nombre y precio del plan
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
GROUP BY
  PL.NOMBRE,
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Verificacion de vistas materializadas
SELECT MVIEW_NAME, LAST_REFRESH_DATE, STALENESS
  FROM USER_MVIEWS
 WHERE MVIEW_NAME IN ('MV_CALIFICACIONES_PROMEDIO', 'MV_METRICAS_FINANCIERAS');

-- ============================================================================
-- SECCION C: Consultas Parametrizadas (3 requeridas por NT1)
-- ============================================================================
-- Se usa DEFINE para declarar variables de sustitucion.
-- El usuario puede cambiar el valor antes de ejecutar cada bloque.
-- Util para reportes ad-hoc en SQL Developer o SQL*Plus.
-- ============================================================================
-- Consejo: usar UNDEFINE ciudad/limite/fecha_inicio/fecha_fin al terminar.

-- Consulta C.1: Top N contenidos mas reproducidos por ciudad de residencia.
-- Uso: cambiar &&ciudad y &&limite antes de ejecutar (DEFINE ciudad = 'Medellin'; DEFINE limite = 5).
-- UPPER() en ambos lados hace la comparacion case-insensitive.
-- Subconsulta interna calcula agregaciones; ROWNUM filtra el top N.
DEFINE ciudad = 'Bogota'
DEFINE limite = 10

SELECT *
FROM (
  SELECT
    C.TITULO,                                            -- Titulo del contenido
    C.TIPO_CONTENIDO,                                    -- Tipo: pelicula, serie, etc.
    CAT.NOMBRE                       AS CATEGORIA,       -- Categoria del contenido
    COUNT(R.ID_REPRODUCCION)         AS TOTAL_REPRODUCCIONES, -- Veces reproducido
    ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS PROMEDIO_AVANCE_PCT  -- Avance medio en %
  FROM REPRODUCCIONES R
  -- JOIN a PERFILES para obtener el perfil que reprodujo
  JOIN PERFILES P
    ON P.ID_PERFIL = R.ID_PERFIL
  -- JOIN a USUARIOS para filtrar por ciudad de residencia
  JOIN USUARIOS U
    ON U.ID_USUARIO = P.ID_USUARIO
  -- JOIN a CONTENIDOS para traer titulo y tipo del contenido
  JOIN CONTENIDOS C
    ON C.ID_CONTENIDO = R.ID_CONTENIDO
  -- JOIN a CATEGORIAS para traer el nombre legible de la categoria
  JOIN CATEGORIAS CAT
    ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
  -- Filtro por ciudad (parametro interactivo &&ciudad)
  WHERE UPPER(U.CIUDAD_RESIDENCIA) = UPPER('&&ciudad')
  GROUP BY
    C.TITULO,
    C.TIPO_CONTENIDO,
    CAT.NOMBRE
  -- Ordenar por mas reproducido primero
  ORDER BY TOTAL_REPRODUCCIONES DESC
)
-- Limitar a los &&limite resultados mas populares
WHERE ROWNUM <= &&limite;

-- Consulta C.2: Ingresos de facturacion agrupados por mes en un rango de fechas.
-- Uso: cambiar &&fecha_inicio y &&fecha_fin antes de ejecutar.
-- TO_DATE convierte el string del parametro a fecha Oracle con formato YYYY-MM-DD.
-- CASE WHEN separa ingresos cobrados vs por cobrar para analisis de cartera.
DEFINE fecha_inicio = '2025-01-01'
DEFINE fecha_fin    = '2025-12-31'

SELECT
  F.PERIODO_ANIO,                           -- Anio de facturacion
  F.PERIODO_MES,                            -- Mes de facturacion
  COUNT(F.ID_FACTURACION) AS TOTAL_FACTURAS,   -- Facturas emitidas en el mes
  SUM(F.MONTO_FINAL)      AS INGRESOS_TOTALES, -- Monto total facturado
  -- Suma solo de facturas pagadas (estado = 'PAGADA')
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                       AS INGRESOS_COBRADOS,
  -- Suma de facturas pendientes o vencidas (cartera por cobrar)
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                       AS INGRESOS_POR_COBRAR
FROM FACTURACIONES F
-- Filtro por rango de fechas de corte usando parametros interactivos
WHERE F.FECHA_CORTE
      BETWEEN TO_DATE('&&fecha_inicio', 'YYYY-MM-DD')
          AND TO_DATE('&&fecha_fin',    'YYYY-MM-DD')
GROUP BY
  F.PERIODO_ANIO,
  F.PERIODO_MES
ORDER BY
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Consulta C.3: Estadisticas de calificaciones por genero de contenido.
-- Uso: cambiar &&genero antes de ejecutar (DEFINE genero = 'Accion';).
-- UPPER() hace la comparacion case-insensitive del nombre del genero.
-- Ordena por puntaje promedio descendente para ver los mejor valorados primero.
DEFINE genero = 'Drama'

SELECT
  C.TITULO,                                   -- Titulo del contenido
  C.TIPO_CONTENIDO,                           -- Tipo: pelicula, serie, etc.
  CAT.NOMBRE             AS CATEGORIA,        -- Categoria del contenido
  ROUND(AVG(CAL.PUNTAJE), 2) AS PROMEDIO_PUNTAJE,  -- Puntaje medio 1-5
  COUNT(CAL.ID_CALIFICACION) AS TOTAL_CALIFICACIONES, -- Cantidad de reviews
  MIN(CAL.PUNTAJE)       AS PUNTAJE_MIN,      -- Puntaje mas bajo recibido
  MAX(CAL.PUNTAJE)       AS PUNTAJE_MAX       -- Puntaje mas alto recibido
FROM CALIFICACIONES CAL
-- JOIN obligatorio: traer titulo y tipo del contenido calificado
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = CAL.ID_CONTENIDO
-- JOIN obligatorio: traer categoria del contenido
JOIN CATEGORIAS CAT
  ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
-- JOIN obligatorio: resolver generos asociados al contenido
JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
-- JOIN obligatorio: traer nombre del genero para filtrar
JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
-- Filtro por genero (parametro interactivo &&genero)
WHERE UPPER(G.NOMBRE) = UPPER('&&genero')
GROUP BY
  C.TITULO,
  C.TIPO_CONTENIDO,
  CAT.NOMBRE
-- Mejor valorados primero
ORDER BY PROMEDIO_PUNTAJE DESC;

-- ============================================================================
-- SECCION D: Tablas Cruzadas (PIVOT y UNPIVOT)
-- ============================================================================
-- PIVOT gira filas en columnas para analisis bidimensional.
-- UNPIVOT revierte columnas a filas para normalizar datos pivotados.
-- ============================================================================

-- PIVOT D.1: Total de reproducciones por dispositivo y mes del ano.
-- Convierte filas de reproducciones en una tabla bidimensional:
--   Filas: dispositivo (movil, tablet, tv, computador, Sin dispositivo)
--   Columnas: MES_1 .. MES_12 (cantidad de reproducciones por mes)
-- NVL reemplaza NULL por 'Sin dispositivo' para no perder reproducciones sin dispositivo.
-- EXTRACT(MONTH) obtiene el numero de mes (1-12) de la fecha de inicio.
SELECT *
FROM (
  SELECT
    NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO, -- Dispositivo de reproduccion
    EXTRACT(MONTH FROM R.FECHA_INICIO)            AS MES,         -- Numero de mes 1-12
    R.ID_REPRODUCCION                                         -- PK de la reproduccion
  FROM REPRODUCCIONES R
)
-- PIVOT: cuenta reproducciones para cada combinacion (dispositivo x mes)
PIVOT (
  COUNT(ID_REPRODUCCION)
  FOR MES IN (
    1  AS MES_1,  2  AS MES_2,  3  AS MES_3,
    4  AS MES_4,  5  AS MES_5,  6  AS MES_6,
    7  AS MES_7,  8  AS MES_8,  9  AS MES_9,
    10 AS MES_10, 11 AS MES_11, 12 AS MES_12
  )
)
ORDER BY DISPOSITIVO;

-- PIVOT D.2: Cantidad de usuarios activos por plan de suscripcion y ciudad.
-- Convierte filas de usuarios en matriz bidimensional:
--   Filas: plan comercial (BASICO, ESTANDAR, PREMIUM)
--   Columnas: ciudades principales del seed de datos (BOGOTA, MEDELLIN, CALI, etc.)
-- Solo considera usuarios con ESTADO_CUENTA = 'ACTIVO'.
SELECT *
FROM (
  SELECT
    PL.NOMBRE            AS PLAN,          -- Nombre del plan comercial
    U.CIUDAD_RESIDENCIA  AS CIUDAD         -- Ciudad de residencia del usuario
  FROM USUARIOS U
  -- JOIN obligatorio: resolver el nombre del plan a partir de ID_PLAN
  JOIN PLANES PL ON PL.ID_PLAN = U.ID_PLAN
  -- Solo usuarios activos (no suspendidos ni cancelados)
  WHERE U.ESTADO_CUENTA = 'ACTIVO'
)
-- PIVOT: cuenta usuarios para cada combinacion (plan x ciudad)
PIVOT (
  COUNT(*)
  FOR CIUDAD IN (
    'Bogota'       AS BOGOTA,
    'Medellin'     AS MEDELLIN,
    'Cali'         AS CALI,
    'Barranquilla' AS BARRANQUILLA,
    'Cartagena'    AS CARTAGENA
  )
)
ORDER BY PLAN;

-- UNPIVOT D.3: Desnormalizar el resultado de PIVOT D.1 de vuelta a filas.
-- Primero aplica PIVOT (como en D.1), luego UNPIVOT revierte columnas a filas.
-- Utilidad: permite filtrar por dispositivo y mes con WHERE sin manipular columnas dinamicas.
-- WHERE TOTAL_REPRODUCCIONES > 0 excluye combinaciones sin reproducciones.
SELECT DISPOSITIVO, MES_NOMBRE, TOTAL_REPRODUCCIONES
FROM (
  SELECT *
  FROM (
    SELECT
      NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO,
      EXTRACT(MONTH FROM R.FECHA_INICIO)            AS MES,
      R.ID_REPRODUCCION
    FROM REPRODUCCIONES R
  )
  -- Paso intermedio: aplicar PIVOT para obtener columnas MES_1..MES_12
  PIVOT (
    COUNT(ID_REPRODUCCION)
    FOR MES IN (
      1  AS MES_1,  2  AS MES_2,  3  AS MES_3,
      4  AS MES_4,  5  AS MES_5,  6  AS MES_6,
      7  AS MES_7,  8  AS MES_8,  9  AS MES_9,
      10 AS MES_10, 11 AS MES_11, 12 AS MES_12
    )
  )
)
-- UNPIVOT: convierte cada columna MES_N en una fila con el valor de reproducciones
UNPIVOT (
  TOTAL_REPRODUCCIONES
  FOR MES_NOMBRE IN (
    MES_1, MES_2, MES_3, MES_4,  MES_5,  MES_6,
    MES_7, MES_8, MES_9, MES_10, MES_11, MES_12
  )
)
-- Filtrar solo combinaciones que tienen al menos una reproduccion
WHERE TOTAL_REPRODUCCIONES > 0
ORDER BY DISPOSITIVO, MES_NOMBRE;

-- UNPIVOT D.4: Desnormalizar MV_METRICAS_FINANCIERAS para ver tipo de ingreso como fila.
-- Convierte las columnas INGRESOS_COBRADOS e INGRESOS_PENDIENTES en filas separadas.
-- Utilidad: facilita graficos de barras apiladas donde cada fila es una barra.
-- WHERE MONTO > 0 excluye periodos sin ingresos de ese tipo.
SELECT PLAN, PERIODO_ANIO, PERIODO_MES, TIPO_INGRESO, MONTO
FROM MV_METRICAS_FINANCIERAS
-- UNPIVOT: cada columna de ingreso se convierte en una fila con su etiqueta
UNPIVOT (
  MONTO
  FOR TIPO_INGRESO IN (
    INGRESOS_COBRADOS   AS 'COBRADO',
    INGRESOS_PENDIENTES AS 'PENDIENTE'
  )
)
-- Solo incluir filas con montos positivos
WHERE MONTO > 0
ORDER BY PLAN, PERIODO_ANIO, PERIODO_MES, TIPO_INGRESO;

-- ============================================================================
-- SECCION E: Agrupamientos Avanzados (4 requeridos por NT1)
-- ============================================================================

-- Agrupamiento E.1: ROLLUP — subtotales jerarquicos de ingresos.
-- ROLLUP(f.PERIODO_ANIO, f.PERIODO_MES) genera 3 niveles de agregacion:
--   1) Total por anio y mes (filas normales)
--   2) Subtotal por anio (fila donde PERIODO_MES es NULL)
--   3) Gran total (fila donde PERIODO_ANIO y PERIODO_MES son NULL)
-- NULLS LAST ordena los subtotales al final para legibilidad.
SELECT
  F.PERIODO_ANIO,                          -- Anio de facturacion (NULL en subtotal)
  F.PERIODO_MES,                           -- Mes de facturacion (NULL en subtotal)
  SUM(F.MONTO_FINAL)      AS INGRESOS_TOTALES,   -- Suma de montos para ese nivel
  COUNT(F.ID_FACTURACION) AS TOTAL_FACTURAS      -- Cantidad de facturas para ese nivel
FROM FACTURACIONES F
GROUP BY ROLLUP(F.PERIODO_ANIO, F.PERIODO_MES)
ORDER BY
  F.PERIODO_ANIO NULLS LAST,
  F.PERIODO_MES  NULLS LAST;

-- Agrupamiento E.2: CUBE — todas las combinaciones posibles entre dispositivo y ano.
-- CUBE(dispositivo, anio) genera 4 niveles de agregacion:
--   1) Total por dispositivo y anio (filas normales)
--   2) Subtotal por dispositivo (anio = NULL)
--   3) Subtotal por anio (dispositivo = NULL)
--   4) Gran total (dispositivo = NULL, anio = NULL)
-- NVL reemplaza NULL por 'Sin dispositivo' para mantener coherencia en las filas.
SELECT
  NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO,  -- Dispositivo de reproduccion
  EXTRACT(YEAR FROM R.FECHA_INICIO)             AS ANIO,         -- Anio de reproduccion
  COUNT(R.ID_REPRODUCCION)                     AS TOTAL_REPRODUCCIONES, -- Sesiones contadas
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2)          AS PROMEDIO_AVANCE      -- Avance promedio en %
FROM REPRODUCCIONES R
GROUP BY CUBE(
  NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo'),
  EXTRACT(YEAR FROM R.FECHA_INICIO)
)
ORDER BY
  DISPOSITIVO NULLS LAST,
  ANIO        NULLS LAST;

-- Agrupamiento E.3: GROUPING() — identifica filas de subtotal en resultado ROLLUP.
-- GROUPING(columna) retorna 1 cuando la columna forma parte de una fila de subtotal.
-- DECODE traduce 1/0 en etiquetas legibles para reportes ('TOTAL GENERAL', 'SUBTOTAL ANO').
-- Utilidad: permite que la aplicacion frontend distinga filas de detalle vs agregadas.
SELECT
  -- Etiqueta legible del anio: 'TOTAL GENERAL' si es subtotal, valor real si no
  DECODE(GROUPING(F.PERIODO_ANIO), 1, 'TOTAL GENERAL', TO_CHAR(F.PERIODO_ANIO))
    AS ANIO_LABEL,
  -- Etiqueta legible del mes: 'SUBTOTAL ANO' si es subtotal, valor real si no
  DECODE(GROUPING(F.PERIODO_MES),  1, 'SUBTOTAL ANO',  TO_CHAR(F.PERIODO_MES))
    AS MES_LABEL,
  -- Flag binario: 1 si esta fila es el gran total, 0 si no
  GROUPING(F.PERIODO_ANIO) AS ES_TOTAL_GENERAL,
  -- Flag binario: 1 si esta fila es subtotal de anio, 0 si no
  GROUPING(F.PERIODO_MES)  AS ES_SUBTOTAL_ANO,
  SUM(F.MONTO_FINAL)       AS INGRESOS_TOTALES
FROM FACTURACIONES F
GROUP BY ROLLUP(F.PERIODO_ANIO, F.PERIODO_MES)
ORDER BY
  F.PERIODO_ANIO NULLS LAST,
  F.PERIODO_MES  NULLS LAST;

-- Agrupamiento E.4: GROUPING SETS — combinaciones especificas a eleccion del analista.
-- A diferencia de CUBE (que calcula todas las combinaciones), GROUPING SETS permite
-- elegir exactamente cuales combinaciones de agregacion se desean.
-- En este caso: (ciudad + plan), (solo ciudad), (solo plan), (gran total).
-- COUNT(DISTINCT) evita contar el mismo usuario dos veces si tiene multiples facturas.
SELECT
  U.CIUDAD_RESIDENCIA,                        -- Ciudad de residencia (NULL en subtotales)
  PL.NOMBRE             AS PLAN,                -- Nombre del plan (NULL en subtotales)
  COUNT(DISTINCT U.ID_USUARIO) AS USUARIOS_ACTIVOS, -- Usuarios unicos en ese nivel
  SUM(F.MONTO_FINAL)    AS INGRESOS            -- Ingresos totales en ese nivel
FROM USUARIOS U
-- JOIN obligatorio: resolver nombre del plan
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
-- JOIN obligatorio: traer facturaciones del usuario
JOIN FACTURACIONES F
  ON F.ID_USUARIO = U.ID_USUARIO
GROUP BY GROUPING SETS (
  (U.CIUDAD_RESIDENCIA, PL.NOMBRE),  -- Agregacion combinada: ciudad + plan
  (U.CIUDAD_RESIDENCIA),             -- Agregacion por ciudad solamente
  (PL.NOMBRE),                       -- Agregacion por plan solamente
  ()                                 -- Gran total de todos los usuarios
)
ORDER BY
  U.CIUDAD_RESIDENCIA NULLS LAST,
  PL.NOMBRE           NULLS LAST;

-- ============================================================================
-- SECCION F: Vistas de Lectura para Endpoints de Analitica del Backend
-- ============================================================================
-- Estas tres vistas son consumidas por los endpoints:
--   GET /api/v1/analytics/consumption
--   GET /api/v1/analytics/finance
--   GET /api/v1/analytics/internal-performance
-- El backend aplica filtros adicionales sobre estas vistas en tiempo de ejecucion.
-- Nota: VW_ANALITICA_CONSUMO puede producir multiples filas por reproduccion
--       cuando el contenido tiene varios generos (comportamiento esperado).
-- ============================================================================
-- Las vistas consolidan datos para filtros en API sin recalcular joins complejos.

-- Vista F.1: Consumo de contenido por dimension geografica, dispositivo y plan.
-- Consumida por el endpoint GET /api/v1/analytics/consumption.
-- LEFT JOIN con GENEROS porque un contenido puede no tener generos asignados.
-- TRUNC(..., 'MM') trunca la fecha al primer dia del mes para agregacion mensual.
-- COUNT(DISTINCT R.ID_PERFIL) evita contar el mismo perfil multiple veces.
CREATE OR REPLACE VIEW VW_ANALITICA_CONSUMO AS
SELECT
  U.CIUDAD_RESIDENCIA,                        -- Ciudad de residencia del usuario
  CAT.NOMBRE            AS CATEGORIA,          -- Categoria del contenido (ej. Accion, Drama)
  G.NOMBRE              AS GENERO,             -- Genero del contenido (NULL si no tiene)
  R.ULTIMO_DISPOSITIVO,                        -- Dispositivo desde el que se reprodujo
  PL.NOMBRE             AS PLAN,               -- Plan de suscripcion del usuario
  TRUNC(R.FECHA_INICIO, 'MM') AS PERIODO_MES, -- Periodo mensual truncado (primer dia)
  COUNT(R.ID_REPRODUCCION)    AS TOTAL_REPRODUCCIONES, -- Cantidad de sesiones de visionado
  COUNT(DISTINCT R.ID_PERFIL) AS PERFILES_UNICOS,     -- Perfiles distintos que reprodujeron
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS PROMEDIO_AVANCE -- Avance promedio en %
FROM REPRODUCCIONES R
-- JOIN obligatorio: traer datos del perfil que reprodujo
JOIN PERFILES P
  ON P.ID_PERFIL = R.ID_PERFIL
-- JOIN obligatorio: traer datos del usuario titular
JOIN USUARIOS U
  ON U.ID_USUARIO = P.ID_USUARIO
-- JOIN obligatorio: traer nombre del plan de suscripcion
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
-- JOIN obligatorio: traer titulo y categoria del contenido
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = R.ID_CONTENIDO
-- JOIN obligatorio: traer nombre legible de la categoria
JOIN CATEGORIAS CAT
  ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
-- LEFT JOIN: traer generos del contenido si existen (no excluye sin genero)
LEFT JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
GROUP BY
  U.CIUDAD_RESIDENCIA,
  CAT.NOMBRE,
  G.NOMBRE,
  R.ULTIMO_DISPOSITIVO,
  PL.NOMBRE,
  TRUNC(R.FECHA_INICIO, 'MM');

-- Vista F.2: Metricas financieras por ciudad, plan y periodo de facturacion.
-- Consumida por el endpoint GET /api/v1/analytics/finance.
-- CASE WHEN separa ingresos cobrados vs pendientes para analisis de cartera.
-- COUNT(DISTINCT F.ID_USUARIO) evita contar el mismo usuario dos veces.
CREATE OR REPLACE VIEW VW_ANALITICA_FINANZAS AS
SELECT
  U.CIUDAD_RESIDENCIA,                        -- Ciudad de residencia del usuario facturado
  PL.NOMBRE             AS PLAN,               -- Nombre comercial del plan
  F.PERIODO_ANIO,                              -- Anio de facturacion
  F.PERIODO_MES,                               -- Mes de facturacion
  COUNT(F.ID_FACTURACION)    AS TOTAL_FACTURAS,     -- Facturas emitidas en ese nivel
  SUM(F.MONTO_FINAL)         AS INGRESOS_TOTALES,   -- Monto total facturado
  -- Suma solo de facturas con estado 'PAGADA'
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                          AS INGRESOS_COBRADOS,
  -- Suma de facturas con estado 'PENDIENTE' o 'VENCIDA' (cartera por cobrar)
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                          AS INGRESOS_PENDIENTES,
  COUNT(DISTINCT F.ID_USUARIO) AS USUARIOS_FACTURADOS -- Usuarios unicos facturados
FROM FACTURACIONES F
-- JOIN obligatorio: traer datos del usuario para resolver ciudad y plan
JOIN USUARIOS U
  ON U.ID_USUARIO = F.ID_USUARIO
-- JOIN obligatorio: traer nombre del plan de suscripcion
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
GROUP BY
  U.CIUDAD_RESIDENCIA,
  PL.NOMBRE,
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Vista F.3: Rendimiento interno del equipo por departamento y cohort de ingreso.
-- Consumida por el endpoint GET /api/v1/analytics/internal-performance.
-- SUM(E.ES_JEFE) suma las banderas booleanas (1 = jefe, 0 = no jefe) para contar lideres.
-- CASE WHEN dentro de COUNT cuenta solo empleados con estado 'ACTIVO'.
-- EXTRACT separa fecha de ingreso en anio y mes para analisis de cohort.
CREATE OR REPLACE VIEW VW_ANALITICA_RENDIMIENTO AS
SELECT
  D.NOMBRE             AS DEPARTAMENTO,      -- Nombre del departamento organizacional
  COUNT(E.ID_EMPLEADO) AS TOTAL_EMPLEADOS,   -- Cantidad total de empleados
  SUM(E.ES_JEFE)       AS TOTAL_JEFES,       -- Cantidad de empleados con rol de jefe
  -- Contar solo empleados cuyo estado es 'ACTIVO'
  COUNT(
    CASE WHEN E.ESTADO_EMPLEADO = 'ACTIVO' THEN 1 END
  )                    AS EMPLEADOS_ACTIVOS, -- Empleados actualmente activos
  EXTRACT(YEAR  FROM E.FECHA_INGRESO) AS ANIO_INGRESO,  -- Anio de contratacion
  EXTRACT(MONTH FROM E.FECHA_INGRESO)  AS MES_INGRESO    -- Mes de contratacion
FROM EMPLEADOS E
-- JOIN obligatorio: traer nombre del departamento del empleado
JOIN DEPARTAMENTOS D
  ON D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
GROUP BY
  D.NOMBRE,
  EXTRACT(YEAR  FROM E.FECHA_INGRESO),
  EXTRACT(MONTH FROM E.FECHA_INGRESO);

-- GRANTs para que ROL_ANALISTA y ROL_ADMIN puedan consultar las vistas y MVs
GRANT SELECT ON VW_ANALITICA_CONSUMO      TO ROL_ANALISTA;
GRANT SELECT ON VW_ANALITICA_FINANZAS     TO ROL_ANALISTA;
GRANT SELECT ON VW_ANALITICA_RENDIMIENTO  TO ROL_ANALISTA;
GRANT SELECT ON MV_CALIFICACIONES_PROMEDIO TO ROL_ANALISTA;
GRANT SELECT ON MV_METRICAS_FINANCIERAS   TO ROL_ANALISTA;

GRANT SELECT ON VW_ANALITICA_CONSUMO      TO ROL_ADMIN;
GRANT SELECT ON VW_ANALITICA_FINANZAS     TO ROL_ADMIN;
GRANT SELECT ON VW_ANALITICA_RENDIMIENTO  TO ROL_ADMIN;
GRANT SELECT ON MV_CALIFICACIONES_PROMEDIO TO ROL_ADMIN;
GRANT SELECT ON MV_METRICAS_FINANCIERAS   TO ROL_ADMIN;

COMMIT;

-- Verificacion final: consultar las tres vistas
SELECT 'VW_ANALITICA_CONSUMO'     AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_CONSUMO
UNION ALL
SELECT 'VW_ANALITICA_FINANZAS'    AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_FINANZAS
UNION ALL
SELECT 'VW_ANALITICA_RENDIMIENTO' AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_RENDIMIENTO;
