-- ============================================================================
-- MinFlix - Nucleo 1 Analitica (NT1: Consultas Avanzadas, Iteracion 7)
-- Ejecutar como owner de tablas (MINFLIX_APP en XEPDB1).
-- Requiere: scripts 01..16 aplicados.
-- Objetivo:
--   Seccion A: Fragmentacion (particionamiento) de REPRODUCCIONES por FECHA_INICIO.
--   Seccion B: Vistas materializadas para calificaciones y metricas financieras.
--   Seccion C: Consultas parametrizadas (DEFINE/&&) para analitica interactiva.
--   Seccion D: Tablas cruzadas con PIVOT y UNPIVOT bidimensional.
--   Seccion E: Agrupamientos avanzados: ROLLUP, CUBE, GROUPING(), GROUPING SETS.
--   Seccion F: Vistas de lectura para los tres endpoints de analitica del backend.
-- ============================================================================

SET SERVEROUTPUT ON;

-- ============================================================================
-- SECCION A: Fragmentacion (Particionamiento por rango de FECHA_INICIO)
-- ============================================================================
-- Oracle no permite agregar particionamiento a una tabla existente.
-- Estrategia: guardar datos, recrear la tabla con particiones, reinsertar.
-- Se usan cinco particiones por ventanas de tiempo para optimizar consultas
-- analiticas que filtran por periodo (WHERE FECHA_INICIO BETWEEN ...).
-- ============================================================================

-- Paso A.1: Guardar datos existentes en tabla temporal de respaldo
CREATE TABLE REPRODUCCIONES_BKP AS
  SELECT * FROM REPRODUCCIONES;

-- Paso A.2: Eliminar tabla original con sus constraints e indices
--   CASCADE CONSTRAINTS elimina las FKs propias (PERFILES, CONTENIDOS).
--   El trigger TRG_REPRODUCCIONES_REGLAS_BIU se elimina automaticamente.
--   La vista VW_CONTINUAR_VIENDO quedara invalida y se recompilara al recrear la tabla.
DROP TABLE REPRODUCCIONES CASCADE CONSTRAINTS;

-- Paso A.3: Recrear tabla con PARTITION BY RANGE sobre FECHA_INICIO
CREATE TABLE REPRODUCCIONES (
  ID_REPRODUCCION         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ID_PERFIL               NUMBER NOT NULL,
  ID_CONTENIDO            NUMBER NOT NULL,
  PROGRESO_SEGUNDOS       NUMBER(10,0) DEFAULT 0 NOT NULL,
  DURACION_TOTAL_SEGUNDOS NUMBER(10,0) NULL,
  PORCENTAJE_AVANCE       NUMBER(5,2) DEFAULT 0 NOT NULL,
  ULTIMO_DISPOSITIVO      VARCHAR2(80) NULL,
  ESTADO_REPRODUCCION     VARCHAR2(20) DEFAULT 'EN_PROGRESO' NOT NULL,
  FECHA_INICIO            TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FECHA_ULTIMO_EVENTO     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FECHA_FIN               TIMESTAMP NULL,
  CONSTRAINT CK_REPRO_PROGRESO  CHECK (PROGRESO_SEGUNDOS >= 0),
  CONSTRAINT CK_REPRO_DURACION  CHECK (
    DURACION_TOTAL_SEGUNDOS IS NULL OR DURACION_TOTAL_SEGUNDOS > 0
  ),
  CONSTRAINT CK_REPRO_PORCENTAJE CHECK (PORCENTAJE_AVANCE BETWEEN 0 AND 100),
  CONSTRAINT CK_REPRO_ESTADO    CHECK (
    ESTADO_REPRODUCCION IN ('EN_PROGRESO', 'PAUSADO', 'FINALIZADO')
  ),
  CONSTRAINT FK_REPRO_PERFIL    FOREIGN KEY (ID_PERFIL)
    REFERENCES PERFILES(ID_PERFIL),
  CONSTRAINT FK_REPRO_CONTENIDO FOREIGN KEY (ID_CONTENIDO)
    REFERENCES CONTENIDOS(ID_CONTENIDO)
)
PARTITION BY RANGE (FECHA_INICIO) (
  -- Partition P_2024: reproducciones del ano 2024
  PARTITION P_2024    VALUES LESS THAN (TIMESTAMP '2025-01-01 00:00:00'),
  -- Partition P_2025_Q1: primer trimestre 2025
  PARTITION P_2025_Q1 VALUES LESS THAN (TIMESTAMP '2025-04-01 00:00:00'),
  -- Partition P_2025_Q2: segundo trimestre 2025
  PARTITION P_2025_Q2 VALUES LESS THAN (TIMESTAMP '2025-07-01 00:00:00'),
  -- Partition P_2025_Q3: tercer trimestre 2025
  PARTITION P_2025_Q3 VALUES LESS THAN (TIMESTAMP '2025-10-01 00:00:00'),
  -- Partition P_FUTURO: cuarto trimestre 2025 y fechas posteriores
  PARTITION P_FUTURO  VALUES LESS THAN (MAXVALUE)
);

-- Paso A.4: Reinsertar datos del respaldo en la tabla particionada
INSERT INTO REPRODUCCIONES (
  ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO,
  PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS, PORCENTAJE_AVANCE,
  ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  FECHA_INICIO, FECHA_ULTIMO_EVENTO, FECHA_FIN
)
SELECT
  ID_REPRODUCCION, ID_PERFIL, ID_CONTENIDO,
  PROGRESO_SEGUNDOS, DURACION_TOTAL_SEGUNDOS, PORCENTAJE_AVANCE,
  ULTIMO_DISPOSITIVO, ESTADO_REPRODUCCION,
  FECHA_INICIO, FECHA_ULTIMO_EVENTO, FECHA_FIN
FROM REPRODUCCIONES_BKP;

COMMIT;

-- Paso A.5: Recrear indices de la tabla original (script 04)
CREATE INDEX IDX_REPRODUCCIONES_PERFIL_EVENTO
  ON REPRODUCCIONES (ID_PERFIL, FECHA_ULTIMO_EVENTO DESC)
  LOCAL; -- LOCAL: cada particion tiene su propio segmento de indice

CREATE INDEX IDX_REPRODUCCIONES_CONTENIDO
  ON REPRODUCCIONES (ID_CONTENIDO, FECHA_ULTIMO_EVENTO DESC)
  LOCAL;

CREATE INDEX IDX_REPRODUCCIONES_ESTADO
  ON REPRODUCCIONES (ESTADO_REPRODUCCION)
  LOCAL;

-- Paso A.6: Recrear trigger de validacion (identico al de script 04)
CREATE OR REPLACE TRIGGER TRG_REPRODUCCIONES_REGLAS_BIU
BEFORE INSERT OR UPDATE ON REPRODUCCIONES
FOR EACH ROW
DECLARE
  V_ESTADO_CUENTA USUARIOS.ESTADO_CUENTA%TYPE;
  V_TIPO_PERFIL   PERFILES.TIPO_PERFIL%TYPE;
  V_CLASIFICACION CONTENIDOS.CLASIFICACION_EDAD%TYPE;
BEGIN
  SELECT U.ESTADO_CUENTA, P.TIPO_PERFIL, C.CLASIFICACION_EDAD
    INTO V_ESTADO_CUENTA, V_TIPO_PERFIL, V_CLASIFICACION
    FROM PERFILES P
    INNER JOIN USUARIOS U ON U.ID_USUARIO = P.ID_USUARIO
    INNER JOIN CONTENIDOS C ON C.ID_CONTENIDO = :NEW.ID_CONTENIDO
   WHERE P.ID_PERFIL = :NEW.ID_PERFIL;

  IF V_ESTADO_CUENTA <> 'ACTIVO' THEN
    RAISE_APPLICATION_ERROR(
      -20021,
      'La cuenta debe estar activa para registrar reproducciones'
    );
  END IF;

  IF FN_CLASIFICACION_PERMITIDA_PARA_PERFIL(V_TIPO_PERFIL, V_CLASIFICACION) = 0 THEN
    RAISE_APPLICATION_ERROR(
      -20022,
      'El perfil seleccionado no puede reproducir este contenido por clasificacion'
    );
  END IF;

  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL
     AND :NEW.PROGRESO_SEGUNDOS > :NEW.DURACION_TOTAL_SEGUNDOS THEN
    RAISE_APPLICATION_ERROR(
      -20023,
      'El progreso no puede superar la duracion total del contenido'
    );
  END IF;

  IF :NEW.DURACION_TOTAL_SEGUNDOS IS NOT NULL
     AND :NEW.DURACION_TOTAL_SEGUNDOS > 0 THEN
    :NEW.PORCENTAJE_AVANCE := ROUND(
      LEAST(100, (:NEW.PROGRESO_SEGUNDOS / :NEW.DURACION_TOTAL_SEGUNDOS) * 100),
      2
    );
  ELSE
    :NEW.PORCENTAJE_AVANCE := 0;
  END IF;

  :NEW.FECHA_ULTIMO_EVENTO := CURRENT_TIMESTAMP;

  IF :NEW.ESTADO_REPRODUCCION = 'FINALIZADO' AND :NEW.FECHA_FIN IS NULL THEN
    :NEW.FECHA_FIN := CURRENT_TIMESTAMP;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(
      -20024,
      'No existe el perfil o contenido asociado para registrar reproduccion'
    );
END;
/

-- Paso A.7: Forzar recompilacion de la vista que depende de REPRODUCCIONES
ALTER VIEW VW_CONTINUAR_VIENDO COMPILE;

-- Paso A.8: Eliminar tabla de respaldo
DROP TABLE REPRODUCCIONES_BKP;

-- Verificacion de particiones creadas
SELECT TABLE_NAME, PARTITION_NAME, HIGH_VALUE
  FROM USER_TAB_PARTITIONS
 WHERE TABLE_NAME = 'REPRODUCCIONES'
 ORDER BY PARTITION_POSITION;

-- ============================================================================
-- SECCION B: Vistas Materializadas (2 requeridas por NT1)
-- ============================================================================
-- Las vistas materializadas almacenan fisicamente el resultado de una consulta.
-- Se usan para pre-calcular agregaciones costosas y acelerar consultas analiticas.
-- REFRESH ON DEMAND: se actualizan manualmente con DBMS_MVIEW.REFRESH.
-- ============================================================================

-- MV 1: Promedio de calificaciones por contenido y genero
--   Permite obtener rapidamente el rating de cualquier contenido sin recalcular.
CREATE MATERIALIZED VIEW MV_CALIFICACIONES_PROMEDIO
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT
  C.ID_CONTENIDO,
  C.TITULO,
  C.TIPO_CONTENIDO,
  G.NOMBRE                         AS GENERO,
  ROUND(AVG(CAL.PUNTAJE), 2)       AS PROMEDIO_PUNTAJE,
  COUNT(CAL.ID_CALIFICACION)       AS TOTAL_CALIFICACIONES,
  MIN(CAL.PUNTAJE)                 AS PUNTAJE_MINIMO,
  MAX(CAL.PUNTAJE)                 AS PUNTAJE_MAXIMO
FROM CALIFICACIONES CAL
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = CAL.ID_CONTENIDO
LEFT JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
GROUP BY
  C.ID_CONTENIDO,
  C.TITULO,
  C.TIPO_CONTENIDO,
  G.NOMBRE;

-- MV 2: Metricas financieras agregadas por plan y periodo
--   Permite dashboard ejecutivo de ingresos sin recorrer millones de facturas.
CREATE MATERIALIZED VIEW MV_METRICAS_FINANCIERAS
BUILD IMMEDIATE
REFRESH ON DEMAND
AS
SELECT
  PL.NOMBRE                        AS PLAN,
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  COUNT(F.ID_FACTURACION)          AS TOTAL_FACTURAS,
  SUM(F.MONTO_FINAL)               AS INGRESOS_TOTALES,
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                                AS INGRESOS_COBRADOS,
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                                AS INGRESOS_PENDIENTES,
  COUNT(DISTINCT F.ID_USUARIO)     AS USUARIOS_FACTURADOS
FROM FACTURACIONES F
JOIN USUARIOS U
  ON U.ID_USUARIO = F.ID_USUARIO
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
GROUP BY
  PL.NOMBRE,
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Verificacion de vistas materializadas
SELECT MVIEW_NAME, LAST_REFRESH_DATE, STALENESS
  FROM USER_MVIEWS
 WHERE MVIEW_NAME IN ('MV_CALIFICACIONES_PROMEDIO', 'MV_METRICAS_FINANCIERAS');

-- ============================================================================
-- SECCION C: Consultas Parametrizadas (3 requeridas por NT1)
-- ============================================================================
-- Se usa DEFINE para declarar variables de sustitucion.
-- El usuario puede cambiar el valor antes de ejecutar cada bloque.
-- Util para reportes ad-hoc en SQL Developer o SQL*Plus.
-- ============================================================================

-- Consulta C.1: Top N contenidos mas reproducidos por ciudad de residencia
-- Parametros: &&ciudad (ciudad del usuario), &&limite (cantidad maxima de resultados)
DEFINE ciudad = 'Bogota'
DEFINE limite = 10

SELECT *
FROM (
  SELECT
    C.TITULO,
    C.TIPO_CONTENIDO,
    CAT.NOMBRE                       AS CATEGORIA,
    COUNT(R.ID_REPRODUCCION)         AS TOTAL_REPRODUCCIONES,
    ROUND(AVG(R.PORCENTAJE_AVANCE), 2) AS PROMEDIO_AVANCE_PCT
  FROM REPRODUCCIONES R
  JOIN PERFILES P
    ON P.ID_PERFIL = R.ID_PERFIL
  JOIN USUARIOS U
    ON U.ID_USUARIO = P.ID_USUARIO
  JOIN CONTENIDOS C
    ON C.ID_CONTENIDO = R.ID_CONTENIDO
  JOIN CATEGORIAS CAT
    ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
  WHERE UPPER(U.CIUDAD_RESIDENCIA) = UPPER('&&ciudad')
  GROUP BY
    C.TITULO,
    C.TIPO_CONTENIDO,
    CAT.NOMBRE
  ORDER BY TOTAL_REPRODUCCIONES DESC
)
WHERE ROWNUM <= &&limite;

-- Consulta C.2: Ingresos de facturacion agrupados por mes en un rango de fechas
-- Parametros: &&fecha_inicio (YYYY-MM-DD), &&fecha_fin (YYYY-MM-DD)
DEFINE fecha_inicio = '2025-01-01'
DEFINE fecha_fin    = '2025-12-31'

SELECT
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  COUNT(F.ID_FACTURACION)         AS TOTAL_FACTURAS,
  SUM(F.MONTO_FINAL)              AS INGRESOS_TOTALES,
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                               AS INGRESOS_COBRADOS,
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                               AS INGRESOS_POR_COBRAR
FROM FACTURACIONES F
WHERE F.FECHA_CORTE
      BETWEEN TO_DATE('&&fecha_inicio', 'YYYY-MM-DD')
          AND TO_DATE('&&fecha_fin',    'YYYY-MM-DD')
GROUP BY
  F.PERIODO_ANIO,
  F.PERIODO_MES
ORDER BY
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Consulta C.3: Estadisticas de calificaciones por genero de contenido
-- Parametro: &&genero (nombre exacto del genero, ej. Drama, Accion, Comedia)
DEFINE genero = 'Drama'

SELECT
  C.TITULO,
  C.TIPO_CONTENIDO,
  CAT.NOMBRE                        AS CATEGORIA,
  ROUND(AVG(CAL.PUNTAJE), 2)        AS PROMEDIO_PUNTAJE,
  COUNT(CAL.ID_CALIFICACION)        AS TOTAL_CALIFICACIONES,
  MIN(CAL.PUNTAJE)                  AS PUNTAJE_MIN,
  MAX(CAL.PUNTAJE)                  AS PUNTAJE_MAX
FROM CALIFICACIONES CAL
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = CAL.ID_CONTENIDO
JOIN CATEGORIAS CAT
  ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
WHERE UPPER(G.NOMBRE) = UPPER('&&genero')
GROUP BY
  C.TITULO,
  C.TIPO_CONTENIDO,
  CAT.NOMBRE
ORDER BY PROMEDIO_PUNTAJE DESC;

-- ============================================================================
-- SECCION D: Tablas Cruzadas (PIVOT y UNPIVOT)
-- ============================================================================
-- PIVOT gira filas en columnas para analisis bidimensional.
-- UNPIVOT revierte columnas a filas para normalizar datos pivotados.
-- ============================================================================

-- PIVOT D.1: Total de reproducciones por dispositivo y mes del ano
--   Filas: dispositivo (movil, tablet, tv, computador)
--   Columnas: MES_1 .. MES_12 (cantidad de reproducciones por mes)
SELECT *
FROM (
  SELECT
    NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO,
    EXTRACT(MONTH FROM R.FECHA_INICIO)            AS MES,
    R.ID_REPRODUCCION
  FROM REPRODUCCIONES R
)
PIVOT (
  COUNT(ID_REPRODUCCION)
  FOR MES IN (
    1  AS MES_1,  2  AS MES_2,  3  AS MES_3,
    4  AS MES_4,  5  AS MES_5,  6  AS MES_6,
    7  AS MES_7,  8  AS MES_8,  9  AS MES_9,
    10 AS MES_10, 11 AS MES_11, 12 AS MES_12
  )
)
ORDER BY DISPOSITIVO;

-- PIVOT D.2: Cantidad de usuarios activos por plan de suscripcion y ciudad
--   Filas: plan (BASICO, ESTANDAR, PREMIUM)
--   Columnas: ciudades principales del seed de datos
SELECT *
FROM (
  SELECT
    PL.NOMBRE            AS PLAN,
    U.CIUDAD_RESIDENCIA  AS CIUDAD
  FROM USUARIOS U
  JOIN PLANES PL ON PL.ID_PLAN = U.ID_PLAN
  WHERE U.ESTADO_CUENTA = 'ACTIVO'
)
PIVOT (
  COUNT(*)
  FOR CIUDAD IN (
    'Bogota'      AS BOGOTA,
    'Medellin'    AS MEDELLIN,
    'Cali'        AS CALI,
    'Barranquilla' AS BARRANQUILLA,
    'Cartagena'   AS CARTAGENA
  )
)
ORDER BY PLAN;

-- UNPIVOT D.3: Desnormalizar el resultado de PIVOT D.1 de vuelta a filas
--   Permite filtrar por dispositivo y mes sin necesidad de manipular columnas.
SELECT DISPOSITIVO, MES_NOMBRE, TOTAL_REPRODUCCIONES
FROM (
  SELECT *
  FROM (
    SELECT
      NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO,
      EXTRACT(MONTH FROM R.FECHA_INICIO)            AS MES,
      R.ID_REPRODUCCION
    FROM REPRODUCCIONES R
  )
  PIVOT (
    COUNT(ID_REPRODUCCION)
    FOR MES IN (
      1  AS MES_1,  2  AS MES_2,  3  AS MES_3,
      4  AS MES_4,  5  AS MES_5,  6  AS MES_6,
      7  AS MES_7,  8  AS MES_8,  9  AS MES_9,
      10 AS MES_10, 11 AS MES_11, 12 AS MES_12
    )
  )
)
UNPIVOT (
  TOTAL_REPRODUCCIONES
  FOR MES_NOMBRE IN (
    MES_1, MES_2, MES_3, MES_4,  MES_5,  MES_6,
    MES_7, MES_8, MES_9, MES_10, MES_11, MES_12
  )
)
WHERE TOTAL_REPRODUCCIONES > 0
ORDER BY DISPOSITIVO, MES_NOMBRE;

-- UNPIVOT D.4: Desnormalizar MV_METRICAS_FINANCIERAS para ver tipo de ingreso como fila
--   Convierte columnas INGRESOS_COBRADOS / INGRESOS_PENDIENTES en filas clasificadas.
SELECT PLAN, PERIODO_ANIO, PERIODO_MES, TIPO_INGRESO, MONTO
FROM MV_METRICAS_FINANCIERAS
UNPIVOT (
  MONTO
  FOR TIPO_INGRESO IN (
    INGRESOS_COBRADOS   AS 'COBRADO',
    INGRESOS_PENDIENTES AS 'PENDIENTE'
  )
)
WHERE MONTO > 0
ORDER BY PLAN, PERIODO_ANIO, PERIODO_MES, TIPO_INGRESO;

-- ============================================================================
-- SECCION E: Agrupamientos Avanzados (4 requeridos por NT1)
-- ============================================================================

-- Agrupamiento E.1: ROLLUP — subtotales jerarquicos de ingresos
--   Produce: subtotal por mes, subtotal por ano, gran total
SELECT
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  SUM(F.MONTO_FINAL)          AS INGRESOS_TOTALES,
  COUNT(F.ID_FACTURACION)     AS TOTAL_FACTURAS
FROM FACTURACIONES F
GROUP BY ROLLUP(F.PERIODO_ANIO, F.PERIODO_MES)
ORDER BY
  F.PERIODO_ANIO NULLS LAST,
  F.PERIODO_MES  NULLS LAST;

-- Agrupamiento E.2: CUBE — todas las combinaciones posibles entre dispositivo y ano
--   Produce: subtotal por dispositivo, por ano, por dispositivo+ano, y gran total
SELECT
  NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo') AS DISPOSITIVO,
  EXTRACT(YEAR FROM R.FECHA_INICIO)             AS ANIO,
  COUNT(R.ID_REPRODUCCION)                      AS TOTAL_REPRODUCCIONES,
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2)            AS PROMEDIO_AVANCE
FROM REPRODUCCIONES R
GROUP BY CUBE(
  NVL(R.ULTIMO_DISPOSITIVO, 'Sin dispositivo'),
  EXTRACT(YEAR FROM R.FECHA_INICIO)
)
ORDER BY
  DISPOSITIVO NULLS LAST,
  ANIO        NULLS LAST;

-- Agrupamiento E.3: GROUPING() — identifica filas de subtotal en resultado ROLLUP
--   GROUPING() retorna 1 cuando la columna es parte de una fila de subtotal.
SELECT
  DECODE(GROUPING(F.PERIODO_ANIO), 1, 'TOTAL GENERAL', TO_CHAR(F.PERIODO_ANIO))
    AS ANIO_LABEL,
  DECODE(GROUPING(F.PERIODO_MES),  1, 'SUBTOTAL ANO',  TO_CHAR(F.PERIODO_MES))
    AS MES_LABEL,
  GROUPING(F.PERIODO_ANIO)         AS ES_TOTAL_GENERAL,
  GROUPING(F.PERIODO_MES)          AS ES_SUBTOTAL_ANO,
  SUM(F.MONTO_FINAL)               AS INGRESOS_TOTALES
FROM FACTURACIONES F
GROUP BY ROLLUP(F.PERIODO_ANIO, F.PERIODO_MES)
ORDER BY
  F.PERIODO_ANIO NULLS LAST,
  F.PERIODO_MES  NULLS LAST;

-- Agrupamiento E.4: GROUPING SETS — combinaciones especificas a eleccion del analista
--   Evita calcular todas las combinaciones del CUBE; solo las que se necesitan.
SELECT
  U.CIUDAD_RESIDENCIA,
  PL.NOMBRE                        AS PLAN,
  COUNT(DISTINCT U.ID_USUARIO)     AS USUARIOS_ACTIVOS,
  SUM(F.MONTO_FINAL)               AS INGRESOS
FROM USUARIOS U
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
JOIN FACTURACIONES F
  ON F.ID_USUARIO = U.ID_USUARIO
GROUP BY GROUPING SETS (
  (U.CIUDAD_RESIDENCIA, PL.NOMBRE),  -- por ciudad y plan
  (U.CIUDAD_RESIDENCIA),             -- solo por ciudad
  (PL.NOMBRE),                       -- solo por plan
  ()                                 -- gran total
)
ORDER BY
  U.CIUDAD_RESIDENCIA NULLS LAST,
  PL.NOMBRE           NULLS LAST;

-- ============================================================================
-- SECCION F: Vistas de Lectura para Endpoints de Analitica del Backend
-- ============================================================================
-- Estas tres vistas son consumidas por los endpoints:
--   GET /api/v1/analytics/consumption
--   GET /api/v1/analytics/finance
--   GET /api/v1/analytics/internal-performance
-- El backend aplica filtros adicionales sobre estas vistas en tiempo de ejecucion.
-- Nota: VW_ANALITICA_CONSUMO puede producir multiples filas por reproduccion
--       cuando el contenido tiene varios generos (comportamiento esperado).
-- ============================================================================

-- Vista F.1: Consumo de contenido por dimension geografica, dispositivo y plan
CREATE OR REPLACE VIEW VW_ANALITICA_CONSUMO AS
SELECT
  U.CIUDAD_RESIDENCIA,
  CAT.NOMBRE                            AS CATEGORIA,
  G.NOMBRE                              AS GENERO,
  R.ULTIMO_DISPOSITIVO,
  PL.NOMBRE                             AS PLAN,
  TRUNC(R.FECHA_INICIO, 'MM')           AS PERIODO_MES,
  COUNT(R.ID_REPRODUCCION)              AS TOTAL_REPRODUCCIONES,
  COUNT(DISTINCT R.ID_PERFIL)           AS PERFILES_UNICOS,
  ROUND(AVG(R.PORCENTAJE_AVANCE), 2)    AS PROMEDIO_AVANCE
FROM REPRODUCCIONES R
JOIN PERFILES P
  ON P.ID_PERFIL = R.ID_PERFIL
JOIN USUARIOS U
  ON U.ID_USUARIO = P.ID_USUARIO
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
JOIN CONTENIDOS C
  ON C.ID_CONTENIDO = R.ID_CONTENIDO
JOIN CATEGORIAS CAT
  ON CAT.ID_CATEGORIA = C.ID_CATEGORIA
LEFT JOIN CONTENIDOS_GENEROS CG
  ON CG.ID_CONTENIDO = C.ID_CONTENIDO
LEFT JOIN GENEROS G
  ON G.ID_GENERO = CG.ID_GENERO
GROUP BY
  U.CIUDAD_RESIDENCIA,
  CAT.NOMBRE,
  G.NOMBRE,
  R.ULTIMO_DISPOSITIVO,
  PL.NOMBRE,
  TRUNC(R.FECHA_INICIO, 'MM');

-- Vista F.2: Metricas financieras por ciudad, plan y periodo de facturacion
CREATE OR REPLACE VIEW VW_ANALITICA_FINANZAS AS
SELECT
  U.CIUDAD_RESIDENCIA,
  PL.NOMBRE                             AS PLAN,
  F.PERIODO_ANIO,
  F.PERIODO_MES,
  COUNT(F.ID_FACTURACION)               AS TOTAL_FACTURAS,
  SUM(F.MONTO_FINAL)                    AS INGRESOS_TOTALES,
  SUM(
    CASE WHEN F.ESTADO_FACTURA = 'PAGADA'
         THEN F.MONTO_FINAL ELSE 0 END
  )                                     AS INGRESOS_COBRADOS,
  SUM(
    CASE WHEN F.ESTADO_FACTURA IN ('PENDIENTE', 'VENCIDA')
         THEN F.MONTO_FINAL ELSE 0 END
  )                                     AS INGRESOS_PENDIENTES,
  COUNT(DISTINCT F.ID_USUARIO)          AS USUARIOS_FACTURADOS
FROM FACTURACIONES F
JOIN USUARIOS U
  ON U.ID_USUARIO = F.ID_USUARIO
JOIN PLANES PL
  ON PL.ID_PLAN = U.ID_PLAN
GROUP BY
  U.CIUDAD_RESIDENCIA,
  PL.NOMBRE,
  F.PERIODO_ANIO,
  F.PERIODO_MES;

-- Vista F.3: Rendimiento interno del equipo por departamento y cohort de ingreso
CREATE OR REPLACE VIEW VW_ANALITICA_RENDIMIENTO AS
SELECT
  D.NOMBRE                              AS DEPARTAMENTO,
  COUNT(E.ID_EMPLEADO)                  AS TOTAL_EMPLEADOS,
  SUM(E.ES_JEFE)                        AS TOTAL_JEFES,
  COUNT(
    CASE WHEN E.ESTADO_EMPLEADO = 'ACTIVO' THEN 1 END
  )                                     AS EMPLEADOS_ACTIVOS,
  EXTRACT(YEAR  FROM E.FECHA_INGRESO)   AS ANIO_INGRESO,
  EXTRACT(MONTH FROM E.FECHA_INGRESO)   AS MES_INGRESO
FROM EMPLEADOS E
JOIN DEPARTAMENTOS D
  ON D.ID_DEPARTAMENTO = E.ID_DEPARTAMENTO
GROUP BY
  D.NOMBRE,
  EXTRACT(YEAR  FROM E.FECHA_INGRESO),
  EXTRACT(MONTH FROM E.FECHA_INGRESO);

-- GRANTs para que ROL_ANALISTA y ROL_ADMIN puedan consultar las vistas y MVs
GRANT SELECT ON VW_ANALITICA_CONSUMO      TO ROL_ANALISTA;
GRANT SELECT ON VW_ANALITICA_FINANZAS     TO ROL_ANALISTA;
GRANT SELECT ON VW_ANALITICA_RENDIMIENTO  TO ROL_ANALISTA;
GRANT SELECT ON MV_CALIFICACIONES_PROMEDIO TO ROL_ANALISTA;
GRANT SELECT ON MV_METRICAS_FINANCIERAS   TO ROL_ANALISTA;

GRANT SELECT ON VW_ANALITICA_CONSUMO      TO ROL_ADMIN;
GRANT SELECT ON VW_ANALITICA_FINANZAS     TO ROL_ADMIN;
GRANT SELECT ON VW_ANALITICA_RENDIMIENTO  TO ROL_ADMIN;
GRANT SELECT ON MV_CALIFICACIONES_PROMEDIO TO ROL_ADMIN;
GRANT SELECT ON MV_METRICAS_FINANCIERAS   TO ROL_ADMIN;

COMMIT;

-- Verificacion final: consultar las tres vistas
SELECT 'VW_ANALITICA_CONSUMO'     AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_CONSUMO
UNION ALL
SELECT 'VW_ANALITICA_FINANZAS'    AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_FINANZAS
UNION ALL
SELECT 'VW_ANALITICA_RENDIMIENTO' AS VISTA, COUNT(*) AS FILAS FROM VW_ANALITICA_RENDIMIENTO;
